#ifdef SPANISH
	#define STR0001 "Relacion de usuarios"
	#define STR0002 "Emision del Archivo de usuarios"
	#define STR0003 "Imprimira los datos de los usuarios de   "
	#define STR0004 "acuerdo con la configuracion del usuario."
	#define STR0005 "A rayas"
	#define STR0006 "Administracion"
	#define STR0007 "LISTADO DEL ARCHIVO DE USUARIOS"
	#define STR0008 "¡No se encontro el archivo de accesos!"
	#define STR0009 "Atencion"
	#define STR0010 "Configuraciones elo Administrador"
	#define STR0011 "Numero de errores"
	#define STR0012 "Numero de contrasenas por guardar"
	#define STR0013 "Usa nombre para verificar la contrasena"
	#define STR0014 "Si"
	#define STR0015 "No"
	#define STR0016 "Tamano minimo de la contrasena"
	#define STR0017 "Usa bloqueo de usuario"
	#define STR0018 "E-mail"
	#define STR0019 "Configuraciones de los Grupos"
	#define STR0020 "** Grupo **"
	#define STR0021 "ID"
	#define STR0022 "Nombre"
	#define STR0023 "Validez de la Clave"
	#define STR0024 "Cant de dias para expirar la contrasena"
	#define STR0025 "Autorizado para modificar contrasena"
	#define STR0026 "Directorio de informe"
	#define STR0027 "Impresora"
	#define STR0028 "Empresas"
	#define STR0029 "Fecha de ultima modific."
	#define STR0030 "Tipo de impresion"
	#define STR0031 "En disco"
	#define STR0032 "Por Windows"
	#define STR0033 "Directo en el puerto"
	#define STR0034 "Formato"
	#define STR0035 "Retrato"
	#define STR0036 "Apaisada"
	#define STR0037 "Entorno"
	#define STR0038 "Servidor"
	#define STR0039 "Cliente"
	#define STR0040 "Opcion de impresion"
	#define STR0041 "Acceso a otros dir. de impresion"
	#define STR0042 "Restricc. de Accesos  | Domingo  | Lunes    | Martes   | Miercoles| Jueves   | Viernes  | Sabado  |"
	#define STR0043 "              Inicio "
	#define STR0044 "                 Fin "
	#define STR0045 "Configurac.de los Usuarios"
	#define STR0046 "** Usuario **"
	#define STR0047 "Nomb.Completo"
	#define STR0048 "Ext. "
	#define STR0049 "Fch. de Validez"
	#define STR0050 "Autorizado para cambiar la contrasena"
	#define STR0051 "Modificar la contrasena en el proximo Logon"
	#define STR0052 "Grupo(s)"
	#define STR0053 "ID del Supervisor"
	#define STR0054 "Departamento"
	#define STR0055 "Cargo"
	#define STR0056 "Numero de accesos simultaneos"
	#define STR0057 "Fecha de la ultima modificacion"
	#define STR0058 "Usuario bloqueado"
	#define STR0059 "Numero de digitos para el año"
	#define STR0060 "Prioridad de Grupo"
	#define STR0061 "Todas"
	#define STR0062 "Accesos"
	#define STR0063 "Modulo"
	#define STR0064 "Nivel"
	#define STR0065 "Menu"
	#define STR0066 "Procesos"
	#define STR0067 "Inclusion de Reg."
	#define STR0068 "Modificacion de Reg."
	#define STR0069 "Informes"
	#define STR0070 "Transacciones"
	#define STR0071 "Respuesta de Parametros"
	#define STR0072 "Log de Operaciones del Sistema"
	#define STR0073 " - Si"
	#define STR0074 " - No"
	#define STR0075 " - Estandar"
	#define STR0076 "Configurador"
	#define STR0077 "De Usuario"
	#define STR0078 "A Usuario"
	#define STR0079 "De Grupo"
	#define STR0080 "A Grupo"
	#define STR0081 "Salta Pagina Grupo/Usuario"
	#define STR0082 "Cod/Suc"
	#define STR0083 "Empresa/Sucursal"
	#define STR0084 "Fecha de la inclusion"
	#define STR0085 "¿Imprime Detalles del Menu?"
	#define STR0086 "Rutina                   Funcion   Opciones"
	#define STR0087 "Imprime Usuários Bloqueados?"
#else
	#ifdef ENGLISH
		#define STR0001 "Users List"
		#define STR0002 "Print Users File"
		#define STR0003 "It will print data on users   "
		#define STR0004 "according to the user's setup."
		#define STR0005 "Z.Form "
		#define STR0006 "Management   "
		#define STR0007 "USERS FILE LIST"
		#define STR0008 "Access file not found!"
		#define STR0009 "Warning"
		#define STR0010 "Administrator`s Setup"
		#define STR0011 "Number of errors"
		#define STR0012 "Number of passwords to save"
		#define STR0013 "Use name to verify password"
		#define STR0014 "Yes"
		#define STR0015 "No"
		#define STR0016 "Password minimum lengh"
		#define STR0017 "Use User locking"
		#define STR0018 "E-mail"
		#define STR0019 "Groups Settings"
		#define STR0020 "** Group **"
		#define STR0021 "ID"
		#define STR0022 "Name"
		#define STR0023 "Password Validity"
		#define STR0024 "No. of days to password expire"
		#define STR0025 "Authorized to change password"
		#define STR0026 "Report directory"
		#define STR0027 "Printer"
		#define STR0028 "Companies"
		#define STR0029 "Last updating date"
		#define STR0030 "Print type"
		#define STR0031 "To Disk"
		#define STR0032 "Via Windows"
		#define STR0033 "Direct to port"
		#define STR0034 "Format"
		#define STR0035 "Portrait"
		#define STR0036 "Landscape"
		#define STR0037 "Environment"
		#define STR0038 "Server"
		#define STR0039 "Customer"
		#define STR0040 "Print Option"
		#define STR0041 "Access to other print dir."
		#define STR0042 "Access Restriction    |  Sunday  |  Monday  |  Tuesday |Wednesday | Thursday |  Friday  |Saturday |"
		#define STR0043 "           Beginning "
		#define STR0044 "                 End "
		#define STR0045 "Users Settings"
		#define STR0046 "** User **"
		#define STR0047 "Full Name"
		#define STR0048 "Extension"
		#define STR0049 "Expiring Date"
		#define STR0050 "Authorized to change password"
		#define STR0051 "Change password on next Logon"
		#define STR0052 "Group(s)"
		#define STR0053 "Supervisor`s ID"
		#define STR0054 "Department"
		#define STR0055 "Position"
		#define STR0056 "Number of simultaneous accesses"
		#define STR0057 "Last updating date"
		#define STR0058 "User locked"
		#define STR0059 "Number of digits to year"
		#define STR0060 "Group`s Priority"
		#define STR0061 "All"
		#define STR0062 "Accesses"
		#define STR0063 "Module"
		#define STR0064 "Level"
		#define STR0065 "Menu"
		#define STR0066 "Processes"
		#define STR0067 "Rec. Insertion"
		#define STR0068 "Rec. Update"
		#define STR0069 "Reports"
		#define STR0070 "Transactions"
		#define STR0071 "Parameters Response"
		#define STR0072 "System Operations Log"
		#define STR0073 " - Yes"
		#define STR0074 " - No"
		#define STR0075 " - Standard"
		#define STR0076 "Configurator"
		#define STR0077 "From User"
		#define STR0078 "To User"
		#define STR0079 "From Group"
		#define STR0080 "To Group"
		#define STR0081 "Skip Group/User Page"
		#define STR0082 "Cod/Brc"
		#define STR0083 "Company/Branch"
		#define STR0084 "Addition date   "
		#define STR0085 "Print Menu Details?"
		#define STR0086 "Routine                  Function  Options"
		#define STR0087 "Imprime Usuários Bloqueados?"
	#else
		Static STR0001 := "Relação de usuários"
		Static STR0002 := "Emissão do Cadastro de usuários"
		Static STR0003 := "Ira imprimir os dados dos usuários      "
		Static STR0004 := "de acordo com a configuração do usuário."
		Static STR0005 := "Zebrado"
		#define STR0006  "Administração"
		Static STR0007 := "RELACAO DO CADASTRO DE USUÁRIOS"
		Static STR0008 := "Arquivo de acessos não Encontrado!"
		#define STR0009  "Atenção"
		Static STR0010 := "Configurações do Administrador"
		Static STR0011 := "Numero de erros"
		Static STR0012 := "Numero de senhas a guardar"
		Static STR0013 := "Usa nome para verificar a senha"
		#define STR0014  "Sim"
		#define STR0015  "Não"
		Static STR0016 := "Tamanho mínimo da senha"
		Static STR0017 := "Usa bloqueio de usuário"
		#define STR0018  "E-mail"
		Static STR0019 := "Configurações dos Grupos"
		Static STR0020 := "** Grupo **"
		Static STR0021 := "ID"
		#define STR0022  "Nome"
		Static STR0023 := "Validade da Senha"
		Static STR0024 := "Qtde de dias para expirar a senha"
		Static STR0025 := "Autorizado a alterar senha"
		Static STR0026 := "Diretório de relatório"
		#define STR0027  "Impressora"
		#define STR0028  "Empresas"
		#define STR0029  "Data de última alteração"
		#define STR0030  "Tipo de impressão"
		#define STR0031  "Em disco"
		#define STR0032  "Via Windows"
		Static STR0033 := "Direta na porta"
		#define STR0034  "Formato"
		#define STR0035  "Retrato"
		#define STR0036  "Paisagem"
		#define STR0037  "Ambiente"
		#define STR0038  "Servidor"
		#define STR0039  "Cliente"
		#define STR0040  "Opção de impressão"
		#define STR0041  "Acesso a outros dir. de impressão"
		Static STR0042 := "Restrição de Acessos  | Domingo  | Segunda  | Terca    | Quarta   | Quinta   | Sexta    | Sábado  |"
		Static STR0043 := "              Inicio "
		Static STR0044 := "                 Fim "
		Static STR0045 := "Configurações dos Usuários"
		Static STR0046 := "** Usuário **"
		#define STR0047  "Nome Completo"
		Static STR0048 := "Ramal"
		Static STR0049 := "Data de Validade"
		Static STR0050 := "Autorizado a alterar a senha"
		Static STR0051 := "Alterar a senha no próximo Logon"
		#define STR0052  "Grupo(s)"
		Static STR0053 := "ID do Supervisor"
		#define STR0054  "Departamento"
		#define STR0055  "Cargo"
		#define STR0056  "Número de acessos simultâneos"
		#define STR0057  "Data da última alteração"
		Static STR0058 := "Usuário bloqueado"
		Static STR0059 := "Número de digitos para o ano"
		Static STR0060 := "Prioridade de Grupo"
		#define STR0061  "Todas"
		#define STR0062  "Acessos"
		#define STR0063  "Módulo"
		#define STR0064  "Nível"
		#define STR0065  "Menu"
		#define STR0066  "Processos"
		Static STR0067 := "Inclusão de Reg."
		Static STR0068 := "Alteração de Reg."
		#define STR0069  "Relatórios"
		Static STR0070 := "Transações"
		Static STR0071 := "Resposta de Parametros"
		Static STR0072 := "Log de OperaçÕes do Sistema"
		#define STR0073  " - Sim"
		#define STR0074  " - Não"
		#define STR0075  " - Padrão"
		#define STR0076  "Configurador"
		Static STR0077 := "Do Usuario"
		Static STR0078 := "Ate Usuario"
		#define STR0079  "Do Grupo"
		Static STR0080 := "Ate Grupo"
		Static STR0081 := "Salta Pagina Grupo/Usuario"
		Static STR0082 := "Cod/Fil"
		Static STR0083 := "Empresa/Filial"
		Static STR0084 := "Data da inclusão"
		Static STR0085 := "Imprime Detalhes do Menu?"
		Static STR0086 := "Rotina                   Função    Opções"
		Static STR0087 := "Imprime Usuários Bloqueados?"
	#endif
#endif

#ifndef SPANISH
#ifndef ENGLISH
	STATIC uInit := __InitFun()

	Static Function __InitFun()
	uInit := Nil
	If Type('cPaisLoc') == 'C'

		If cPaisLoc == "PTG"
			STR0001 := "Relação de utilizadores"
			STR0002 := "Emissão do registo de utilizadores"
			STR0003 := "Irá imprimir os dados dos utilizadores      "
			STR0004 := "De acordo com a configuração do utilizador."
			STR0005 := "Código de barras"
			STR0007 := "Relação Do Registo De Utilizadores"
			STR0008 := "Ficheiro De Acessos Não Encontrado!"
			STR0010 := "Configurações Do Administrador"
			STR0011 := "Número de erros"
			STR0012 := "Número de palavras-passe a guardar"
			STR0013 := "Utilizar nome para verificar a palavra-passe"
			STR0016 := "Tamanho mínimo da palavra-passe"
			STR0017 := "Utilizar bloqueio de utilizador"
			STR0019 := "Configurações Dos Grupos"
			STR0020 := "** grupo **"
			STR0021 := "Id"
			STR0023 := "Validade Da Palavra-passe"
			STR0024 := "Qtde de dias para expirar a palavra-passe"
			STR0025 := "Autorizado a alterar palavra-passe"
			STR0026 := "Directório de relatório"
			STR0033 := "Directa na porta"
			STR0042 := "Restrição de acessos  | domingo  | segunda  | terça    | quarta   | quinta   | sexta    | sábado  |"
			STR0043 := "              início "
			STR0044 := "                 fim "
			STR0045 := "Configurações Dos Utilizadores"
			STR0046 := "** utilizador **"
			STR0048 := "Extensão"
			STR0049 := "Data De Validade"
			STR0050 := "Autorizado a alterar a palavra-passe"
			STR0051 := "Alterar A Palavra-passe No Próximo Logon"
			STR0053 := "Id Do Supervisor"
			STR0058 := "Utilizador bloqueado"
			STR0059 := "Número de dígitos para o ano"
			STR0060 := "Prioridade De Grupo"
			STR0067 := "Inclusão De Reg."
			STR0068 := "Alteração De Reg."
			STR0070 := "Transacoes"
			STR0071 := "Resposta De Parâmetros"
			STR0072 := "Diário De Operações Do Sistema"
			STR0077 := "Do Utilizador"
			STR0078 := "Até Utilizador"
			STR0080 := "Até Grupo"
			STR0081 := "Salta Página Grupo/utilizador"
			STR0082 := "Cód/fil"
			STR0083 := "Empresa/filial"
			STR0084 := "Data da inserção"
			STR0085 := "Imprimir Detalhes Do Menu?"
			STR0086 := "Procedimento                   Função    Opções"
			STR0087 := "Imprime Usuários Bloqueados?"
		EndIf
		EndIf
	Return Nil
#ENDIF
#ENDIF
