#ifdef SPANISH
	#define STR0001 "Para seleccionar un informe utilice: "
	#define STR0002 "Doble clic o <Enter> en el informe marcado para mostrar."
	#define STR0003 "Archivos"
	#define STR0004 "Buscar"
	#define STR0005 "Imprimir"
	#define STR0006 "Administrador de Impresion"
	#define STR0007 "Entorno"
	#define STR0008 "Servidor"
	#define STR0009 "Cliente"
	#define STR0010 "Directorio: "
	#define STR0011 "Seleccione el Directorio"
	#define STR0012 "Buscar: "
	#define STR0013 "Fecha"
	#define STR0014 "Hora"
	#define STR0015 "Tamano"
	#define STR0016 "Pagina actual"
	#define STR0017 "Informe actual"
	#define STR0018 "Considera mayusculas y minusculas"
	#define STR0019 "Buscar: "
	#define STR0020 "Iniciar busqueda"
	#define STR0021 "Resultado de la busqueda"
	#define STR0022 "Pagina"
	#define STR0023 "Ocurrencias"
	#define STR0024 "Tipo de Impresion"
	#define STR0025 "Por Windows"
	#define STR0026 "Directo en la puerta"
	#define STR0027 "Driver:"
	#define STR0028 "Puerta:"
	#define STR0029 "Impresora"
	#define STR0030 "A"
	#define STR0031 "Asunto"
	#define STR0032 "Descripcion"
	#define STR0033 "Recibir copia del e-mail"
	#define STR0034 "Opciones"
	#define STR0035 "Todas las paginas"
	#define STR0036 "Intervalo"
	#define STR0037 "Inicio: "
	#define STR0038 "Fin: "
	#define STR0039 "Margen"
	#define STR0040 "Confirma borrado del informe: "
	#define STR0041 "Ocurrio un error al abrir el informe. Error: "
	#define STR0042 "Error de apertura"
	#define STR0043 "No fue posible cerrar el informe"
	#define STR0044 ". Error: "
	#define STR0045 "Error"
	#define STR0046 "Imprimiendo informe. Espere..."
	#define STR0047 "Directorio de informes"
	#define STR0048 "El directorio informado no contiene informes"
	#define STR0049 "¡Archivo vacio!"
	#define STR0050 "Elija la pagina"
	#define STR0051 "Ir a la pagina: "
	#define STR0052 "No se encontro ninguna ocurrencia."
	#define STR0053 "Archivo"
	#define STR0054 "Configuracion"
	#define STR0055 "Salir"
	#define STR0056 "Pagina "
	#define STR0057 " de "
	#define STR0058 "Numero de copias"
	#define STR0059 "Usuario sin autorizacion para acceder informes en el servidor."
	#define STR0060 " se utilizara el directorio estandar."
	#define STR0061 "Formato HTML"
	#define STR0062 "Nuevo Mensaje"
	#define STR0063 "Asunto:"
	#define STR0064 "Descripcion:"
	#define STR0065 "El campo de direcciones no se informo."

	#define STR0066 " No fue posible obtener acceso exclusivo al informe "
	#define STR0067 ". Puede esta bloqueado o sendo utilizado por otro usuario."
	#define STR0068 "Actualice el Protheus Server y Remote para visualizar los informes personalizables"
	#define STR0069 "¡Problemas en la generacion del archivo!"
#else
	#ifdef ENGLISH
		#define STR0001 "To select a report use: "
		#define STR0002 "Duble click or <Enter> on the report checked to be shown."
		#define STR0003 "Files"
		#define STR0004 "Search"
		#define STR0005 "Print"
		#define STR0006 "Printing Manager"
		#define STR0007 "Environment"
		#define STR0008 "Server"
		#define STR0009 "Customer"
		#define STR0010 "Directory : "
		#define STR0011 "Select the Directory"
		#define STR0012 "Find : "
		#define STR0013 "Date"
		#define STR0014 "Time"
		#define STR0015 "Size"
		#define STR0016 "Current page"
		#define STR0017 "Current report"
		#define STR0018 "Consider capital and small letters"
		#define STR0019 "Search by : "
		#define STR0020 "Start search"
		#define STR0021 "Searching result"
		#define STR0022 "Page"
		#define STR0023 "Occurrences"
		#define STR0024 "Printing Type"
		#define STR0025 "Via Windows"
		#define STR0026 "Straight at the drawer"
		#define STR0027 "Driver :"
		#define STR0028 "Drawer:"
		#define STR0029 "Printer"
		#define STR0030 "To"
		#define STR0031 "Subject"
		#define STR0032 "Description"
		#define STR0033 "Receive a copy of the e-mail"
		#define STR0034 "Options"
		#define STR0035 "All the pages"
		#define STR0036 "Interval"
		#define STR0037 "Start : "
		#define STR0038 "End : "
		#define STR0039 "Margin"
		#define STR0040 "Confirm the report deletion : "
		#define STR0041 "There has been an error while opening the report. Error: "
		#define STR0042 "Error while opening"
		#define STR0043 "It was not possible to close the report "
		#define STR0044 ". Error: "
		#define STR0045 "Error"
		#define STR0046 "Printing report. Please, wait..."
		#define STR0047 "Reports directory"
		#define STR0048 "The informed directory does not have reports"
		#define STR0049 "Empty file !"
		#define STR0050 "Select the page"
		#define STR0051 "Go to page : "
		#define STR0052 "No occurrence was found."
		#define STR0053 "File"
		#define STR0054 "Configuration"
		#define STR0055 "Exit"
		#define STR0056 "Page "
		#define STR0057 " of "
		#define STR0058 "Copies quantity"
		#define STR0059 "User is not allowed to access reports in the server."
		#define STR0060 " standard directory to be used. "
		#define STR0061 "HTML format "
		#define STR0062 "New Message  "
		#define STR0063 "Subject:"
		#define STR0064 "Descript.:"
		#define STR0065 "The Addresses field was not input."

		#define STR0066 "Unable to obtain exclusive access to report.  "
		#define STR0067 ". May be blocked or in use by another user. "
		#define STR0068 "Update Protheus Server and Remote to view customizable reports "
		#define STR0069 "Problems in generating file!"
	#else
		Static STR0001 := "Para selecionar um relatório utilize : "
		Static STR0002 := "Duplo click ou <Enter> no relatorio marcado para exibir."
		Static STR0003 := "Arquivos"
		#define STR0004  "Procurar"
		#define STR0005  "Imprimir"
		Static STR0006 := "Gerenciador de Impressão"
		#define STR0007  "Ambiente"
		#define STR0008  "Servidor"
		#define STR0009  "Cliente"
		Static STR0010 := "Diretório : "
		Static STR0011 := "Selecione o Diretório"
		#define STR0012  "Localizar : "
		#define STR0013  "Data"
		#define STR0014  "Hora"
		#define STR0015  "Tamanho"
		Static STR0016 := "Página atual"
		Static STR0017 := "Relatório atual"
		Static STR0018 := "Considera maisculas e minusculas"
		#define STR0019  "Procurar por : "
		#define STR0020  "Iniciar busca"
		#define STR0021  "Resultado da pesquisa"
		#define STR0022  "Página"
		#define STR0023  "Ocorrências"
		Static STR0024 := "Tipo de Impressão"
		#define STR0025  "Via Windows"
		Static STR0026 := "Direto na porta"
		#define STR0027  "Driver :"
		#define STR0028  "Porta :"
		#define STR0029  "Impressora"
		#define STR0030  "Para"
		#define STR0031  "Assunto"
		#define STR0032  "Descrição"
		#define STR0033  "Receber cópia do e-mail"
		#define STR0034  "Opções"
		#define STR0035  "Todas as páginas"
		#define STR0036  "Intervalo"
		#define STR0037  "Início : "
		#define STR0038  "Fim : "
		#define STR0039  "Margem"
		Static STR0040 := "Confirma a exclusão do relatório : "
		Static STR0041 := "Ocorreu um erro na abertura do relatorio.  Erro : "
		#define STR0042  "Erro na abertura"
		#define STR0043  "Não foi possível fechar o relatório "
		Static STR0044 := ". Erro : "
		#define STR0045  "Erro"
		Static STR0046 := "Imprimindo relatorio. Aguarde..."
		Static STR0047 := "Diretório de relatórios"
		Static STR0048 := "O diretório informado não contém relatórios"
		Static STR0049 := "Arquivo vazio !"
		Static STR0050 := "Escolha a pagina"
		#define STR0051  "Ir para a página : "
		Static STR0052 := "Nenhuma ocorrência foi encontra."
		Static STR0053 := "Arquivo"
		#define STR0054  "Configuração"
		#define STR0055  "Sair"
		Static STR0056 := "Pagina "
		#define STR0057  " de "
		Static STR0058 := "Numero de copias"
		Static STR0059 := "Usuario sem permissao para acessar relatorios no servidor."
		Static STR0060 := " o diretorio padrao sera utilizado."
		Static STR0061 := "Formato HTML"
		#define STR0062  "Nova Mensagem"
		#define STR0063  "Assunto:"
		#define STR0064  "Descrição:"
		Static STR0065 := "O campo de Endereços não foi informado."

		#define STR0066  "Não foi possível obter acesso exclusivo ao relatório "
		Static STR0067 := ". Pode estar bloqueado ou sendo utilizado por outro usuário."
		Static STR0068 := "Atualize o Protheus Server e Remote para visualizar os relatorios personalizaveis"
		Static STR0069 := "Problemas na geração do arquivo !!!"
	#endif
#endif

#ifndef SPANISH
#ifndef ENGLISH
	STATIC uInit := __InitFun()

	Static Function __InitFun()
	uInit := Nil
	If Type('cPaisLoc') == 'C'

		If cPaisLoc == "PTG"
			STR0001 := "Para seleccionar um relatório utilize : "
			STR0002 := "Duplo clique ou <enter> no relatório marcado para exibir."
			STR0003 := "Ficheiros"
			STR0006 := "Gestor De Impressão"
			STR0010 := "Directório : "
			STR0011 := "Seleccione O Directório"
			STR0016 := "Página actual"
			STR0017 := "Relatório actual"
			STR0018 := "Considerar maiúsculas e minúsculas"
			STR0024 := "Tipo de impressão"
			STR0026 := "Directo na porta"
			STR0040 := "Confirmar a exclusão do relatório : "
			STR0041 := "Ocorreu um erro na abertura do relatório.  erro : "
			STR0044 := ". erro : "
			STR0046 := "A Imprimir Relatório. Aguarde..."
			STR0047 := "Directório de relatórios"
			STR0048 := "O directório introduzido não contém relatórios"
			STR0049 := "Ficheiro vazio !"
			STR0050 := "Escolha a página"
			STR0052 := "Nenhuma ocorrência foi encontrada."
			STR0053 := "Ficheiro"
			STR0056 := "Página "
			STR0058 := "Número de cópias"
			STR0059 := "Utilizador sem permissão para aceder a relatórios no servidor."
			STR0060 := " o directório padrão será utilizado."
			STR0061 := "Formato Html"
			STR0065 := 'O campo de Moradas não foi informado.'
			STR0067 := ". pode estar bloqueado ou a ser utilizado por outro utilizador."
			STR0068 := "Actualize o Protheus Server e Remote para visualizar os relatórios personalizáveis"
			STR0069 := "Problemas na criação do ficheiro !!!"
		EndIf
		EndIf
	Return Nil
#ENDIF
#ENDIF
