/*
旼컴컴컴컴컴컴컴컴컴커
쿛osicoes para aProps�
읕컴컴컴컴컴컴컴컴컴켸
*/
#DEFINE APROP_NTAM  13
#DEFINE APROP_ITEM  01
#DEFINE APROP_PROP  02
#DEFINE APROP_TIT   03
#DEFINE APROP_TIPO  04
#DEFINE APROP_TAM   05
#DEFINE APROP_DEC   06
#DEFINE APROP_PICT  07
#DEFINE APROP_VAL   08
#DEFINE APROP_VLANT 09
#DEFINE APROP_OBJ   10
#DEFINE APROP_CBOX  11
#DEFINE APROP_F3    12
#DEFINE APROP_NREG  13