#IFDEF SPANISH
   #define STR0001 "ARCHIVO DE MODELO DE LISTA"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "CADASTRO DE MODELO DE GRADE"
   #ELSE
      #define STR0001 "CADASTRO DE MODELO DE GRADE"
   #ENDIF
#ENDIF
