#IFDEF SPANISH
   #define STR0001 "Este programa tem como objetivo imprimir relatorio "
   #define STR0002 "de acordo com os parametros informados pelo usuario."
   #define STR0003 "Escala Salarial de Mao de Obra do Projeto"
   #define STR0004 "Zebrado"
   #define STR0005 "Administracao"
   #define STR0006 "Codigo             Descricao                               Pad.Salarial    Salario Base    Salario Hora  %Encargos  Sal. Encargos"
   #define STR0007 "*** CANCELADO PELO OPERADOR ***"
   #define STR0008 "Projeto : "
   #define STR0009 "Cliente : "
   #define STR0010 "Edital  : "
   #define STR0011 "Inicio  : "
   #define STR0012 "  Fim  : "
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Este programa tem como objetivo imprimir relatorio "
      #define STR0002 "de acordo com os parametros informados pelo usuario."
      #define STR0003 "Escala Salarial de Mao de Obra do Projeto"
      #define STR0004 "Zebrado"
      #define STR0005 "Administracao"
      #define STR0006 "Codigo             Descricao                               Pad.Salarial    Salario Base    Salario Hora  %Encargos  Sal. Encargos"
      #define STR0007 "*** CANCELADO PELO OPERADOR ***"
      #define STR0008 "Projeto : "
      #define STR0009 "Cliente : "
      #define STR0010 "Edital  : "
      #define STR0011 "Inicio  : "
      #define STR0012 "  Fim  : "
   #ELSE
      #define STR0001 "Este programa tem como objetivo imprimir relatorio "
      #define STR0002 "de acordo com os parametros informados pelo usuario."
      #define STR0003 "Escala Salarial de Mao de Obra do Projeto"
      #define STR0004 "Zebrado"
      #define STR0005 "Administracao"
      #define STR0006 "Codigo             Descricao                               Pad.Salarial    Salario Base    Salario Hora  %Encargos  Sal. Encargos"
      #define STR0007 "*** CANCELADO PELO OPERADOR ***"
      #define STR0008 "Projeto : "
      #define STR0009 "Cliente : "
      #define STR0010 "Edital  : "
      #define STR0011 "Inicio  : "
      #define STR0012 "  Fim  : "
   #ENDIF
#ENDIF
