#ifdef SPANISH
	#define STR0001 "El servicio de Totvs Microsiga Protheus no fue registrado en el ECM. Ejecute nuevamente el Mantenimiento de Procesos ECM en el Configurador de Totvs Microsiga Protheus."
	#define STR0002 "Complete los datos del formulario"
	#define STR0003 "Hubo un error en el servicio de Totvs Microsiga Protheus"
	#define STR0004 "Verifique la configuracion en el ECM o ejecute nuevamente el Mantenimiento de Procesos ECM en el Totvs Microsiga Protheus"
	#define STR0005 "Hubo un error en la comunicacion con el servicio de Totvs Microsiga Protheus, verifique los datos del formulario"
	#define STR0006 "El campo"
	#define STR0007 "contiene una fecha invalida"
	#define STR0008 "contiene un numero (valor o tamano) invalido"
	#define STR0009 "no se completo"
	#define STR0010 "Complete al menos una linea de grillas"
	#define STR0011 "Hubo una modificacion en la estructura de datos. Por favor actualice el proceso a traves de la opcion Mantenimiento de Procesos ECM del Configurador de Protheus para continuar."
#else
	#ifdef ENGLISH
		#define STR0001 "Totvs Microsiga Protheus service has not been registered in the ECM. Run ECM Processes Maintenance again in Totvs Microsiga Protheus Configurator."
		#define STR0002 "Fill out form data"
		#define STR0003 "Error in Totvs Microsiga Protheus service"
		#define STR0004 "Check the ECM configuration or run the ECM Processes Maintenance in Totvs Microsiga Protheus again"
		#define STR0005 "Error in communication with Totvs Microsiga Protheus service, check form data"
		#define STR0006 "The field"
		#define STR0007 "contains an invalid date"
		#define STR0008 "contains an invalid number (value or length)"
		#define STR0009 "was not filled out"
		#define STR0010 "Fill out at least one row of grids"
		#define STR0011 "There was a change in data structure. Please update process through option ECM Process Maintenance of Protheus Configurator to continue."
	#else
		#define STR0001 "O serviço do Totvs Microsiga Protheus não foi registrado no ECM. Execute novamente a Manutenção de Processos ECM no Configurador do Totvs Microsiga Protheus."
		#define STR0002 "Preencha os dados do formulário"
		#define STR0003 "Ocorreu erro no serviço do Totvs Microsiga Protheus"
		#define STR0004 "Verifique a configuração no ECM ou execute novamente a Manutenção de Processos ECM no Totvs Microsiga Protheus"
		#define STR0005 "Ocorreu um erro na comunicação com o serviço do Totvs Microsiga Protheus, verifique os dados do formulário"
		#define STR0006 "O campo"
		#define STR0007 "contém uma data inválida"
		#define STR0008 "contém um número (valor ou tamanho) inválido"
		#define STR0009 "não foi preenchido"
		#define STR0010 "Preencha pelo menos uma linha das grades"
		#define STR0011 "Houve uma alteração na estrutura de dados. Por favor atualize o processo através da opção Manutenção de Processos ECM do Configurador do Protheus para continuar."
	#endif
#endif
