#ifdef SPANISH
	#define STR0001 "A solicitação de importação informada não foi encontrada."
	#define STR0002 "A ação de exclusão não pode ser realizada para a solicitação de importação. Para anular o processo, envie uma ação de cancelamento."
	#define STR0003 "Solicitação de importação não informada"
	#define STR0004 "O motivo do cancelamento não foi informado."
	#define STR0005 "A solicitação de importação não pode ser cancelada pois o processo encontra-se em fase subsequente. Status atual: "
	#define STR0006 "Pendente"
	#define STR0007 "Em processo de cotação"
	#define STR0008 "Cotado no mercado nacional"
	#define STR0009 "Aguardando Purchase Order"
	#define STR0010 "Cancelado"
	#define STR0011 "Atendida - em fase de Purchase Order"
#else
	#ifdef ENGLISH
		#define STR0001 "Entered import request not found."
		#define STR0002 "Cannot execute deletion for import request. To void the process, send a cancellation action."
		#define STR0003 "Import request not entered"
		#define STR0004 "Cancellation reason not entered!"
		#define STR0005 "Cannot cancel import request because the process is in a subsequent phase. Current Status: "
		#define STR0006 "Pending"
		#define STR0007 "In quotation process"
		#define STR0008 "Quoted in the domestic market"
		#define STR0009 "Waiting for Purchase Order"
		#define STR0010 "Canceled"
		#define STR0011 "Served - in Purchase Order phase"
	#else
		#define STR0001 "A solicitação de importação informada não foi encontrada."
		#define STR0002 "A ação de exclusão não pode ser realizada para a solicitação de importação. Para anular o processo, envie uma ação de cancelamento."
		#define STR0003 "Solicitação de importação não informada"
		#define STR0004 "O motivo do cancelamento não foi informado."
		#define STR0005 "A solicitação de importação não pode ser cancelada pois o processo encontra-se em fase subsequente. Status atual: "
		#define STR0006 "Pendente"
		#define STR0007 "Em processo de cotação"
		#define STR0008 "Cotado no mercado nacional"
		#define STR0009 "Aguardando Purchase Order"
		#define STR0010 "Cancelado"
		#define STR0011 "Atendida - em fase de Purchase Order"
	#endif
#endif
