#IFDEF SPANISH
	#define STR0001 "Resumen de Caja"
	#define STR0002 "Creditos(Ventas)"
	#define STR0003 "Debitos(Retiros) "
	#define STR0004 "&Codigo de Caja: "
	#define STR0005 "Saldo Inicial:"
	#define STR0006 "Fecha del Movimiento:"
	#define STR0007 "Dinero  "
	#define STR0008 "Cheques"
	#define STR0009 "Tarjetas de Credito"
	#define STR0010 "Convenios"
	#define STR0011 "Vales/Ingresos"
	#define STR0012 "Financiado"
	#define STR0013 "Otros"
	#define STR0014 "Total de Ventas"
	#define STR0015 "Vales/Gastos "
	#define STR0016 "Devoluciones"
	#define STR0017 "Total de Debitos"
	#define STR0018 "SALDO FINAL:"
	#define STR0019 "&Imprimir"
	#define STR0020 "&Salir"
	#define STR0021 "Esta opcion permite imprimir el Cierre de Caja        "
	#define STR0022 "de la fecha actual."
	#define STR0023 "Cierre de Caja     "
	#define STR0024 "A Rayas"
	#define STR0025 "Administracion"
	#define STR0026 "| Empresa :"
	#define STR0027 "|                          CIERRE DE LA CAJA                          |"
	#define STR0028 "| Codigo :"
	#define STR0029 "| Fch del Movimiento:                             "
	#define STR0030 "| Saldo Inicial .................................."
	#define STR0031 "| V E N T A S ...................................."
	#define STR0032 "| Devolucion......................................"
	#define STR0033 "| S A N G R I A .................................."
	#define STR0034 "| Saldo Final ...................................."
	#define STR0035 "Posicion Caja General "
	#define STR0036 "Vales"
	#define STR0037 "Total General"
	#define STR0038 "Salir"
	#define STR0039 "Seleccionando Registros..."
	#define STR0040 "Contra Vales"
	#define STR0041 "Tarjetas de Debito"
	#DEFINE STR0042 "Pagos"
	#DEFINE STR0043 "Transferencias"
	#DEFINE STR0044 "Cobros"
	#DEFINE STR0045 "Credito de Venta"
   #define STR0046 "SALDO FINAL"
   #define STR0047 "Valores"
   #define STR0048 "|                                  |-----------------TOTALIZADORES EN LITROS-------------------|                                   |"
   #define STR0049 "|SURT./PRODUCTO                    |APERTURA           |  CIERRE           |VENTAS             | CANTIDAD TOTAL VENDIDA (LITROS)   |"
   #define STR0050 "*** ANULADO POR EL OPERADOR ***"
   #define STR0051 "|                                                                                      TOTAL SURTID.(LITROS):"
   #define STR0052 "|GRUPO                                        |VALOR              |GRUPO                                       |VALOR              |"
   #define STR0053 "|                                                                                      TOTAL GRUPOS:               R$"
   #define STR0054 "|PRODUCTO                              |CANT.   |VALOR            |PRODUCTO                              | CANT.  |VALOR           |"
   #define STR0055 "|                                                                                      TOTAL PRODUCTOS:            R$"
#ELSE
	#IFDEF ENGLISH
		#define STR0001 "Cashier Summary"
		#define STR0002 "Credits (Sales) "
		#define STR0003 "Debits (Part.Clos)"
		#define STR0004 "&Cashier Code   :"
		#define STR0005 "Initial Balance"
		#define STR0006 "Transaction Date :"
		#define STR0007 "Cash    "
		#define STR0008 "Cheques"
		#define STR0009 "Credit Cards      "
		#define STR0010 "Conventions"
		#define STR0011 "Voucher/Reven."
		#define STR0012 "Financed  "
		#define STR0013 "Others"
		#define STR0014 "Total Sales    "
		#define STR0015 "Vouchers/Expens"
		#define STR0016 "Devolutions"
		#define STR0017 "Total Debits    "
		#define STR0018 "END BALANCE:"
		#define STR0019 "&Print   "
		#define STR0020 "&Exit"
		#define STR0021 "This option will enable the printing of the Cashier Closing"
		#define STR0022 "on the current date."
		#define STR0023 "Cashier Closing    "
		#define STR0024 "Z.Form "
		#define STR0025 "Management   "
		#define STR0026 "| Company :"
		#define STR0027 "|                         CASHIER CLOSING                             |"
		#define STR0028 "| Code   :"
		#define STR0029 "| Transaction Date  :"
		#define STR0030 "| Initial Balance................................."
		#define STR0031 "| S A L E S......................................."
		#define STR0032 "| Devolution......................................"
		#define STR0033 "| P A R T I A L  C L O S I N G ..................."
		#define STR0034 "| Final Balance..................................."
		#define STR0035 "Position of General Cashier"
		#define STR0036 "Vouchers"
		#define STR0037 "Total Gener"
		#define STR0038 "Exit "
		#define STR0039 "Selecting Records........"
		#define STR0040 "Contra Vales"
		#define STR0041 "Cartao de Debito"
		#DEFINE STR0042 "Pagamentos"
		#DEFINE STR0043 "Transferˆncias"
		#DEFINE STR0044 "Recebimentos"
		#DEFINE STR0045 "Cr‚dito de Venda"
      #define STR0046 "SALDO FINAL"
      #define STR0047 "Valores"
      #define STR0048 "|                                  |-----------------ENCERRANTES EM LITROS---------------------|                                   |"
      #define STR0049 "|BOMBA/PRODUTO                     |ABERTURA           |FECHAMENTO         |VENDAS             |QUANTIDADE TOTAL VENDIDA(LITROS)   |"
      #define STR0050 "*** CANCELADO PELO OPERADOR ***"
      #define STR0051 "|                                                                                      TOTAL BOMBAS (LITROS):"
      #define STR0052 "|GRUPO                                        |VALOR              |GRUPO                                       |VALOR              |"
      #define STR0053 "|                                                                                      TOTAL GRUPOS :              R$"
      #define STR0054 "|PRODUTO                               |QUANT.  |VALOR            |PRODUTO                               |QUANT.  |VALOR           |"
      #define STR0055 "|                                                                                      TOTAL PRODUTOS:             R$"
	#ELSE
		#define STR0001 "Resumo de Caixa"
		#define STR0002 "Creditos(Vendas)"
		#define STR0003 "Debitos(Sangrias)"
		#define STR0004 "&Codigo do Caixa:"
		#define STR0005 "Saldo Inicial:"
		#define STR0006 "Data do Movimento:"
		#define STR0007 "Dinheiro"
		#define STR0008 "Cheques"
		#define STR0009 "Cartoes de Credito"
		#define STR0010 "Convenios"
		#define STR0011 "Vales/Receitas"
		#define STR0012 "Financiado"
		#define STR0013 "Outros"
		#define STR0014 "Total de Creditos"
		#define STR0015 "Vales/Despesas"
		#define STR0016 "Devolucoes"
		#define STR0017 "Total de Debitos"
		#define STR0018 "SALDO FINAL:"
		#define STR0019 "&Imprimir"
		#define STR0020 "&Sair"
		#define STR0021 "Esta opcao permite que seja impresso o Fechamento de Caixa"
		#define STR0022 "da data corrente."
		#define STR0023 "Fechamento de Caixa"
		#define STR0024 "Zebrado"
		#define STR0025 "Administracao"
		#define STR0026 "| Empresa :"
		#define STR0027 "|                                                        FECHAMENTO DO CAIXA                                                       |"
		#define STR0028 "| Codigo :"
		#define STR0029 "| Data do Movimento :"
		#define STR0030 "| Saldo Inicial .............................."
		#define STR0031 "| C R E D I T O S / V E N D A S..............."
		#define STR0032 "| Devolucao......................................."
		#define STR0033 "| D E B I T O S / S A N G R I A S............."
		#define STR0034 "| Saldo Final ................................"
		#define STR0035 "Posicao do Caixa Geral"
		#define STR0036 "Vales"
		#define STR0037 "Total Geral"
		#define STR0038 "Sair"
		#define STR0039 "Selecionando Registros..."
		#define STR0040 "Contra Vales"
		#define STR0041 "Cartoes de Debito Automatico"
		#DEFINE STR0042 "Pagamentos"
		#DEFINE STR0043 "Transferencias"
		#DEFINE STR0044 "Recebimentos"
		#DEFINE STR0045 "Credito de Venda"
      #define STR0046 "SALDO FINAL"
      #define STR0047 "Valores"
      #define STR0048 "|                                  |-----------------ENCERRANTES EM LITROS---------------------|                                   |"
      #define STR0049 "|BOMBA/PRODUTO                     |ABERTURA           |FECHAMENTO         |VENDAS             |QUANTIDADE TOTAL VENDIDA(LITROS)   |"
      #define STR0050 "*** CANCELADO PELO OPERADOR ***"
      #define STR0051 "|                                                                                      TOTAL BOMBAS (LITROS):"
      #define STR0052 "|GRUPO                                        |VALOR              |GRUPO                                       |VALOR              |"
      #define STR0053 "|                                                                                      TOTAL GRUPOS :              R$"
      #define STR0054 "|PRODUTO                               |QUANT.  |VALOR            |PRODUTO                               |QUANT.  |VALOR           |"
      #define STR0055 "|                                                                                      TOTAL PRODUTOS:             R$"
	#ENDIF
#ENDIF