#IFDEF SPANISH
   #define STR0001 "Serviços"
   #define STR0002 "Nome"
   #define STR0003 "Descrição"
   #define STR0004 "Status"
   #define STR0005 "Última utilização"
   #define STR0006 "Iniciar todos serviços"
   #define STR0007 "Iniciar serviço"
   #define STR0008 "Parar todos serviços"
   #define STR0009 "Parar serviço"
   #define STR0010 "Atualizar"
   #define STR0011 "Agendamento"
   #define STR0012 "Rotina"
   #define STR0013 "Aumentar número de threads"
   #define STR0014 "Diminuir número de threads"
   #define STR0015 "Diminuindo thread..."
   #define STR0016 "Adicionando thread..."
   #define STR0017 "Iniciando serviço..."
   #define STR0018 "Parando serviço..."
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Serviços"
      #define STR0002 "Nome"
      #define STR0003 "Descrição"
      #define STR0004 "Status"
      #define STR0005 "Última utilização"
      #define STR0006 "Iniciar todos serviços"
      #define STR0007 "Iniciar serviço"
      #define STR0008 "Parar todos serviços"
      #define STR0009 "Parar serviço"
      #define STR0010 "Atualizar"
      #define STR0011 "Agendamento"
      #define STR0012 "Rotina"
      #define STR0013 "Aumentar número de threads"
      #define STR0014 "Diminuir número de threads"
      #define STR0015 "Diminuindo thread..."
      #define STR0016 "Adicionando thread..."
      #define STR0017 "Iniciando serviço..."
      #define STR0018 "Parando serviço..."
   #ELSE
      #define STR0001 "Serviços"
      #define STR0002 "Nome"
      #define STR0003 "Descrição"
      #define STR0004 "Status"
      #define STR0005 "Última utilização"
      #define STR0006 "Iniciar todos serviços"
      #define STR0007 "Iniciar serviço"
      #define STR0008 "Parar todos serviços"
      #define STR0009 "Parar serviço"
      #define STR0010 "Atualizar"
      #define STR0011 "Agendamento"
      #define STR0012 "Rotina"
      #define STR0013 "Aumentar número de threads"
      #define STR0014 "Diminuir número de threads"
      #define STR0015 "Diminuindo thread..."
      #define STR0016 "Adicionando thread..."
      #define STR0017 "Iniciando serviço..."
      #define STR0018 "Parando serviço..."
   #ENDIF
#ENDIF
