#IFDEF SPANISH
   #define STR0001 "Pesquisar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Alt.Cadastro"
   #define STR0005 "Alt.Estrutura"
   #define STR0006 "Excluir"
   #define STR0007 "Gerenciador de Empreendimentos"
   #define STR0008 "Cadastro de Empreendimento"
   #define STR0009 "Incluir Estrutura"
   #define STR0010 "Incluir Unidade"
   #define STR0011 "Alterar"
   #define STR0012 "Informações"
   #define STR0013 "Inform."
   #define STR0014 "Estrutura"
   #define STR0015 "Estrut."
   #define STR0016 "Help"
   #define STR0017 "Confirma"
   #define STR0018 "Sair"
   #define STR0019 "Processando..."
   #define STR0020 "Opcao invalida."
   #define STR0021 "Novos niveis e tarefas so poderao ser adicionados a uma EDT"
   #define STR0022 "Não é possivel, acrescentar nova estrutura abaixo do nivel atual."
   #define STR0023 "Não é possivel, acrescentar unidades abaixo do nivel atual."
   #define STR0024 "Incluir Multiplas Unidades"
   #define STR0025 "Atenção"
   #define STR0026 "Existem unidades vendidas e ou reservadas, nao sera possivel excluir o emprendimento."
   #define STR0027 "Detalhe:"
   #define STR0028 "      Reservadas         : "
   #define STR0029 "      Contrato assinado  : "
   #define STR0030 "      Outros             : "
   #define STR0031 "OK"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alt.Cadastro"
      #define STR0005 "Alt.Estrutura"
      #define STR0006 "Excluir"
      #define STR0007 "Gerenciador de Empreendimentos"
      #define STR0008 "Cadastro de Empreendimento"
      #define STR0009 "Incluir Estrutura"
      #define STR0010 "Incluir Unidade"
      #define STR0011 "Alterar"
      #define STR0012 "Informações"
      #define STR0013 "Inform."
      #define STR0014 "Estrutura"
      #define STR0015 "Estrut."
      #define STR0016 "Help"
      #define STR0017 "Confirma"
      #define STR0018 "Sair"
      #define STR0019 "Processando..."
      #define STR0020 "Opcao invalida."
      #define STR0021 "Novos niveis e tarefas so poderao ser adicionados a uma EDT"
      #define STR0022 "Não é possivel, acrescentar nova estrutura abaixo do nivel atual."
      #define STR0023 "Não é possivel, acrescentar unidades abaixo do nivel atual."
      #define STR0024 "Incluir Multiplas Unidades"
      #define STR0025 "Atenção"
	   #define STR0026 "Existem unidades vendidas e ou reservadas, nao sera possivel excluir o emprendimento."
	   #define STR0027 "Detalhe:"
	   #define STR0028 "      Reservadas         : "
	   #define STR0029 "      Contrato assinado  : "
	   #define STR0030 "      Outros             : "
	   #define STR0031 "OK"
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alt.Cadastro"
      #define STR0005 "Alt.Estrutura"
      #define STR0006 "Excluir"
      #define STR0007 "Gerenciador de Empreendimentos"
      #define STR0008 "Cadastro de Empreendimento"
      #define STR0009 "Incluir Estrutura"
      #define STR0010 "Incluir Unidade"
      #define STR0011 "Alterar"
      #define STR0012 "Informações"
      #define STR0013 "Inform."
      #define STR0014 "Estrutura"
      #define STR0015 "Estrut."
      #define STR0016 "Help"
      #define STR0017 "Confirma"
      #define STR0018 "Sair"
      #define STR0019 "Processando..."
      #define STR0020 "Opcao invalida."
      #define STR0021 "Novos niveis e tarefas so poderao ser adicionados a uma EDT"
      #define STR0022 "Não é possivel, acrescentar nova estrutura abaixo do nivel atual."
      #define STR0023 "Não é possivel, acrescentar unidades abaixo do nivel atual."
      #define STR0024 "Incluir Multiplas Unidades"
	   #define STR0025 "Atenção"
	   #define STR0026 "Existem unidades vendidas e ou reservadas, nao sera possivel excluir o emprendimento."
	   #define STR0027 "Detalhe:"
	   #define STR0028 "      Reservadas         : "
	   #define STR0029 "      Contrato assinado  : "
	   #define STR0030 "      Outros             : "
	   #define STR0031 "OK"
   #ENDIF
#ENDIF
