#ifdef SPANISH
	#define STR0001 "Generacion archivo de DIRF"
	#define STR0002 "Este programa genera el archivo de DIRF"
	#define STR0003 "Confirma"
	#define STR0004 "Reescribe"
	#define STR0005 "Salir   "
	#define STR0006 "Generacion archivo de DIRF"
	#define STR0007 "Este programa genera el archivo de DIRF"
	#define STR0008 "Confirma"
	#define STR0009 "Reescribe"
	#define STR0010 "Salir   "
	#define STR0011 "Sucursal  : "
	#define STR0012 "Matricula : "
	#define STR0013 "Nombre    : "
	#define STR0014 "¿Confirma configuracion de los parametros?"
	#define STR0015 "Atencion"
	#define STR0016 "Conserva"
	#define STR0017 "Limpia"
	#define STR0018 "¿Cuanto al archivo de DIRF, ya tiene datos? "
	#define STR0019 "Ya existen datos en el Archivo de la DIRF. ¿Limpia el Archivo?"
	#define STR0020 "Tablas desactualizadas. Ejecute el actualizador"
	#define STR0021 "Las tablas SRL y SR4 se limpiaran para que a partir de ahora pueda almacenarse el historial."
	#define STR0022 "Registro con concepto en blanco en el acumulado.    Sucursal/Matricula  Competencia            Valor "
	#define STR0023 "Registro con competencia en blanco no acumulado.   Sucursal/Matricula  Concepto             Valor"
	#define STR0024 "Registro con fecha de pago en blanco no acumulado."
	#define STR0025 "Concepto duplicado en los acumulados.    Sucursal/Matricula   Concepto   Competencia             Valor"
	#define STR0026 "Empleado sin CPF registrado."
	#define STR0027 "¡Archivo generado con exito!"
	#define STR0028 "No se encontro ninguna inconsistencia durante la generacion."
	#define STR0029 "Informaciones para generar la DIRF."
	#define STR0030 "Para obtener informaciones detalladas de como proceder para configurar la DIRF, consulte"
	#define STR0031 "el Boletin Tecnico que se encuentra en el Portal del Cliente para download."
	#define STR0032 "Log de ocurrências de la DIRF"
	#define STR0033 "Concepto consta en los acumulados, pero no consta en el archivo de conceptos.   Concepto    Competencia             Valor"
	#define STR0034 "Concepto con incidencia para IR, pero sin configuracion para DIRF."
	#define STR0035 "Empleado"
	#define STR0036 "Inicio del procesamiento"
	#define STR0037 "Final del procesamiento"
	#define STR0038 "Prorrateo de Asistencia Medica"
	#define STR0039 "No se encontro prorrateo Asist. Medica p/ este empleado"
	#define STR0040 "No se encontro archivo de prorrateo de Asist. Medica -> "
	#define STR0041 ". Efectue el prorrateo."
	#define STR0042 "No fue posible abrir el archivo de prorrateo -> "
	#define STR0043 ". Verifique el prorrateo de asist. medica."
	#define STR0044 "Prest.Serv.Transp.Pasaj."
	#define STR0045 "Prest.Serv.Transp.Carga"
	#define STR0046 "Ejecute la opcion de compatibilizador referente a los Ajustes para Dirf 2012 - Fase3. Para mayores informaciones, verifique el respectivo Boletin Tecnico."
	#define STR0047 "Ok"
	#define STR0048 "Existem informações do rateio do plano de assistência médica e odontológica."
	#define STR0049 "Deseja efetuar a importação dos dados para o histórico?"
	#define STR0050 "Log da Importação do Rateio dos Planos de Saude das Empresas para o Histórico"
	#define STR0051 "Registros processados da Importação do Rateio dos Planos de Saude das Empresas para o Histórico"
	#define STR0052 "- Registro lido (Fil: "
	#define STR0053 " Matr: "
	#define STR0054 " Verba: "
	#define STR0055 " Data Pagto: "
	#define STR0056 " Valor: R$ "
	#define STR0057 " Filial: "
	#define STR0058 " Matrícula: "
	#define STR0059 " não encontrada no Cad. de Funcionário."
	#define STR0060 ". Dependente: "
	#define STR0061 " não encontrado."
	#define STR0062 " Origem: "
	#define STR0063 ". Origem inválida. Deve ser dos tipos 1 (Titular), 2 (Dependente) ou 3 (Agregado)."
	#define STR0064 " Tp Assist.: "
	#define STR0065 ". Tipo de assistência inválida. Deve ser dos tipos 1 (Plano), 2 (Co-participação)"
	#define STR0066 "     ou 3 (Reembolso)."
	#define STR0067 " Tp Fornecedor: "
	#define STR0068 ". Tipo do fornecedor inválido. Deve ser dos tipos 1 (Médica) ou 2 (Odonto.)."
	#define STR0069 " Tp Plano: "
	#define STR0070 ". Tipo do plano inválido. Deve ser dos tipos 1 (Fx. Salarial), 2 (Fx. Etária), 3 (Vl. Fixo),"
	#define STR0071 "     ou 4 (% S/ Salário)."
	#define STR0072 " Verba: "
	#define STR0073 " não encontrada."
	#define STR0074 " Código do Fornecedor não encontrado. Tp Fornecedor: "
	#define STR0075 " Fornecedor: "
	#define STR0076 " Código do Plano não encontrado. Tp Fornecedor: "
	#define STR0077 " Fornecedor: "
	#define STR0078 " Tp. Plano: "
	#define STR0079 " Cod. Plano: "
	#define STR0080 "  -> Registro gravado (Fil: "
	#define STR0081 "- Total de registros lidos - Total : "
	#define STR0082 "- Total de registros gravados - Total : "
	#define STR0083 "- Total de registros gravados - Plano de Saúde : "
	#define STR0084 "- Total de registros gravados - Co-Part./Reembolso de Plano de Saúde : "
	#define STR0085 "  -> Não Gravado."
	#define STR0086 " Campo Código do Dep/Agr. preenchido porém campo Origem igual a 1 (titular)."
	#define STR0087 "     Campo Origem dever ser preenchido com 2 (Dependente) ou 3 (Agregado)."
	#define STR0088 " Registro se origino del calculo del plan de salud."
	#define STR0089 " 161-Ajuste de campos de las tablas RHP y RHS."
	#define STR0090 "NVLLIMDIRF Límite anual Decl. IRPF informado con R$ "
	#define STR0091 "NVLLIMOUT Límite anual Otras categorías informado con R$ "
	#define STR0092 "Estos 2 Mnemónicos definen el valor mínimo de las remuneraciones que se considerarán para la generación del archivo de la DIRF."
	#define STR0093 "El primero para beneficiarios de empleo remunerado y el segundo para remuneraciones sin vínculo laboral."
	#define STR0094 "¿Desea continuar?"
	#define STR0095 "Mnemónicos:"
	#define STR0096 "Si desea modificar los valores, haga clic en No, y a continuación, vaya a: "
	#define STR0097 "Actualizaciones > Definiciones de cálculo > Mnemónicos"
	#define STR0098 "P_VLIMDIRF Límite anual Decl. IRPF informado con R$ "
	#define STR0099 "P_VLIMOUT Límite anual Otras categorías informado con R$ "
	#define STR0100 "Ejecute la opción del compatibilizador 117 referente a la DIRF - Creación de índice para la tabla RCS. Si ya hizo la ejecución, por favor ejecútela nuevamente."
#else
	#ifdef ENGLISH
		#define STR0001 "DIRF File Generation"
		#define STR0002 "This routine will generate the DIRF file"
		#define STR0003 "Confirm"
		#define STR0004 "Retype"
		#define STR0005 "Quit"
		#define STR0006 "DIRF File Generation"
		#define STR0007 "This routine will generate the DIRF file"
		#define STR0008 "Confirm"
		#define STR0009 "Retype"
		#define STR0010 "Quit"
		#define STR0011 "Branch    : "
		#define STR0012 "Registrat.: "
		#define STR0013 "Name      : "
		#define STR0014 "Confirm parameters configuration ?"
		#define STR0015 "Attention"
		#define STR0016 "Keep    "
		#define STR0017 "Clear  "
		#define STR0018 "About DIRF file, is there any data?"
		#define STR0019 "There is data in DIRF file. Clear the File?"
		#define STR0020 "Table outdated. Run updater."
		#define STR0021 "SRL and SR4 tables will be cleaned up to store history since now."
		#define STR0022 "Entry with fund in blank in accrual.           Branch/Registration   Competence          Value "
		#define STR0023 "Entry with competence in blank in accrual.          Branch/Registration  Fund            Value"
		#define STR0024 "Entry with payment date in blank in accrual."
		#define STR0025 "Fund duplicated in accrual.        Branch/Registration   Fund   Competence             Value"
		#define STR0026 "Employee without CPF registered"
		#define STR0027 "File successfully generated!"
		#define STR0028 "No inconsistency found during generation."
		#define STR0029 "Information to generate DIRF."
		#define STR0030 "For further information regarding how to setup DIRF, query"
		#define STR0031 "the technical bulletin is in Customer Portal for download."
		#define STR0032 "DIRF Occurrence Log"
		#define STR0033 "Fund registered in accrual, but it is not registered in fund file.   Fund     Competence             Value"
		#define STR0034 "Fund with IR incidence but with no DIRF configuration."
		#define STR0035 "Employee"
		#define STR0036 "Beginning processing"
		#define STR0037 "Conclusion of processing"
		#define STR0038 "Health Care Apportionment"
		#define STR0039 "Health Care Apportionment not found for this Employee"
		#define STR0040 "Health Care Apportionment File not found -> "
		#define STR0041 ". Make the Apportionment."
		#define STR0042 "Apportionment file could not be opened -> "
		#define STR0043 ". Check the health care apportionment."
		#define STR0044 "PASSENG. TRANSP. SERV. PROV."
		#define STR0045 "CARGO TRANSP. SERV. PROV."
		#define STR0046 "Run the compatibility program option regarding Dirf 2012 - Phase 3 Adjustments. For further information, check the respective Technical Newsletter."
		#define STR0047 "Ok"
		#define STR0048 "There are health and dental plan proration data."
		#define STR0049 "Do you wish to import data into history?"
		#define STR0050 "Log of Corporate Health Plan Proration Imports to History"
		#define STR0051 "Processed Records of Corporate Health Plan Proration Imports to History"
		#define STR0052 "- Record read (Fil: "
		#define STR0053 " Reg: "
		#define STR0054 " Budget: "
		#define STR0055 " Payment Date "
		#define STR0056 " Value: R$ "
		#define STR0057 " Branch: "
		#define STR0058 " Registration: "
		#define STR0059 " not found in Employee Register."
		#define STR0060 ". Dependant: "
		#define STR0061 " not found."
		#define STR0062 " Origin: "
		#define STR0063 ". Origin not valid. It must be of types 1 (Title holder), 2 (Dependant) or 3 (Aggregate)."
		#define STR0064 " Assist. Tp: "
		#define STR0065 ". Assistance type not valid. It must be of types 1 (Plan), 2 (Co-participation)"
		#define STR0066 "     or 3 (Reimbursement)"
		#define STR0067 " Supplier Tp: "
		#define STR0068 ". Supplier type not valid. It must be of types 1 (Medical), 2 (Dental)"
		#define STR0069 " Plan Tp: "
		#define STR0070 ". Plan type not valid. Must be type 1 (Salary Rg), 2 (Age Rg), 3 (Ret. Fee),"
		#define STR0071 "     or 4 (% No Salary)."
		#define STR0072 " Budget: "
		#define STR0073 " not found."
		#define STR0074 " Supplier Code not found. Supplier Tp: "
		#define STR0075 " Supplier: "
		#define STR0076 " Plan Code not found. Supplier Tp: "
		#define STR0077 " Supplier: "
		#define STR0078 " Tp. Plan: "
		#define STR0079 " Plan Code: "
		#define STR0080 "  -> Record saved (Fil: "
		#define STR0081 "- Total records read - Total : "
		#define STR0082 "- Total records saved - Total : "
		#define STR0083 "- Total records saved - Health Plan : "
		#define STR0084 "- Total records saved - Health Plan Co-Part/Reimbursement : "
		#define STR0085 "  -> Not Recorded."
		#define STR0086 " Field Dep/Agr Code filled out but field Source equal to 1 (holder)."
		#define STR0087 "     Fill out Source Field with 2 (dependent) or 3 (Household Member)."
		#define STR0088 " Record from health plan calculation. "
		#define STR0089 " 161-RHP and RHS tables adjustment"
		#define STR0090 "NVLLIMDIRF Yearly Limit Statmt IRPF filled out with BRL "
		#define STR0091 "NVLLIMDIRF Yearly Limit Other Categories filled out with BRL "
		#define STR0092 "These 2 Mnemonics define the minimum income value taken into account to create the DIRF file."
		#define STR0093 "The first for salaried work beneficiaries and the second for incomes with no employment relationships."
		#define STR0094 "Continue?"
		#define STR0095 "Mnemonics:"
		#define STR0096 "If you wish to change the values, click No, then go to: "
		#define STR0097 "Updates > Calculation Definitions > Mnemonics"
		#define STR0098 "NVLLIMDIRF Yearly Limit Decl.  "
		#define STR0099 "P_VLIMOUT Yearly Limit Other Categories filled out with BRL "
		#define STR0100 "Execute the compatibility program 117 option regarding DIRF - RCS table index creation. If already executed, please do so again."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "Criaçäo do Ficheiro da D. I. R. F.", "Geraçäo do Arquivo da D. I. R. F." )
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Este Programa Cria O Ficheiro Da  DIRF ", "Este programa gera o arquivo da D.I.R.F." )
		#define STR0003 "Confirma"
		#define STR0004 "Redigita"
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Abandonar", "Abandona" )
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Criaçäo do ficheiro da D.I.R.F.", "Geraçäo do Arquivo da D.I.R.F." )
		#define STR0007 If( cPaisLoc $ "ANG|PTG", "Este Programa Cria O Ficheiro Da  DIRF ", "Este programa gera o arquivo da D.I.R.F." )
		#define STR0008 "Confirma"
		#define STR0009 "Redigita"
		#define STR0010 If( cPaisLoc $ "ANG|PTG", "Abandonar", "Abandona" )
		#define STR0011 "Filial    : "
		#define STR0012 If( cPaisLoc $ "ANG|PTG", "Registo : ", "Matricula : " )
		#define STR0013 "Nome      : "
		#define STR0014 If( cPaisLoc $ "ANG|PTG", "Confirma configuração dos parâmetros?", "Confirma configuraçäo dos parâmetros?" )
		#define STR0015 If( cPaisLoc $ "ANG|PTG", "Atenção", "Atençäo" )
		#define STR0016 "Conserva"
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Limpo", "Limpa" )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", "Quanto ao ficheiro da  DIRF  , já contem dados? ", "Quanto ao Arquivo da DIRF, ja contem dados? " )
		#define STR0019 If( cPaisLoc $ "ANG|PTG", "Já existem dados no ficheiro da  DIRF  . limpar o ficheiro ?", "Ja existem dados no Arquivo da DIRF. Limpa o Arquivo ?" )
		#define STR0020 If( cPaisLoc $ "ANG|PTG", "Tabelas desactualizadas. executar o actualizador", "Tabelas desatualizadas. Execute o atualizador" )
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "As tabelas srl e sr4 serão limpas para que a partir de agora o histórico possa ser guardado.", "As tabelas SRL e SR4 serao limpas para que a partir de agora o historico possa ser armazenado." )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Movimento com verba em branco no acumulado.    filial/registo  competência            valor ", "Lancamento com verba em branco no acumulado.    Filial/Matricula  Competencia            Valor " )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "Movimento Com Competência Em Branco No Acumulado.   Filial/registo  Verba             Valor", "Lancamento com competencia em branco no acumulado.   Filial/Matricula  Verba             Valor" )
		#define STR0024 If( cPaisLoc $ "ANG|PTG", "Movimento com data de pagamento em branco no acumulado.", "Lancamento com data de pagamento em branco no acumulado." )
		#define STR0025 If( cPaisLoc $ "ANG|PTG", "Verba Duplicada Nos Acumulados.    Filial/registo   Verba   Competência             Valor", "Verba duplicada nos acumulados.    Filial/Matricula   Verba   Competencia             Valor" )
		#define STR0026 If( cPaisLoc $ "ANG|PTG", "Funcionário sem número de contribuinte registado.", "Funcionário sem CPF cadastrado." )
		#define STR0027 If( cPaisLoc $ "ANG|PTG", "Ficheiro criado com sucesso!", "Arquivo gerado com sucesso!" )
		#define STR0028 If( cPaisLoc $ "ANG|PTG", "Não foi encontrada nenhuma inconsistência durante a criação.", "Não foi encontrada nenhuma inconsistência durante a geração." )
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Informações Para Criar A Dirf.", "Informações para gerar a DIRF." )
		#define STR0030 If( cPaisLoc $ "ANG|PTG", "Para obter informações detalhadas de como proceder para configurar a dirf, consulte", "Para obter informações detalhadas de como proceder para configurar a DIRF, consulte" )
		#define STR0031 "o Boletim Técnico que se encontra no Portal do Cliente para download."
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Diário De Ocorrências Da Dirf", "Log de ocorrências da DIRF" )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "Verba Consta Nos Acumulados, Mas Não Consta No Registo De Verbas.   Verba    Competência             Valor", "Verba consta nos acumulados, mas nao consta no cadastro de verbas.   Verba    Competencia             Valor" )
		#define STR0034 If( cPaisLoc $ "ANG|PTG", "Verba Com Incidência Para Ir, Mas Sem Configuração Para Dirf.", "Verba com incidência para IR, mas sem configuração para DIRF." )
		#define STR0035 If( cPaisLoc $ "ANG|PTG", "Empregado", "Funcionário" )
		#define STR0036 "Início do processamento"
		#define STR0037 If( cPaisLoc $ "ANG|PTG", "Fim do processamento", "Termino do processamento" )
		#define STR0038 "Rateio de Assistência Médica"
		#define STR0039 If( cPaisLoc $ "ANG|PTG", "Rateio Assist. Médica não encontrado p/ este colaborador", "Rateio Assist. Médica não encontrado p/ este Funcionario" )
		#define STR0040 If( cPaisLoc $ "ANG|PTG", "Ficheiro de rateio de Assist. Médica não encontrado -> ", "Arquivo de rateio de Assist. Médica não encontrado -> " )
		#define STR0041 If( cPaisLoc $ "ANG|PTG", ". Efectue o rateio.", ". Efetue o Rateio." )
		#define STR0042 If( cPaisLoc $ "ANG|PTG", "Não foi possível abrir o ficheiro de rateio -> ", "Não foi possível abrir o arquivo de rateio -> " )
		#define STR0043 ". Verifique o rateio de assist. médica."
		#define STR0044 "PREST.SERV.TRANSP.PASSAG."
		#define STR0045 "PREST.SERV.TRANSP.CARGA"
		#define STR0046 If( cPaisLoc $ "ANG|PTG", "Execute a opção do compatibilizador referente aos Ajustes para Dirf 2012 - Fase3. Para mais informações, verifique o respectivo Boletim Técnico.", "Execute a opção do compatibilizador referente aos Ajustes para Dirf 2012 - Fase3. Para maiores informações, verifique o respectivo Boletim Técnico." )
		#define STR0047 "Ok"
		#define STR0048 "Existem informações do rateio do plano de assistência médica e odontológica."
		#define STR0049 If( cPaisLoc $ "ANG|PTG", "Deseja efectuar a importação dos dados para o histórico?", "Deseja efetuar a importação dos dados para o histórico?" )
		#define STR0050 If( cPaisLoc $ "ANG|PTG", "Log da importação do rateio dos Planos de Saúde das empresas para o histórico", "Log da Importação do Rateio dos Planos de Saude das Empresas para o Histórico" )
		#define STR0051 If( cPaisLoc $ "ANG|PTG", "Registos processados da importação do rateio dos Planos de Saúde das empresas para o histórico", "Registros processados da Importação do Rateio dos Planos de Saude das Empresas para o Histórico" )
		#define STR0052 If( cPaisLoc $ "ANG|PTG", "- Registo lido (Fil: ", "- Registro lido (Fil: " )
		#define STR0053 " Matr: "
		#define STR0054 " Verba: "
		#define STR0055 If( cPaisLoc $ "ANG|PTG", " Data Pgt.: ", " Data Pagto: " )
		#define STR0056 " Valor: R$ "
		#define STR0057 " Filial: "
		#define STR0058 " Matrícula: "
		#define STR0059 If( cPaisLoc $ "ANG|PTG", " não encontrada no Reg. de Colaborador.", " não encontrada no Cad. de Funcionário." )
		#define STR0060 ". Dependente: "
		#define STR0061 " não encontrado."
		#define STR0062 " Origem: "
		#define STR0063 ". Origem inválida. Deve ser dos tipos 1 (Titular), 2 (Dependente) ou 3 (Agregado)."
		#define STR0064 If( cPaisLoc $ "ANG|PTG", " Tp.Assist.: ", " Tp Assist.: " )
		#define STR0065 ". Tipo de assistência inválida. Deve ser dos tipos 1 (Plano), 2 (Co-participação)"
		#define STR0066 "     ou 3 (Reembolso)."
		#define STR0067 If( cPaisLoc $ "ANG|PTG", " Tp.Fornecedor: ", " Tp Fornecedor: " )
		#define STR0068 ". Tipo do fornecedor inválido. Deve ser dos tipos 1 (Médica) ou 2 (Odonto.)."
		#define STR0069 If( cPaisLoc $ "ANG|PTG", " Tp.Plano: ", " Tp Plano: " )
		#define STR0070 If( cPaisLoc $ "ANG|PTG", ". Tipo do plano inválido. Deve ser dos tipos 1 (Fx. Salarial), 2 (Fx. Etária), 3 (Vlr. Fixo),", ". Tipo do plano inválido. Deve ser dos tipos 1 (Fx. Salarial), 2 (Fx. Etária), 3 (Vl. Fixo)," )
		#define STR0071 If( cPaisLoc $ "ANG|PTG", "     ou 4 (% S/ Remuneração).", "     ou 4 (% S/ Salário)." )
		#define STR0072 " Verba: "
		#define STR0073 " não encontrada."
		#define STR0074 If( cPaisLoc $ "ANG|PTG", " Código do fornecedor não encontrado. Tp.Fornecedor: ", " Código do Fornecedor não encontrado. Tp Fornecedor: " )
		#define STR0075 " Fornecedor: "
		#define STR0076 If( cPaisLoc $ "ANG|PTG", " Código do plano não encontrado. Tp.Fornecedor: ", " Código do Plano não encontrado. Tp Fornecedor: " )
		#define STR0077 " Fornecedor: "
		#define STR0078 " Tp. Plano: "
		#define STR0079 If( cPaisLoc $ "ANG|PTG", " Cód. Plano: ", " Cod. Plano: " )
		#define STR0080 If( cPaisLoc $ "ANG|PTG", "  -> Registo gravado (Fil: ", "  -> Registro gravado (Fil: " )
		#define STR0081 If( cPaisLoc $ "ANG|PTG", "- Total de registos lidos - Total : ", "- Total de registros lidos - Total : " )
		#define STR0082 If( cPaisLoc $ "ANG|PTG", "- Total de registos gravados - Total : ", "- Total de registros gravados - Total : " )
		#define STR0083 If( cPaisLoc $ "ANG|PTG", "- Total de registos gravados - Plano de Saúde : ", "- Total de registros gravados - Plano de Saúde : " )
		#define STR0084 If( cPaisLoc $ "ANG|PTG", "- Total de registos gravados - Co-Part./Reembolso de Plano de Saúde : ", "- Total de registros gravados - Co-Part./Reembolso de Plano de Saúde : " )
		#define STR0085 If( cPaisLoc $ "ANG|PTG", "  -> Não gravado.", "  -> Não Gravado." )
		#define STR0086 " Campo Código do Dep/Agr. preenchido porém campo Origem igual a 1 (titular)."
		#define STR0087 "     Campo Origem dever ser preenchido com 2 (Dependente) ou 3 (Agregado)."
		#define STR0088 If( cPaisLoc $ "ANG|PTG", " Registo foi originado do cálculo do plano de saúde.", " Registro foi originado do cálculo do plano de saúde." )
		#define STR0089 " 161-Ajuste de campos das tabelas RHP e RHS"
		#define STR0090 "NVLLIMDIRF Limite Anual Decl. IRPF preenchido com R$ "
		#define STR0091 "NVLLIMOUT Limite Anual Outras Categorias preenchido com R$ "
		#define STR0092 "Estes 2 Mnemônicos definem o valor mínimo dos rendimentos, a ser considerado para a geração do arquivo da DIRF."
		#define STR0093 "O primeiro para beneficiários de trabalho assalariado e o segundo para rendimentos sem vínculo empregatício."
		#define STR0094 "Deseja continuar?"
		#define STR0095 "Mnemônicos:"
		#define STR0096 "Caso queira modificar os valores, clique em Não, e em seguida vá em: "
		#define STR0097 "Atualizações > Definições de Cálculo > Mnemônicos"
		#define STR0098 "P_VLIMDIRF Limite Anual Decl. IRPF preenchido com R$ "
		#define STR0099 "P_VLIMOUT Limite Anual Outras Categorias preenchido com R$ "
		#define STR0100 "Execute a opção do compatibilizador 117 referente a DIRF - Criacao de indice para a tabela RCS. Caso já tenha executado, favor executá-lo novamente."
	#endif
#endif
