#ifdef SPANISH
	#define STR0001 "Relatório do resumo de imposto de renda retido na fonte"
	#define STR0002 "Resumo do imposto de renda retido na fonte dos funcionários, conforme período selecionado."
	#define STR0003 "Matrícula"
	#define STR0004 "Nome + Matrícula"
	#define STR0005 "Cod. da Filial"
	#define STR0006 "Nome da Filial"
	#define STR0007 "CNPJ"
	#define STR0008 "Nome Funcionário"
	#define STR0009 "Endereço"
	#define STR0010 "Município"
	#define STR0011 "Estado"
	#define STR0012 "CEP"
	#define STR0013 "Data Nasc."
	#define STR0014 "RG"
	#define STR0015 "Tot. imp. sobre renda"
	#define STR0016 "Tot. pagtos recebidos"
	#define STR0017 "Tot. benefícios extras"
	#define STR0018 "Tot. previdência social"
#else
	#ifdef ENGLISH
		#define STR0001 "Relatório do resumo de imposto de renda retido na fonte"
		#define STR0002 "Resumo do imposto de renda retido na fonte dos funcionários, conforme período selecionado."
		#define STR0003 "Matrícula"
		#define STR0004 "Nome + Matrícula"
		#define STR0005 "Cod. da Filial"
		#define STR0006 "Nome da Filial"
		#define STR0007 "CNPJ"
		#define STR0008 "Nome Funcionário"
		#define STR0009 "Endereço"
		#define STR0010 "Município"
		#define STR0011 "Estado"
		#define STR0012 "CEP"
		#define STR0013 "Data Nasc."
		#define STR0014 "RG"
		#define STR0015 "Tot. imp. sobre renda"
		#define STR0016 "Tot. pagtos recebidos"
		#define STR0017 "Tot. benefícios extras"
		#define STR0018 "Tot. previdência social"
	#else
		Static STR0001 := "Relatório do resumo de imposto de renda retido na fonte"
		Static STR0002 := "Resumo do imposto de renda retido na fonte dos funcionários, conforme período selecionado."
		Static STR0003 := "Matrícula"
		Static STR0004 := "Nome + Matrícula"
		Static STR0005 := "Cod. da Filial"
		Static STR0006 := "Nome da Filial"
		Static STR0007 := "CNPJ"
		Static STR0008 := "Nome Funcionário"
		Static STR0009 := "Endereço"
		Static STR0010 := "Município"
		Static STR0011 := "Estado"
		Static STR0012 := "CEP"
		Static STR0013 := "Data Nasc."
		Static STR0014 := "RG"
		Static STR0015 := "Tot. imp. sobre renda"
		Static STR0016 := "Tot. pagtos recebidos"
		Static STR0017 := "Tot. benefícios extras"
		Static STR0018 := "Tot. previdência social"
	#endif
#endif

#ifndef SPANISH
#ifndef ENGLISH
	STATIC uInit := __InitFun()

	Static Function __InitFun()
	uInit := Nil
	If Type('cPaisLoc') == 'C'

		If cPaisLoc == "ANG"
			STR0001 := "Relatório do resumo de imposto de renda retido na fonte"
			STR0002 := "Resumo do imposto de renda retido na fonte dos funcionários, conforme período selecionado."
			STR0003 := "Matrícula"
			STR0004 := "Nome + Matrícula"
			STR0005 := "Cod. da Filial"
			STR0006 := "Nome da Filial"
			STR0007 := "CNPJ"
			STR0008 := "Nome Funcionário"
			STR0009 := "Endereço"
			STR0010 := "Município"
			STR0011 := "Estado"
			STR0012 := "CEP"
			STR0013 := "Data Nasc."
			STR0014 := "RG"
			STR0015 := "Tot. imp. sobre renda"
			STR0016 := "Tot. pagtos recebidos"
			STR0017 := "Tot. benefícios extras"
			STR0018 := "Tot. previdência social"
		ElseIf cPaisLoc == "PTG"
			STR0001 := "Relatório do resumo de imposto de renda retido na fonte"
			STR0002 := "Resumo do imposto de renda retido na fonte dos funcionários, conforme período selecionado."
			STR0003 := "Matrícula"
			STR0004 := "Nome + Matrícula"
			STR0005 := "Cod. da Filial"
			STR0006 := "Nome da Filial"
			STR0007 := "CNPJ"
			STR0008 := "Nome Funcionário"
			STR0009 := "Endereço"
			STR0010 := "Município"
			STR0011 := "Estado"
			STR0012 := "CEP"
			STR0013 := "Data Nasc."
			STR0014 := "RG"
			STR0015 := "Tot. imp. sobre renda"
			STR0016 := "Tot. pagtos recebidos"
			STR0017 := "Tot. benefícios extras"
			STR0018 := "Tot. previdência social"
		EndIf
		EndIf
	Return Nil
#ENDIF
#ENDIF
