#ifdef SPANISH
	#define STR0001 "Agencias"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Borrar"
	#define STR0006 "Imprimir"
	#define STR0007 "Copiar"
	#define STR0008 "No se puede borrar agencia que ya genero calculo de comision."
	#define STR0009 "No permite borrar agencias que tienen items de comisiones registradas."
	#define STR0010 "Não permite excluir Agências que possuem Saldo."
#else
	#ifdef ENGLISH
		#define STR0001 "Agencies"
		#define STR0002 "View"
		#define STR0003 "Add"
		#define STR0004 "Change"
		#define STR0005 "Delete"
		#define STR0006 "Print"
		#define STR0007 "Copy"
		#define STR0008 "It is not possible to delete Branch with generated commission calculation."
		#define STR0009 "It is not allowed to delete Branches that have registered Commission Items."
		#define STR0010 "You cannot delete Branches with Balance."
	#else
		#define STR0001 "Agências"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Excluir"
		#define STR0006 "Imprimir"
		#define STR0007 "Copiar"
		#define STR0008 "Não é possível excluir Agência que já foi gerado cálculo de comissão."
		#define STR0009 "Não permite excluir Agências que possuem Ítens de Comissões cadastradas."
		#define STR0010 "Não permite excluir Agências que possuem Saldo."
	#endif
#endif
