#ifdef SPANISH
	#define STR0001 "Confirmacion de devoluciones"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Confirmar"
	#define STR0005 "Leyenda"
	#define STR0006 "Atencion"
	#define STR0007 "La solicitud seleccionada se atendio totalmente"
	#define STR0008 "Atencion anulada"
	#define STR0009 "Cantidad invalida"
	#define STR0010 "Producto no encontrado en la solicitud"
	#define STR0011 "Cantidad informada es mayor que la cantidad por devolverse"
	#define STR0012 "No confirmada"
	#define STR0013 "Confirmacion parcial"
	#define STR0014 "Confirmacion total"
	#define STR0015 "Reimpresion"
	#define STR0016 "Confirmacion de Devolucion"
	#define STR0017 "La atencion ya está en alta"
	#define STR0018 "La fecha de devolucion no puede ser anterior a la fecha de atencion"
	#define STR0019 "Inconsistencia de fecha/ hora"
	#define STR0020 "La fecha de la devolucion no puede ser posterior a la fecha corriente"
	#define STR0021 "La fecha de devolucion es menor o igual al ultimo cierre de stock, no se podra hacer el asiento."
	#define STR0022 "Fecha Cierre"
	#define STR0023 "La fecha de movimiento no puede ser posterior a la fecha de alta"
	#define STR0024 "No hay guia pendiente para esta atencion"
	#define STR0025 "Inconsistencia del estatus de la guia"
#else
	#ifdef ENGLISH
		#define STR0001 "Confirmation of returns"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Confirm  "
		#define STR0005 "Caption"
		#define STR0006 "Note"
		#define STR0007 "The request selected was totally attended to"
		#define STR0008 "Attendance was already canceled"
		#define STR0009 "Quantity invalid"
		#define STR0010 "Product not found in the request"
		#define STR0011 "Quantity entered is more than the quantity to be returned"
		#define STR0012 "Not confirmed"
		#define STR0013 "Partial confirmation"
		#define STR0014 "Total confirmation"
		#define STR0015 "Re-print "
		#define STR0016 "Confirmation of Return"
		#define STR0017 "O atendimento já está em alta"
		#define STR0018 "A data da devolução não pode ser anterior a data do atendimento"
		#define STR0019 "Inconsistência de data/ hora"
		#define STR0020 "A data da devolução não pode ser posterior a data corrente"
		#define STR0021 "A Data da devolução é menor ou igual ao último fechamento de estoque, não será possível efetuar o lançamento."
		#define STR0022 "Data Fecham."
		#define STR0023 "A data da movimentação não pode ser posterior a data da alta"
		#define STR0024 "Não existe nenhuma guia em aberto para este atendimento"
		#define STR0025 "Inconsistência do status da guia"
	#else
		#define STR0001 "Confirmação de devoluções"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Confirmar"
		#define STR0005 "Legenda"
		#define STR0006 "Atenção"
		#define STR0007 "A solicitação selecionada foi totalmente atendida"
		#define STR0008 "Atendimento já foi cancelado"
		#define STR0009 "Quantidade inválida"
		#define STR0010 "Produto não encontrado na solicitação"
		#define STR0011 "Quantida informada é maior que a quantidade a ser devolvida"
		#define STR0012 "Não confirmada"
		#define STR0013 "Confirmação parcial"
		#define STR0014 "Confirmação total"
		#define STR0015 "Reimpressão"
		#define STR0016 "Confirmação da Devolução"
		#define STR0017 "O atendimento já está em alta"
		#define STR0018 "A data da devolução não pode ser anterior a data do atendimento"
		#define STR0019 "Inconsistência de data/ hora"
		#define STR0020 "A data da devolução não pode ser posterior a data corrente"
		#define STR0021 "A Data da devolução é menor ou igual ao último fechamento de estoque, não será possível efetuar o lançamento."
		#define STR0022 "Data Fecham."
		#define STR0023 "A data da movimentação não pode ser posterior a data da alta"
		#define STR0024 "Não existe nenhuma guia em aberto para este atendimento"
		#define STR0025 "Inconsistência do status da guia"
	#endif
#endif
