#ifdef SPANISH
	#define STR0001 "Especialidad medica"
	#define STR0002 "Buscar"
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Modificar"
	#define STR0006 "Borrar"
	#define STR0007 "Especialidad"
	#define STR0008 "Descripcion"
	#define STR0009 "Especialidad ya registrada. Por favor, utilice otro codigo"
	#define STR0010 "Existen profesionales registrados con esta especialidad. Borrado no permitido"
	#define STR0011 "Existen procedimientos registrados con esta especialidad. Borrado no permitido"
	#define STR0012 "Atencion"
#else
	#ifdef ENGLISH
		#define STR0001 "Medical Specialities"
		#define STR0002 "Search"
		#define STR0003 "View"
		#define STR0004 "Insert"
		#define STR0005 "Edit"
		#define STR0006 "Delete"
		#define STR0007 "Speciality"
		#define STR0008 "Description"
		#define STR0009 "This Medical Speciality exists. Please register another Speciality!"
		#define STR0010 "There are Professional with this Speciality on the Professionals File (GAP). Impossible to Delete it!"
		#define STR0011 "It is not possible to delete Medical Speciality! Call Microsiga Support!"
		#define STR0012 "Attention"
	#else
		#define STR0001 "Especialidade médica"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 "Especialidade"
		#define STR0008 "Descrição"
		#define STR0009 "Especialidade já cadastrada. Por favor, utilize outro código"
		#define STR0010 "Existem profissionais cadastrados com esta especialidade. Exclusão não permitida"
		#define STR0011 "Existem procedimentos cadastrados com esta especialidade. Exclusão não permitida"
		#define STR0012 "Atenção"
	#endif
#endif
