#ifdef SPANISH
	#define STR0001 "Geracion de Facturas"
	#define STR0002 "Buscar "
	#define STR0003 "Visualizar"
	#define STR0004 "Gerar     "
	#define STR0005 "Alterar   "
	#define STR0006 "Excluir   "
	#define STR0007 "Atencion"
	#define STR0008 "Atencion"
	#define STR0009 ", Codigo de Tasa/Diaria definida en el parametro MV_SB1TAXD no existe en el SB1"
	#define STR0010 ", Codigo de Mat/Med definido en el parametro MV_SB1MATM no existe en el SB1"
	#define STR0011 ", Codigo de Servicio Externo definido en el parametro MV_SB1SEXT no existe en el SB1"
	#define STR0012 "El lote final no puede quedar vacio"
	#define STR0013 " El lote final no puede ser menor que el lote inicial"
	#define STR0014 "Mes/Ano de Referencia no debe quedar vacio"
	#define STR0015 "El Mes/Ano de referencia no es valido"
	#define STR0016 "No hay lotes dentro de los parametros informados"
	#define STR0017 "El campo GAT_NUMLOT ("
	#define STR0018 ") deve estar en uso. Accione el administrador del sistema."
	#define STR0019 "No encontro Formulario Liberado para facturar"
	#define STR0020 " Gastos no encontrados"
	#define STR0021 "Reg.A"
	#define STR0022 "Paciente"
	#define STR0023 " Total Hospital  Total Repase   Total Directo Total de Cuenta"
	#define STR0024 "Espere, procesando gastos"
	#define STR0025 "Unidad "
	#define STR0026 "Unidad "
	#define STR0027 "TOTAL DE FACTURA / REMESA"
	#define STR0028 "Condicion de pago"
	#define STR0029 "Valor Descuento"
	#define STR0030 "Porcent. Descuento"
	#define STR0031 "Descripcion Descuento"
	#define STR0032 "Factura Generada: "
	#define STR0033 " Serie "
	#define STR0034 "Excluyendo movimiento de remesa anterior"
	#define STR0035 " Prefijo "
	#define STR0036 "Removiendo movimiento de remesa anterior"
	#define STR0037 "Adicionando movimiento de la nueva remesa"
	#define STR0038 "Código de cliente en el registro del Convenio "
	#define STR0039 " esta en blanco"
	#define STR0040 "Codigo del convenio como cliente"
	#define STR0041 "Tienda"
	#define STR0042 "No encontrado en el registro de clientes"
	#define STR0043 "Naturaleza del cliente"
	#define STR0044 " Tienda "
	#define STR0045 ", es campo obligatorio para generacion de factura"
	#define STR0046 "TES "
	#define STR0047 " definido en el parametro MV_TESNFS no encontrado"
	#define STR0048 "Condicion de Pago "
	#define STR0049 " definido en el parametro MV_CPAGHSP no encontrado"
	#define STR0050 "Vendedor "
	#define STR0051 " definido en el parametro MV_VENDHSP no encontrado"
	#define STR0052 "Factura HSP "
	#define STR0053 "Generando pedido de venta "
	#define STR0054 "Gerando pedido de venta"
	#define STR0055 "Liberando pedido de venta "
	#define STR0056 "Problema con la liberacion para venta..."
	#define STR0057 "Generando factura de venta"
	#define STR0058 "Condicion de Pago "
	#define STR0059 " no encontrada"
	#define STR0060 "Digite las fechas y los "
	#define STR0061 "porcentajes"
	#define STR0062 "La cuota "
	#define STR0063 " de los titulos"
	#define STR0064 "El valor de la cuota "
	#define STR0065 " no fue informado"
	#define STR0066 "La cuota "
	#define STR0067 " posee valor informado pero, no tiene la fecha de la cuota"
	#define STR0068 "Ninguna fecha fue informada para las cuotas"
	#define STR0069 "Campo "
	#define STR0070 " Código "
	#define STR0071 " con error de definicion. "
	#define STR0072 "neste tipo de condição de pagamento só é aceito 0 ou % no campo "
	#define STR0073 "Historico Financiero"
	#define STR0074 "Digite el historico del titulo a ser generado en el financeiro"
	#define STR0075 "Graba el nuevo numero de remesa en el convenio ["
	#define STR0076 "¿Desea imprimir el recibo de envio de remesa?"
	#define STR0077 "Lote"
	#define STR0078 "Gastos no encontrados"
	#define STR0079 "Hospital"
	#define STR0080 "Repase"
	#define STR0081 "Directo"
	#define STR0082 "Total"
	#define STR0083 "Descripcion"
	#define STR0084 "El codigo del convenio es obligatorio"
	#define STR0085 "Codigo de convenio invalido"
	#define STR0086 "Factura no encontrada o no pertenece al convenio informado"
	#define STR0087 "Modalidad del cliente es campo obligatorio para generacion de la factura"
#else
	#ifdef ENGLISH
		#define STR0001 "Invoice generation"
		#define STR0002 "Search "
		#define STR0003 "View"
		#define STR0004 "Generate  "
		#define STR0005 "Modify   "
		#define STR0006 "Delete   "
		#define STR0007 ", Procedure code defined in parameter MV_SB1PROC doesnt exist in SB1"
		#define STR0008 "Note"
		#define STR0009 ", Fee/Daily Rt code not defined in parameter MV_SB1TAXD doesnt exist in SB1"
		#define STR0010 ", Code of Mat/Med defined in parameter MV_SB1MATM doesnt exist in SB1"
		#define STR0011 ", Code of External Service defined in parameter MV_SB1SEXT doesnt exist in SB1"
		#define STR0012 "Final lot cannot be blank"
		#define STR0013 "The final lot cannot be smaller than the initial lot"
		#define STR0014 "Reference Month/Year must not be empty"
		#define STR0015 "The Reference Month/year is invalid"
		#define STR0016 "There are no lots within the parameters input"
		#define STR0017 "Field   GAT_NUMLOT ("
		#define STR0018 ") must be in use. Contact the system administrator"
		#define STR0019 "Didnt find Form released for invoicing"
		#define STR0020 "Expenses not found"
		#define STR0021 "Reg.Til"
		#define STR0022 "Patient"
		#define STR0023 " Total Hospital  Total Repass    Total Direct Total of Accont"
		#define STR0024 "Processing expenses, wait"
		#define STR0025 "Unit "
		#define STR0026 "Unit"
		#define STR0027 "TOTAL OF INVOICE/REMITTAN"
		#define STR0028 "Payment condition"
		#define STR0029 "Discount amnt."
		#define STR0030 "Discount percent"
		#define STR0031 "Descriptn Discount"
		#define STR0032 "Invoice gen. "
		#define STR0033 " Series"
		#define STR0034 "Bill generated:"
		#define STR0035 " Prefix "
		#define STR0036 "Deleting movement of previous remittance"
		#define STR0037 "Adding movement of the new remittance"
		#define STR0038 "Client code in the healthcare register "
		#define STR0039 "is blank"
		#define STR0040 "Healthcare code as client"
		#define STR0041 "Shop"
		#define STR0042 "Not found in the client register"
		#define STR0043 "Nature of client"
		#define STR0044 "Shop "
		#define STR0045 ", is mandatory field for generating invoice"
		#define STR0046 "TIO "
		#define STR0047 " defined in parameter MV_TESNFS not found"
		#define STR0048 "Payment condition "
		#define STR0049 "defined in parameter MV_CPAGHSP not found"
		#define STR0050 "Seller "
		#define STR0051 "defined in parameter MV_VENDHSP not found"
		#define STR0052 "Bill HSP "
		#define STR0053 "Generating sale order"
		#define STR0054 "Generating sale order"
		#define STR0055 "Releasing sale order "
		#define STR0056 "Problem releasing for sale..."
		#define STR0057 "Generating sale invoice"
		#define STR0058 "Payment condition "
		#define STR0059 "not found"
		#define STR0060 "Enter the dates and  "
		#define STR0061 "percentages"
		#define STR0062 "values"
		#define STR0063 "of the bills"
		#define STR0064 "Installment amount "
		#define STR0065 "was not input"
		#define STR0066 "Installmnt"
		#define STR0067 "has amount input but not the date of the installment"
		#define STR0068 "No date was input for the installments"
		#define STR0069 "Field "
		#define STR0070 " Code "
		#define STR0071 "with error in definition"
		#define STR0072 "in this type of payment condition only 0 or % accepted in field"
		#define STR0073 "Financial history"
		#define STR0074 "Enter narration of bill to be generated in financial "
		#define STR0075 "Save new remittance number in healthcare ["
		#define STR0076 "Will you print remittance send proof? "
		#define STR0077 "Lot "
		#define STR0078 "Expenses not found "
		#define STR0079 "Hospital"
		#define STR0080 "Transfer"
		#define STR0081 "Direct"
		#define STR0082 "Total"
		#define STR0083 "Description"
		#define STR0084 "Healthcare code is compulsory "
		#define STR0085 "Invalid healthcare code "
		#define STR0086 "Bill not found or does not belong to the healthcare entered"
		#define STR0087 "Customer class is compulsory field for generation of invoice "
	#else
		#define STR0001 "Geração de Faturas"
		#define STR0002 "Pesquisar "
		#define STR0003 "Visualizar"
		#define STR0004 "Gerar     "
		#define STR0005 "Alterar   "
		#define STR0006 "Excluir   "
		#define STR0007 ", Código do Procedimento definido no parametro MV_SB1PROC não existe no SB1"
		#define STR0008 "Atenção"
		#define STR0009 ", Código da Taxa/Diaria definida no parametro MV_SB1TAXD não existe no SB1"
		#define STR0010 ", Código do Mat/Med definido no parametro MV_SB1MATM não existe no SB1"
		#define STR0011 ", Código do Serviço Externo definido no parametro MV_SB1SEXT não existe no SB1"
		#define STR0012 "O lote final não pode ficar vazio"
		#define STR0013 "O lote final não pode ser menor do que o lote inicial"
		#define STR0014 "Mês/Ano de Referência nao deve ficar vazio"
		#define STR0015 "O Mês/Ano de referência não é válido"
		#define STR0016 "Não há lotes dentro dos parâmetros informados"
		#define STR0017 "O campo GAT_NUMLOT ("
		#define STR0018 ") deve estar em uso. Acione o administrador do sistema."
		#define STR0019 "Nao encontrou Guia Liberada para faturar"
		#define STR0020 " Despesas não encontradas"
		#define STR0021 "Reg.Ate"
		#define STR0022 "Paciente"
		#define STR0023 " Total Hospital  Total Repasse   Total Direto Total da Conta"
		#define STR0024 "Aguarde, processando despesas"
		#define STR0025 "Unidade "
		#define STR0026 "Unidade "
		#define STR0027 "TOTAL DA FATURA / REMESSA"
		#define STR0028 "Condicao de pagamento"
		#define STR0029 "Valor Desconto"
		#define STR0030 "Percent. Desconto"
		#define STR0031 "Descricao Desconto"
		#define STR0032 "Nota Gerada: "
		#define STR0033 " Série "
		#define STR0034 "Título Gerado: "
		#define STR0035 " Prefixo "
		#define STR0036 "Removendo movimentacao de remessa anterior"
		#define STR0037 "Adicionando movimentacao da nova remessa"
		#define STR0038 "Código do cliente no cadastro do Convenio "
		#define STR0039 " está em branco"
		#define STR0040 "Codigo do convenio como cliente"
		#define STR0041 "Loja"
		#define STR0042 "Não encontrado no cadastro de clientes"
		#define STR0043 "Natureza do cliente"
		#define STR0044 " Loja "
		#define STR0045 ", é campo obrigatório para geração da nota fiscal"
		#define STR0046 "TES "
		#define STR0047 " definido no parametro MV_TESNFS não encontrado"
		#define STR0048 "Condição de Pagamento "
		#define STR0049 " definido no parametro MV_CPAGHSP não encontrada"
		#define STR0050 "Vendedor "
		#define STR0051 " definido no parametro MV_VENDHSP não encontrado"
		#define STR0052 "Fatura HSP "
		#define STR0053 "Gerando pedido de venda "
		#define STR0054 "Gerando pedido de venda"
		#define STR0055 "Liberando pedido de venda "
		#define STR0056 "Problema com a liberacao para venda..."
		#define STR0057 "Gerando nota fiscal de venda"
		#define STR0058 "Condição de Pagamento "
		#define STR0059 " não encontrada"
		#define STR0060 "Digite as datas e os "
		#define STR0061 "percentuais"
		#define STR0062 "valores"
		#define STR0063 " dos titulos"
		#define STR0064 "O valor da parcela "
		#define STR0065 " não foi informado"
		#define STR0066 "A parcela "
		#define STR0067 " possui valor informado mas não tem a data da parcela"
		#define STR0068 "Nenhuma data foi informada para as parcelas"
		#define STR0069 "Campo "
		#define STR0070 " Código "
		#define STR0071 " com erro de definição. "
		#define STR0072 "neste tipo de condição de pagamento só é aceito 0 ou % no campo "
		#define STR0073 "Histórico Financeiro"
		#define STR0074 "Digite o historico do título a ser gerado no financeiro"
		#define STR0075 "Grava o novo numero de remessa no convenio ["
		#define STR0076 "Deseja imprimir o protocolo de envio de remessa?"
		#define STR0077 "Lote"
		#define STR0078 "Despesas nao encontradas"
		#define STR0079 "Hospital"
		#define STR0080 "Repasse"
		#define STR0081 "Direto"
		#define STR0082 "Total"
		#define STR0083 "Descricao"
		#define STR0084 "O codigo do convenio é obrigatorio"
		#define STR0085 "Codigo do convenio invalido"
		#define STR0086 "Fatura não encontrada ou não pertence ao convenio informado"
		#define STR0087 "Natureza do cliente é campo obrigatório para geração da nota fiscal"
	#endif
#endif
