#ifdef SPANISH
	#define STR0001 "Filtro"
	#define STR0002 "Generacion de Cuentas para Facturacion"
	#define STR0003 "Buscar"
	#define STR0004 "Generar"
	#define STR0005 "Excluir"
	#define STR0006 "Parcial"
	#define STR0007 "Paquete"
	#define STR0008 "Receb.Particular"
	#define STR0009 "Leyenda"
	#define STR0010 "Codigo de Convenio no fue informado"
	#define STR0011 "corretamente, favor ¡ informarlo ! "
	#define STR0012 "Marca o Desmarca Todos"
	#define STR0013 "Guias Disponibles"
	#define STR0014 "NRSEQG - "
	#define STR0015 " ya fue facturada, no sera posible facturarla"
	#define STR0016 "Atencion"
	#define STR0017 "Hospitalar(Control de Cuentas)"
	#define STR0018 "0=No"
	#define STR0019 "1=Si"
	#define STR0020 "Genera Facturacion por Paquete"
	#define STR0021 "Fatura Materiais"
	#define STR0022 "Fatura Medicamentos"
	#define STR0023 "Fatura Taxas/Diarias"
	#define STR0024 "Fatura Procedimentos"
	#define STR0025 "Materiales"
	#define STR0026 "Medicamentos"
	#define STR0027 "Tasas/Diarias"
	#define STR0028 "Procedimientos"
	#define STR0029 "No encontro Paquete para Facturar"
	#define STR0030 "Transfiriendo Mat/Med, Formulario"
	#define STR0031 "Transfiriendo Tasas / Diarias, Formulario"
	#define STR0032 "Transfiriendo Procedimientos, Formulario"
	#define STR0033 "Excluyendo Mat/Med, Formulario"
	#define STR0034 "Exclyendo Tasas / Diarias, Formulario"
	#define STR0035 "Excluyendo Procedimientos, Formulario"
	#define STR0036 "Informar el Codigo de Convenio      "
	#define STR0037 "Transferir"
	#define STR0038 "Informar el Codigo del Plan         "
	#define STR0039 "Plan"
	#define STR0040 "Informar el numero inicial del Formulario "
	#define STR0041 "De Formulario"
	#define STR0042 "Informar el numero final de Formulario   "
	#define STR0043 "Confirma processamento do Extrato ?  "
	#define STR0044 "A Formulario"
	#define STR0045 "Informe el sector de atendimiento"
	#define STR0046 "Sector"
	#define STR0047 "Informe fecha inicial de Atendimiento"
	#define STR0048 "De fecha"
	#define STR0049 "Informe fecha final de Atendimiento"
	#define STR0050 "A la fecha"
	#define STR0051 "Seleccone el Tipo de Atencion   "
	#define STR0052 "Tp. Atendimiento"
	#define STR0053 "Hospitalar"
	#define STR0054 "Ambulatorio"
	#define STR0055 "Portada/Descriptivo"
	#define STR0056 "Informe el Tipo de Formulario        "
	#define STR0057 "Tipo de Guia"
	#define STR0058 "Genera Facturacion de Gastos Realizados"
	#define STR0059 "a la fecha informada.                  "
	#define STR0060 "Generar Facturacion A "
	#define STR0061 "Auditoria"
	#define STR0062 "Generado Facturacion"
	#define STR0063 "Genera Facturacion"
	#define STR0064 "Codigo de Paquete Invalido"
	#define STR0065 "Codigo de Paquete no fue informado"
	#define STR0066 "Este formulario ya tiene facturas generadas"
	#define STR0067 "Este formulario ya posee presupuesto generado."
	#define STR0068 "Orçamento No. "
	#define STR0069 "Este plan no es particular. No sera possible generarle un presupuesto."
	#define STR0070 "Datos da Formulario"
	#define STR0071 "Datos de Convenio"
	#define STR0072 "Gastos "
	#define STR0073 "No hay registro de atendimiento para esta guia. Llame al soporte."
	#define STR0074 "Inconsistencia"
	#define STR0075 "Extracto"
	#define STR0076 "Verifique en la Tabla de Gastos de Procedimiento (GA7)"
	#define STR0077 "Paquete no registrado en la tabla Plano vs. Mat/Med/Proced. Verifique en la Tabla(GAC)"
	#define STR0078 "Fecha de Vigencia expiro. Verifique en la Tabla Planos vs. Mat/Med/Proced(GAC)"
	#define STR0079 "Produto não encontrado na tabela de dados Complementares do Produto (GBI)"
	#define STR0080 "Gastos Referente al Paquete Informado no encontrado, "
	#define STR0081 "Revalorizar"
	#define STR0082 "Opciones para revalorizacion"
	#define STR0083 "Fecha Inicial"
	#define STR0084 "Fecha Final"
	#define STR0085 "Res/Frigobar"
	#define STR0086 "Tasas"
	#define STR0087 "Diarias"
	#define STR0088 "Cambio de plan"
	#define STR0089 "Por"
	#define STR0090 "¿A formulario?"
	#define STR0091 " no es internacion y no puede Generar Facturacion por Paquete"
	#define STR0092 " está cancelada y no puede ser utilizada"
	#define STR0093 "No encontro Gastos para Facturar"
	#define STR0094 "¿ Confirma Generar Cuentas para la Facturacion ?  "
	#define STR0095 "¿ Confirma la Exclusion de las Cuentas de Facturacion ?  "
	#define STR0096 "¿ Confirma la Revalorizacion de las Cuentas ?  "
	#define STR0097 " no se encuentra en la Faturacion, no sera posible excluirla ¡ Atencion !"
	#define STR0098 "¿ Confirma Generar Facturamiento Parcial ?  "
	#define STR0099 "Faturacion"
	#define STR0100 "¡ Esta Guia se encuentra en el Control de Localizacion de Cuentas, Verifique !"
	#define STR0101 "¿ Confirma Generar el Recebimiento de Cuenta Particular ?  "
	#define STR0102 "¿ Confirma el Asiento de Gastos ?  "
	#define STR0103 "Registro"
	#define STR0104 "Atribuir Lote"
	#define STR0105 "Retirar Lote"
	#define STR0106 "Lote"
	#define STR0107 " não pode ser alterada por já estar atrelada a um lote"
	#define STR0108 "  NRGUIA - "
	#define STR0109 "Pendientes"
	#define STR0110 "Los formularios anteriores no fueron procesados"
	#define STR0111 "Transferencia de gastos entre formularios"
	#define STR0112 "Por favor, informe el codigo de formulario de destino"
	#define STR0113 "Formulario no facturado, hay gastos de Mat/Med con valor igual a cero"
	#define STR0114 "Formulario no facturado, hay gasto de Tas/Dia con valor igual a cero"
	#define STR0115 "Formulario no facturado, existe gasto de procedimiento con valor igual a cero."
	#define STR0116 "Lote Atribuido"
	#define STR0117 "Capa de factura"
	#define STR0118 "Descriptivo"
	#define STR0119 "Dcts."
	#define STR0120 "Fichas"
	#define STR0121 "Reval. form.["
	#define STR0122 " Solamente pueden revalorizarse formularios con estatus 3"
	#define STR0123 "Revalorizacion de cuentas"
	#define STR0124 "Paquete    "
	#define STR0125 "Descripcion "
	#define STR0126 "Fch Inicial"
	#define STR0127 "Fch Final  "
	#define STR0128 "CRM       "
	#define STR0129 "Nombre      "
	#define STR0130 "Borra Facturacion"
	#define STR0131 "Facturacion Parcial"
	#define STR0132 "Facturacion finalizada con exito"
	#define STR0133 "Facturacion de paquete"
	#define STR0134 "Facturando ["
	#define STR0135 "Facturacion particular"
	#define STR0136 "Sector no encontrado"
	#define STR0137 "Confirma procesamiento"
	#define STR0138 "Renumerando ["
	#define STR0139 "Borre los registros controladores de la numeracion automatica de los archivos GE5, GE6, GE7 y GD7 de los archivos SXE y SXF"
	#define STR0140 "Renumeracion finalizada"
	#define STR0141 "Campo Obligatorio en blanco"
	#define STR0142 "Atencion"
	#define STR0143 "Por favor, rellene el parametro MV_AUDMEST para validar el stock"
	#define STR0144 "Formulario no encontrado"
	#define STR0145 "Este formulario ya se facturo y no puede modificarse"
	#define STR0146 "Por favor, informe el codigo del formulario de destino"
	#define STR0147 "El formulario de destino informado no es de atencion "
	#define STR0148 "Este formulario ya se facturo y no puede modificarse"
	#define STR0149 "Transferencia en ejecucion. Espere..."
	#define STR0150 "El codigo de formulario del destino informado es el mismo del formulario de origen"
	#define STR0151 "Motivo de la Pendencia no puede quedar sin informacion"
	#define STR0152 "Relacionar Pendencias en la Guia"
	#define STR0153 "Genera Facturacion Parcial"
	#define STR0154 "Generar Facturacion Para Paquetes"
	#define STR0155 "Generar Guia Gasto no Gerneada en la Facturacion"
	#define STR0156 "Asiento de gastos"
	#define STR0157 "Validar Sector"
	#define STR0158 "Grabando ["
	#define STR0159 "Obligatorio registro Campo"
	#define STR0160 "Pacote não encontrado"
	#define STR0161 "Faturamento por Pacote"
	#define STR0162 "Pacote não encontrado no convenio ["
	#define STR0163 "] utilizado na guia"
	#define STR0164 "Considera data base para calculo da vigência"
	#define STR0165 " já possui fatura gerada"
	#define STR0166 " para contas em que o convênio é do tipo (1-Particular), acionar o menu (Recebimento Particular) para que a conta seja enviada ao Caixa."
	#define STR0167 "já tem fatura gerada"
	#define STR0168 "Para que seja possível a exclusão de um faturamento particular, além da exclusão da NF pelo Controle de Caixa, são necessárias também a exclusão do orçamento e do pedido. "
	#define STR0169 "Controle de Contas"
	#define STR0170 "Gerado Faturas"
	#define STR0171 "Associado Extr.Conv."
	#define STR0172 "Liquidado"
		#define STR0173 "Conta Previa"
		#define STR0174 "Faturamento não realizado"
		#define STR0175 "Guias faturadas com sucesso: "
		#define STR0176 "Guias não faturadas: "
		#define STR0177 "O codigo do setor é obrigatorio"
		#define STR0178 "Nenhuma guia selecionada"
		#define STR0179 "Conta Aberta"
		#define STR0180 "Hora Inicial"
		#define STR0181 "Hora Final"
		#define STR0182 "Descrição"
		#define STR0183 "Intercorrência"
		#define STR0184 "Campo obrigatório em branco, Aba [Pacote]"
		#define STR0185 "Campo obrigatório em branco, Aba [Intercorrência]"
		#define STR0186 "Pacote não cadastrado na Aba [Pacote]."
		#define STR0187 "Para faturamento em conta aberta o pacote deverá ser informado na aba [Pacote]"
		#define STR0188 "Pacote já cadastrado na Aba [Pacote]"
		#define STR0189 "Data inválida. Menor que a data do atendimento"
		#define STR0190 "Data inválida. Maior que a data da alta"
		#define STR0191 "CRM do médico não encontrado"
#else
	#ifdef ENGLISH
		#define STR0001 "Filter"
		#define STR0002 "Generation of accounts for billing"
		#define STR0003 "Search"
		#define STR0004 "Gener."
		#define STR0005 "Delete "
		#define STR0006 "Partial"
		#define STR0007 "Packet"
		#define STR0008 "Recei.Particular"
		#define STR0009 "Legend"
		#define STR0010 "Healthcare code was not entered"
		#define STR0011 "correctly, please, enter it ! "
		#define STR0012 "Check or Uncheck all"
		#define STR0013 "Available forms"
		#define STR0014 "NRSEQG - "
		#define STR0015 "was already billed, cannot be billed"
		#define STR0016 "Note"
		#define STR0017 "Hospital(Control Accounts)"
		#define STR0018 "0=No"
		#define STR0019 "1=Yes"
		#define STR0020 "Generate bill by packet"
		#define STR0021 "Bill materials"
		#define STR0022 "Bill medicines"
		#define STR0023 "Bill Fees/Daily Rts"
		#define STR0024 "Bill procedures"
		#define STR0025 "Materials"
		#define STR0026 "Medicines"
		#define STR0027 "Fees/Daily Rt"
		#define STR0028 "Procedures"
		#define STR0029 "Did not find Packet for billing"
		#define STR0030 "Transferring Mat/Med, Form"
		#define STR0031 "Transferring Fees/ Daily Rts, Form"
		#define STR0032 "Transferring Procedures, Form"
		#define STR0033 "Deleting Mat/Med, Form"
		#define STR0034 "Deleting Fees/Daily Rts, Form"
		#define STR0035 "Deleting Procedures, Form"
		#define STR0036 "Enter the healthcare code      "
		#define STR0037 "Heathcar"
		#define STR0038 "Input the Plan code       "
		#define STR0039 "Plan"
		#define STR0040 "Enter the initial form number "
		#define STR0041 "Fm Form"
		#define STR0042 "Enter the final number of Form   "
		#define STR0043 "Confirm processing of Extract ?  "
		#define STR0044 "To form"
		#define STR0045 "Enter the attendance sector"
		#define STR0046 "Sect."
		#define STR0047 "Enter the initial attendance date"
		#define STR0048 "Fm date"
		#define STR0049 "Enter the final attendance date"
		#define STR0050 "To date"
		#define STR0051 "Select the type of attendance   "
		#define STR0052 "Attendance Type"
		#define STR0053 "Hospital"
		#define STR0054 "Policlinic"
		#define STR0055 "Both "
		#define STR0056 "Enter the type of Form        "
		#define STR0057 "Type of Form"
		#define STR0058 "Generate bill of expenses incurred"
		#define STR0059 "till the date entered                  "
		#define STR0060 "Generate bill till "
		#define STR0061 "Checking  "
		#define STR0062 "Bill generated"
		#define STR0063 "Generate bill"
		#define STR0064 "Invalid Packet Code"
		#define STR0065 "Packet Code was not entered"
		#define STR0066 "This form has bills generated"
		#define STR0067 "This form already has budget generatd"
		#define STR0068 "Budget No. "
		#define STR0069 "This plan is not individual. Budget cannot be generated."
		#define STR0070 "Form details"
		#define STR0071 "Healthcare data"
		#define STR0072 "Expense "
		#define STR0073 "There is no record of attendance for this form. Call support."
		#define STR0074 "Inconsistency"
		#define STR0075 "Extract"
		#define STR0076 "Check in the Table of Procedure Expenses (GA7)"
		#define STR0077 "Packet not registered in table Plans X Mat/Med/Proced. Check in the table(GAC)"
		#define STR0078 "Validity date expired. Check in the table Plans X Mat/Med/Proced(GAC)"
		#define STR0079 "Product not found in the data table Product Complements (GBI)"
		#define STR0080 "Expense relating to the Packet input not found, "
		#define STR0081 "Revalue"
		#define STR0082 "Revaluation options"
		#define STR0083 "Initial Date"
		#define STR0084 "Final Date"
		#define STR0085 "Res/Fridge"
		#define STR0086 "Fees"
		#define STR0087 "Daily R"
		#define STR0088 "Change plan"
		#define STR0089 "By"
		#define STR0090 "Plan invalid"
		#define STR0091 " is not admission and cannot generate Billing by Packet"
		#define STR0092 " is canceled and cannot be used"
		#define STR0093 "Didnt find expense for billing"
		#define STR0094 "Confirm generation of accounts for billing?"
		#define STR0095 "Confirm deletion of billing accounts?  "
		#define STR0096 "Confirm Revaluing of accounts?  "
		#define STR0097 "cannot find it in Invoicing, cannot be delete it, Note!!!"
		#define STR0098 "Confirm generation of partial bill?  "
		#define STR0099 "Billing"
		#define STR0100 "is found in the Control of Account Location, please check!!!"
		#define STR0101 "Confirm generation of receipt in private account?  "
		#define STR0102 "Confirm Expense entry ?  "
		#define STR0103 "Lot Maint."
		#define STR0104 "Assign Lot"
		#define STR0105 "Withdraw Lot"
		#define STR0106 "Lot "
		#define STR0107 "cannot be altered as it is linked to one lot"
		#define STR0108 "  NRGUIA - "
		#define STR0109 "Disputes"
		#define STR0110 "The forms above were not processed"
		#define STR0111 "Plan validity date expired"
		#define STR0112 "Invalid healthcare "
		#define STR0113 "Form not invoiced, there are expenses  Mat/Med with value zeroed"
		#define STR0114 "Form not billed, exists Fee/Dai expense with value zeroed"
		#define STR0115 "Form not invoiced, there is an expense Procedure with Value Zero"
		#define STR0116 "Alloc. lot    "
		#define STR0117 "Invoice cover"
		#define STR0118 "Description"
		#define STR0119 "Documents"
		#define STR0120 "Cards "
		#define STR0121 "Re-evaluate form["
		#define STR0122 " Only forms with status 3 can be re-evaluated "
		#define STR0123 "Re-evaluation of accounts"
		#define STR0124 "Package   "
		#define STR0125 "Description"
		#define STR0126 "Initial date"
		#define STR0127 "Final date"
		#define STR0128 "CRM       "
		#define STR0129 "Name      "
		#define STR0130 "Delete Billing "
		#define STR0131 "Partial Billing "
		#define STR0132 "Billing finished successfully "
		#define STR0133 "Package Billing "
		#define STR0134 "Billing ["
		#define STR0135 "Private billing "
		#define STR0136 "Sector not found "
		#define STR0137 "Confirm processing "
		#define STR0138 "Renumerating["
		#define STR0139 "Delete controller records of automatic numbering for files GE5, GE6, GE7 ande GD7 of files SXE and SXF"
		#define STR0140 "Renumeration finished "
		#define STR0141 "Blank compulsory field "
		#define STR0142 "Attention"
		#define STR0143 "Please, fill in the parameter MV_AUDMEST to validate inventory "
		#define STR0144 "Form not found "
		#define STR0145 "Billed for, thus, cannot be edited "
		#define STR0146 "Please, enter destination form code"
		#define STR0147 "Destination form entered does not correspond to attendance"
		#define STR0148 "Billed for, thus, cannot be edited "
		#define STR0149 "Transfer in progress. Please, wait..."
		#define STR0150 "Destination form code entered is the same as the origin form "
		#define STR0151 "Motivo da Pendëncia não pode ficar em branco"
		#define STR0152 "Relacionar Pendëncias na Guia"
		#define STR0153 "Gera Faturamento Parcial"
		#define STR0154 "Gerar Faturamento Para Pacotes"
		#define STR0155 "Gerar Guia Despesas nao Geradas Faturamento"
		#define STR0156 "Lançamentos das Despesas"
		#define STR0157 "Validar Setor"
		#define STR0158 "Gravando ["
		#define STR0159 "Obrigatorio Cadastro Campo"
		#define STR0160 "Pacote não encontrado"
		#define STR0161 "Faturamento por Pacote"
		#define STR0162 "Pacote não encontrado no convenio ["
		#define STR0163 "] utilizado na guia"
		#define STR0164 "Considera data base para calculo da vigência"
		#define STR0165 " já possui fatura gerada"
		#define STR0166 " para contas em que o convênio é do tipo (1-Particular), acionar o menu (Recebimento Particular) para que a conta seja enviada ao Caixa."
		#define STR0167 "já tem fatura gerada"
		#define STR0168 "Para que seja possível a exclusão de um faturamento particular, além da exclusão da NF pelo Controle de Caixa, são necessárias também a exclusão do orçamento e do pedido. "
		#define STR0169 "Controle de Contas"
		#define STR0170 "Gerado Faturas"
		#define STR0171 "Associado Extr.Conv."
		#define STR0172 "Liquidado"
		#define STR0173 "Conta Previa"
		#define STR0174 "Faturamento não realizado"
		#define STR0175 "Guias faturadas com sucesso: "
		#define STR0176 "Guias não faturadas: "
		#define STR0177 "O codigo do setor é obrigatorio"
		#define STR0178 "Nenhuma guia selecionada"
		#define STR0179 "Conta Aberta"
		#define STR0180 "Hora Inicial"
		#define STR0181 "Hora Final"
		#define STR0182 "Descrição"
		#define STR0183 "Intercorrência"
		#define STR0184 "Campo obrigatório em branco, Aba [Pacote]"
		#define STR0185 "Campo obrigatório em branco, Aba [Intercorrência]"
		#define STR0186 "Pacote não cadastrado na Aba [Pacote]."
		#define STR0187 "Para faturamento em conta aberta o pacote deverá ser informado na aba [Pacote]"
		#define STR0188 "Pacote já cadastrado na Aba [Pacote]"
		#define STR0189 "Data inválida. Menor que a data do atendimento"
		#define STR0190 "Data inválida. Maior que a data da alta"
		#define STR0191 "CRM do médico não encontrado"
	#else
		#define STR0001 "Filtro"
		#define STR0002 "Geração de Contas para o Faturamento"
		#define STR0003 "Pesquisar"
		#define STR0004 "Gerar"
		#define STR0005 "Excluir"
		#define STR0006 "Parcial"
		#define STR0007 "Pacote"
		#define STR0008 "Receb.Particular"
		#define STR0009 "Legenda"
		#define STR0010 "Código do Convënio não foi informado"
		#define STR0011 "corretamente, favor, informa-lo ! "
		#define STR0012 "Marca ou Desmarca Todos"
		#define STR0013 "Guias Disponiveis"
		#define STR0014 "NRSEQG - "
		#define STR0015 " já foi faturada, não será possível faturá-la"
		#define STR0016 "Atenção"
		#define STR0017 "Hospitalar(Controle Contas)"
		#define STR0018 "0=Nao"
		#define STR0019 "1=Sim"
		#define STR0020 "Gera Faturamento Por Pacote"
		#define STR0021 "Fatura Materiais"
		#define STR0022 "Fatura Medicamentos"
		#define STR0023 "Fatura Taxas/Diarias"
		#define STR0024 "Fatura Procedimentos"
		#define STR0025 "Materiais"
		#define STR0026 "Medicamentos"
		#define STR0027 "Taxas/Diarias"
		#define STR0028 "Procedimentos"
		#define STR0029 "Não encontrou Pacote para Faturar"
		#define STR0030 "Transferindo Mat/Med, Guia"
		#define STR0031 "Transferindo Taxas / Diarias, Guia"
		#define STR0032 "Transferindo Procedimentos, Guia"
		#define STR0033 "Excluindo Mat/Med, Guia"
		#define STR0034 "Excluindo Taxas / Diarias, Guia"
		#define STR0035 "Excluindo Procedimentos, Guia"
		#define STR0036 "Informar o Codigo do Convenio      "
		#define STR0037 "Transferir"
		#define STR0038 "Informar o Codigo do Plano         "
		#define STR0039 "Plano"
		#define STR0040 "Informar o numero inicial da Guia "
		#define STR0041 "De Guia"
		#define STR0042 "Informar o numero final da Guia   "
		#define STR0043 "Confirma processamento do Extrato ?  "
		#define STR0044 "Ate Guia"
		#define STR0045 "Informe o setor de atendimento"
		#define STR0046 "Setor"
		#define STR0047 "Informe data inicial de Atendimento"
		#define STR0048 "Da data"
		#define STR0049 "Informe data final de Atendimento"
		#define STR0050 "Ate a data"
		#define STR0051 "Selecione o Tipo de Atendimento   "
		#define STR0052 "Tp. Atendimento"
		#define STR0053 "Hospitalar"
		#define STR0054 "Ambulatorio"
		#define STR0055 "Capa/Descritivo"
		#define STR0056 "Informe o Tipo de Guia        "
		#define STR0057 "Tipo de Guia"
		#define STR0058 "Gera Faturamento de Despesas Realizadas"
		#define STR0059 "ate a data informada.                  "
		#define STR0060 "Gerar Faturamento Ate "
		#define STR0061 "Conferencia"
		#define STR0062 "Gerado Faturamento"
		#define STR0063 "Gera Faturamento"
		#define STR0064 "Codigo do Pacote Invalido"
		#define STR0065 "Codigo do Pacote nao foi informado"
		#define STR0066 "Esta guia já tem faturas geradas"
		#define STR0067 "Esta guia já possui orçamento gerado."
		#define STR0068 "Orçamento No. "
		#define STR0069 "Este plano não é particular. Não será possível gerar orçamento."
		#define STR0070 "Dados da Guia"
		#define STR0071 "Dados do Convenio"
		#define STR0072 "Despesa "
		#define STR0073 "Não há registro de atendimento para esta guia. Chame o suporte."
		#define STR0074 "Inconsistencia"
		#define STR0075 "Extrato"
		#define STR0076 "Verifique na Tabela de Despesas de Procedimento (GA7)"
		#define STR0077 "Pacote não cadastrado na tabela Planos X Mat/Med/Proced. Verifique na Tabela(GAC)"
		#define STR0078 "Data de Vigencia expirou. Verifique na Tabela Planos X Mat/Med/Proced(GAC)"
		#define STR0079 "Produto não encontrado na tabela de dados Complementares do Produto (GBI)"
		#define STR0080 "Despesa Referente ao Pacote Informado não encontrada, "
		#define STR0081 "Revalorizar"
		#define STR0082 "Opções para revalorização"
		#define STR0083 "Data Inicial"
		#define STR0084 "Data Final"
		#define STR0085 "Res/Frigobar"
		#define STR0086 "Taxas"
		#define STR0087 "Diarias"
		#define STR0088 "Troca plano"
		#define STR0089 "Por"
		#define STR0090 "Para guia ?"
		#define STR0091 " não é internação e não pode Gerar Faturamento por Pacote"
		#define STR0092 " está cancelada e não pode ser utilizada"
		#define STR0093 "Não encontrou Despesa para Faturar"
		#define STR0094 "Confirma Gerar Contas para o Faturamento?  "
		#define STR0095 "Confirma a Exclusao das Contas do Faturamento?  "
		#define STR0096 "Confirma a Revalorizacao das Contas?  "
		#define STR0097 " não encontra-se no Faturamento, nao sera possivel exclui-la, Atencao!!!"
		#define STR0098 "Confirma Gerar Faturamento Parcial?  "
		#define STR0099 "Faturamento"
		#define STR0100 "Esta Guia encontra-se no Controle de Localizacao de Contas, Verifique!!!"
		#define STR0101 "Confirma Gerar o Recebimento de Conta Particular?  "
		#define STR0102 "Confirma o Lancamento de Despesas ?  "
		#define STR0103 "Cadastro"
		#define STR0104 "Atribuir Lote"
		#define STR0105 "Retirar Lote"
		#define STR0106 "Lote"
		#define STR0107 " não pode ser alterada por já estar atrelada a um lote"
		#define STR0108 "  NRGUIA - "
		#define STR0109 "Pendencias"
		#define STR0110 "As Guias acima Nao foram Processadas"
		#define STR0111 "Transferencia de despesas entre guias"
		#define STR0112 "Por favor, informe o codigo da guia de destino"
		#define STR0113 "Guia Não Faturada, existem despesas de Mat/Med Com o Valor Zerado"
		#define STR0114 "Guia Não Faturada, existe despesa de Tax/Dia Com o Valor Zerado"
		#define STR0115 "Guia Não Faturada, existe despesa de Procedto Com o Valor Zerado"
		#define STR0116 "Lote Atribuido"
		#define STR0117 "Capa Fatura"
		#define STR0118 "Descritivo	"
		#define STR0119 "Doctos"
		#define STR0120 "Fichas"
		#define STR0121 "Reval. guia ["
		#define STR0122 " Somente guias com status 3 podem ser revalorizadas"
		#define STR0123 "Revalorização de contas"
		#define STR0124 "Pacote    "
		#define STR0125 "Descrição "
		#define STR0126 "Dt Inicial"
		#define STR0127 "Dt Final  "
		#define STR0128 "CRM       "
		#define STR0129 "Nome      "
		#define STR0130 "Exclui Faturamento"
		#define STR0131 "Faturamento Parcial"
		#define STR0132 "Faturamento terminado com sucesso"
		#define STR0133 "Faturamento de pacote"
		#define STR0134 "Faturando ["
		#define STR0135 "Faturamento particular"
		#define STR0136 "Setor não encontrado"
		#define STR0137 "Confirma processamento"
		#define STR0138 "Renumerando ["
		#define STR0139 "Delete os registros controladores da numeracao automatica dos arquivos GE5, GE6, GE7 e GD7 dos arquivos SXE e SXF"
		#define STR0140 "Renumeracao finalizada"
		#define STR0141 "Campo Obrigatorio em branco"
		#define STR0142 "Atencao"
		#define STR0143 "Por favor, preencha o parametro MV_AUDMEST para validacao do estoque"
		#define STR0144 "Guia nao encontrada"
		#define STR0145 "Esta guia ja foi faturada e nao pode ser alterada"
		#define STR0146 "Por favor, informe o codigo da guia de destino"
		#define STR0147 "A guia de destino informada nao e do atendimento "
		#define STR0148 "Esta guia ja foi faturada e nao pode ser alterada"
		#define STR0149 "Transferencia em execucao. Aguarde..."
		#define STR0150 "O codigo da guia de destino informado e o mesmo do da guia de origem"
		#define STR0151 "Motivo da Pendëncia não pode ficar em branco"
		#define STR0152 "Relacionar Pendëncias na Guia"
		#define STR0153 "Gera Faturamento Parcial"
		#define STR0154 "Gerar Faturamento Para Pacotes"
		#define STR0155 "Gerar Guia Despesas nao Geradas Faturamento"
		#define STR0156 "Lançamentos das Despesas"
		#define STR0157 "Validar Setor"
		#define STR0158 "Gravando ["
		#define STR0159 "Obrigatorio Cadastro Campo"
		#define STR0160 "Pacote não encontrado"
		#define STR0161 "Faturamento por Pacote"
		#define STR0162 "Pacote não encontrado no convenio ["
		#define STR0163 "] utilizado na guia"
		#define STR0164 "Considera data base para calculo da vigência"
		#define STR0165 " já possui fatura gerada"
		#define STR0166 " para contas em que o convênio é do tipo (1-Particular), acionar o menu (Recebimento Particular) para que a conta seja enviada ao Caixa."
		#define STR0167 "já tem fatura gerada"
		#define STR0168 "Para que seja possível a exclusão de um faturamento particular, além da exclusão da NF pelo Controle de Caixa, são necessárias também a exclusão do orçamento e do pedido. "
		#define STR0169 "Controle de Contas"
		#define STR0170 "Gerado Faturas"
		#define STR0171 "Associado Extr.Conv."
		#define STR0172 "Liquidado"
		#define STR0173 "Conta Previa"
		#define STR0174 "Faturamento não realizado"
		#define STR0175 "Guias faturadas com sucesso: "
		#define STR0176 "Guias não faturadas: "
		#define STR0177 "O codigo do setor é obrigatorio"
		#define STR0178 "Nenhuma guia selecionada"
		#define STR0179 "Conta Aberta"
		#define STR0180 "Hora Inicial"
		#define STR0181 "Hora Final"
		#define STR0182 "Descrição"
		#define STR0183 "Intercorrência"
		#define STR0184 "Campo obrigatório em branco, Aba [Pacote]"
		#define STR0185 "Campo obrigatório em branco, Aba [Intercorrência]"
		#define STR0186 "Pacote não cadastrado na Aba [Pacote]."
		#define STR0187 "Para faturamento em conta aberta o pacote deverá ser informado na aba [Pacote]"
		#define STR0188 "Pacote já cadastrado na Aba [Pacote]"
		#define STR0189 "Data inválida. Menor que a data do atendimento"
		#define STR0190 "Data inválida. Maior que a data da alta"
		#define STR0191 "CRM do médico não encontrado"
	#endif
#endif
