#IFDEF SPANISH
	#define STR0001  "Emision de Pedidos de Compras"
	#define STR0002  "ANULADO POR EL OPERADOR"
	#define STR0003  "Lugar de Entrega: "
	#define STR0004  "CP.:"
	#define STR0005  "Lugar de Cobranza: "
	#define STR0006  "Condicion de Pago "
	#define STR0007  "|Fch. de Emision|"
	#define STR0008  "Total de Mercaderias: "
	#define STR0009  "| Observac."
	#define STR0010  "|   NOTA: Solo aceptaremos la mercaderia si en su Factura consta el numero de nuestro Pedido de Compra."
	#define STR0011  "Continua ..."
	#define STR0012  " - Continuacion"
	#define STR0013  " P E D I D O  D E  C O M P R A S"
	#define STR0014  "a.Cop"
	#define STR0015  "Insc.:"
	#define STR0016  "TEL.:"
	#define STR0017  "FAX.:"
	#define STR0018  "N.C.:"
	#define STR0019  "Itm|   Codigo       Descripc. del Material       |UM|  Cant.      |  Valor Unitario|  Valor Total    |Entrega   |S.C.               |"
#ELSE
	#IFDEF ENGLISH
		#define STR0001  "Print Purchase Orders"
		#define STR0002  "CANCELLED BY THE OPERATOR"
		#define STR0003  "Delivery Location : "
		#define STR0004  "ZIP.:"
		#define STR0005  "Collction Location : "
		#define STR0006  "Payment Terms "
		#define STR0007  "|Issue Date|"
		#define STR0008  "Total of Goods : "
		#define STR0009  "| Comments"
		#define STR0010  "|   NOTE: The goods will be accepted only if the Purchase Order number is described in the Invoice."
		#define STR0011  "Continued on next page..."
		#define STR0012  " - Continued from previous page"
		#define STR0013  " P U R C H A S E   O R D E R"
		#define STR0014  "(Copy #)"
		#define STR0015  "I.E.:"
		#define STR0016  "PH.:"
		#define STR0017  "FAX.:"
		#define STR0018  "CNPJ:"
		#define STR0019  "Itm|   Code         Goods` Description           |UM|  Quantity   |  Unit Value    |  Total Value    |Delivery  |P.R.               |"
	#ELSE
		#define STR0001  "Emissao dos Pedidos de Compras"
		#define STR0002  "CANCELADO PELO OPERADOR"
		#define STR0003  "Local de Entrega  : "
		#define STR0004  "CEP.:"
		#define STR0005  "Local de Cobranca : "
		#define STR0006  "Condicao de Pagto "
		#define STR0007  "|Data de Emissao|"
		#define STR0008  "Total das Mercadorias : "
		#define STR0009  "| Observacoes"
		#define STR0010  "|   NOTA: So aceitaremos a mercadoria se na sua Nota Fiscal constar o numero do nosso Pedido de Compra."
		#define STR0011  "Continua ..."
		#define STR0012  " - Continuacao"
		#define STR0013  " P E D I D O  D E  C O M P R A S"
		#define STR0014  "a.VIA"
		#define STR0015  "I.E.:"
		#define STR0016  "TEL.:"
		#define STR0017  "FAX.:"
		#define STR0018  "CNPJ:"
		#define STR0019  "Itm|Codigo         |Descricao do Material        |UM|   Quantidade|  Valor Unitario|      Valor Total|Entrega   | Solicit. Compra |"
	#ENDIF
#ENDIF