#IFDEF SPANISH
   #define STR0001 "Pesquisar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Alterar"
   #define STR0005 "Excluir"
   #define STR0006 "Imprimir"
   #define STR0007 "Tipo de Atividade Time-sheet"
   #define STR0008 "Modelo de Dados de Tipo de Atividade Time-sheet"
   #define STR0009 "Dados de Tipo de Atividade Time-sheet"
   #define STR0010 "Descrição do Tipo por Idioma"
   #define STR0011 "É preciso incluir todos os idiomas"
   #define STR0012 "É preciso incluir todas descrições"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Imprimir"
      #define STR0007 "Tipo de Atividade Time-sheet"
      #define STR0008 "Modelo de Dados de Tipo de Atividade Time-sheet"
      #define STR0009 "Dados de Tipo de Atividade Time-sheet"
      #define STR0010 "Descrição do Tipo por Idioma"
      #define STR0011 "É preciso incluir todos os idiomas"
      #define STR0012 "É preciso incluir todas descrições"
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Imprimir"
      #define STR0007 "Tipo de Atividade Time-sheet"
      #define STR0008 "Modelo de Dados de Tipo de Atividade Time-sheet"
      #define STR0009 "Dados de Tipo de Atividade Time-sheet"
      #define STR0010 "Descrição do Tipo por Idioma"
      #define STR0011 "É preciso incluir todos os idiomas"
      #define STR0012 "É preciso incluir todas descrições"
   #ENDIF
#ENDIF
