#IFDEF SPANISH
   #define STR0001  "Pesquisar"
   #define STR0002  "Visualizar"
   #define STR0003  "Incluir"
   #define STR0004  "Alterar"
   #define STR0005  "Excluir"
   #define STR0006  "Imprimir"
   #define STR0007  "Cargo"
   #define STR0008  "Modelo de Dados de Cadastro Cargo"
   #define STR0009  "Dados de Cadastro Cargo"
   #define STR0010  "Cadastro Cargo x Cliente"   
   #define STR0011  "É necessário vincular ao menos um cliente"   
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Pesquisar"
      #define STR0002  "Visualizar"
      #define STR0003  "Incluir"
      #define STR0004  "Alterar"
      #define STR0005  "Excluir"
      #define STR0006  "Imprimir"
      #define STR0007  "Cargo"
      #define STR0008  "Modelo de Dados de Cadastro Cargo"
      #define STR0009  "Dados de Cadastro Cargo"
      #define STR0010  "Cadastro Cargo x Cliente"   
      #define STR0011  "É necessário vincular ao menos um cliente"   
   #ELSE
      #define STR0001  "Pesquisar"
      #define STR0002  "Visualizar"
      #define STR0003  "Incluir"
      #define STR0004  "Alterar"
      #define STR0005  "Excluir"
      #define STR0006  "Imprimir"
      #define STR0007  "Cargo"
      #define STR0008  "Modelo de Dados de Cadastro Cargo"
      #define STR0009  "Dados de Cadastro Cargo"
      #define STR0010  "Cadastro Cargo x Cliente"   
      #define STR0011  "É necessário vincular ao menos um cliente"   
   #ENDIF
#ENDIF
