#IFDEF SPANISH
	#define STR0001 "Erro ao preencher o código do Grupo / Cliente / Loja"
	#define STR0002 "Erro ao preencher o código do Grupo"
	#define STR0003 "Não há registro relacionado a este código"
	#define STR0004 "A Empresa de Ebilling não foi definida no cadastro do cliente"
	#define STR0005 "Dados do cliente não preenchidos"
	#define STR0006 "Marcar os Lançamentos como:"
	#define STR0007 "Ok"
	#define STR0008 "Cancelar"
	#define STR0009 "Cpo Obrig"
	#define STR0010 "O campo deve ser preenchido"
	#define STR0011 "Data informada está inválida!"
	#define STR0012 "Erro ao gravar a data final do histórico"
	#define STR0013 "Não foi possível gravar o histórico do caso"
	#define STR0014 "Não é permitido histórico futuro"
	#define STR0015 "Ano-Mes final deve ser maior que Ano-Mes inicial"
	#define STR0016 "Problema para cancelar o WO"
	#define STR0017 "Número da Fatura inválido"
	#define STR0018 "Não é possível enviar Fatura cancelada para WO"
	#define STR0019 "Não é possível enviar Fatura cancelada para WO, é preciso cancelar o compromisso antes de cancelar a Fatura"
	#define STR0020 "A Data Final deve ser maior do que a Data Inicial"
	#define STR0021 "É necessário informar a cotação da moeda "
	#define STR0022 " na data "
	#define STR0023 "Não existe valor do índice "
	#define STR0024 " cadastrado no Ano-Mês "
	#define STR0025 "É preciso preencher o ano-nês final deste histórico"
	#define STR0026 "Períodos sobrepostos no histórico"
	#define STR0027 "É preciso incluir todas as descrições!"
	#define STR0028 "Não é possível enviar Fatura cancelada para WO pois ocorreu a baixa parcial ou total do título financeiro"
	#define STR0029 "Aguarde"
	#define STR0030 "Cancelando Financeiro......"
	#define STR0031 "Erro nos parametros. Comunique a TOTVS."
#ELSE
	#IFDEF ENGLISH
		#define STR0001 "Erro ao preencher o código do Grupo / Cliente / Loja"
		#define STR0002 "Erro ao preencher o código do Grupo"
		#define STR0003 "Não há registro relacionado a este código"
		#define STR0004 "A Empresa de Ebilling não foi definida no cadastro do cliente"
		#define STR0005 "Dados do cliente não preenchidos"
		#define STR0006 "Marcar os Lançamentos como:"
		#define STR0007 "Ok"
		#define STR0008 "Cancelar"
		#define STR0009 "Cpo Obrig"
		#define STR0010 "O campo deve ser preenchido"
		#define STR0011 "Data informada está inválida."
		#define STR0012 "Erro ao gravar a data final do histórico"
		#define STR0013 "Não foi possível gravar o histórico do caso"
		#define STR0014 "Não é permitido histórico futuro"
		#define STR0015 "Ano-Mes final deve ser maior que Ano-Mes inicial"
		#define STR0016 "Problema para cancelar o WO"
		#define STR0017 "Número da Fatura inválido"
		#define STR0018 "Não é possível enviar Fatura cancelada para WO"
		#define STR0019 "Não é possível enviar Fatura cancelada para WO, é preciso cancelar o compromisso antes de cancelar a Fatura"
		#define STR0020 "A Data Final deve ser maior do que a Data Inicial"
		#define STR0021 "É necessário informar a cotação da moeda "
		#define STR0022 " na data "
		#define STR0023 "Não existe valor do índice "
		#define STR0024 " cadastrado no Ano-Mês "
		#define STR0025 "É preciso preencher o ano-nês final deste histórico"
		#define STR0026 "Períodos sobrepostos no histórico"
		#define STR0027 "É preciso incluir todas as descrições!"
		#define STR0028 "Não é possível enviar Fatura cancelada para WO pois ocorreu a baixa parcial ou total do título financeiro"
		#define STR0029 "Aguarde"
		#define STR0030 "Cancelando Financeiro......"
		#define STR0031 "Erro nos parametros. Comunique a TOTVS."
	#ELSE
		#define STR0001 "Erro ao preencher o código do Grupo / Cliente / Loja"
		#define STR0002 "Erro ao preencher o código do Grupo"
		#define STR0003 "Não há registro relacionado a este código"
		#define STR0004 "A Empresa de Ebilling não foi definida no cadastro do cliente"
		#define STR0005 "Dados do cliente não preenchidos"
		#define STR0006 "Marcar os Lançamentos como:"
		#define STR0007 "Ok"
		#define STR0008 "Cancelar"
		#define STR0009 "Cpo Obrig"
		#define STR0010 "O campo deve ser preenchido"
		#define STR0011 "Data informada está inválida."
		#define STR0012 "Erro ao gravar a data final do histórico"
		#define STR0013 "Não foi possível gravar o histórico do caso"
		#define STR0014 "Não é permitido histórico futuro"
		#define STR0015 "Ano-Mes final deve ser maior que Ano-Mes inicial"
		#define STR0016 "Problema para cancelar o WO"
		#define STR0017 "Número da Fatura inválido"
		#define STR0018 "Não é possível enviar Fatura cancelada para WO"
		#define STR0019 "Não é possível enviar Fatura cancelada para WO, é preciso cancelar o compromisso antes de cancelar a Fatura"
		#define STR0020 "A Data Final deve ser maior do que a Data Inicial"
		#define STR0021 "É necessário informar a cotação da moeda "
		#define STR0022 " na data "
		#define STR0023 "Não existe valor do índice "
		#define STR0024 " cadastrado no Ano-Mês "
		#define STR0025 "É preciso preencher o ano-nês final deste histórico"
		#define STR0026 "Períodos sobrepostos no histórico"
		#define STR0027 "É preciso incluir todas as descrições!"
		#define STR0028 "Não é possível enviar Fatura cancelada para WO pois ocorreu a baixa parcial ou total do título financeiro"
		#define STR0029 "Aguarde"
		#define STR0030 "Cancelando Financeiro......"
		#define STR0031 "Erro nos parametros. Comunique a TOTVS."
	#ENDIF
#ENDIF