#ifdef SPANISH
	#define STR0001 "Endereco: "
	#define STR0002 ", Complemento :"
	#define STR0003 ", Bairro :"
	#define STR0004 ", Cidade :"
	#define STR0005 ", Estado :"
	#define STR0006 ", CEP :"
	#define STR0007 " ** Insc.Estadual: "
	#define STR0008 " ** Razao Social: "
	#define STR0009 " ** CNPJ "
	#define STR0010 "Estorne manualmente e em seguida cancele!"
	#define STR0011 "Atenção"
	#define STR0012 "1-Simples Fat."
	#define STR0013 "2-Rem.Ent.Fut"
	#define STR0014 "3-Conta e Ordem"
	#define STR0015 "4-Trans.Simbol"
	#define STR0016 "0-TRF"
	#define STR0017 "Selecione o tipo de retorno"
	#define STR0018 "Devolução"
	#define STR0019 "Troca"
	#define STR0020 "Reentrega"
	#define STR0021 "Logística Reversa"
	#define STR0022 "Retorno NF de Remessa C. e Ord. de Estab. Showroom..."
	#define STR0023 "Aguarde..."
	#define STR0024 "Retorno NF de Remessa Entr. Futura..."
	#define STR0025 "Retorno NF de Transf. Simbólica..."
	#define STR0026 "Atenção! O processo de Logística Reversa somente será efetuado se as Notas Devolvidas forem dos Tipos:"
	#define STR0027 "Remessa Entrega Futura"
	#define STR0028 "Remessa por conta e ordem de Estabelecimento Showroom"
	#define STR0029 "Atenção! O processo de Logística Reversa somente será efetuado se as Nota Devolvida for do Tipo:"
	#define STR0030 "Venda realizada pelo CD Local ou Loja de Entrega"
	#define STR0031 "Retorno NF de Transf. para Loja..."
	#define STR0032 "Atenção! O processo de Logística Reversa não foi efetuado."
	#define STR0033 "Gerando NCC para o cliente..."
	#define STR0034 "Refazendo Pedido Remessa Entr. Futura..."
	#define STR0035 "Refazendo Pedido Remessa C. e Ord. de Estab. Showroom..."
	#define STR0036 "Refazendo Pedido Transf. Simbolica..."
	#define STR0037 "Refazendo Pedido de Venda..."
	#define STR0038 "Atenção! Os Pedidos de Vendas do processo de Logística Reversa não foram gerados."
	#define STR0039 "Atenção! TES: "
	#define STR0040 " não cadastrada na filial: "
	#define STR0041 " ou não cadastrado campo TES de Devolução - F4_TESDV, "
	#define STR0042 "Geração da Nota de Devolução para o Pedido de Venda original: "
	#define STR0043 " não efetuada."
	#define STR0044 "Pedido de Venda"
	#define STR0045 "Antes é necessário faturar os Pedidos: Transferência Simbólica e Remessa Entrega Futura"
	#define STR0046 "Antes é necessário faturar o Pedido: Transferência Simbólica"
	#define STR0047 "OK"
	#define STR0048 "Retorno da NF de Entrada da Loja de Venda..."
	#define STR0049 "Verifique o cadastro de Identifcação de Lojas - SLJ"
	#define STR0050 "Não foi possível faturar o Pedido:"
	#define STR0051 "Item:"
	#define STR0052 "Antes é necessário faturar o Pedido de Transferência no CDM"
	#define STR0053 "Antes é necessário efetuar a classificação do Documento de Entrada:"
	#define STR0054 "Não foi gerado Documento de Entrada para este movimento, verifique o Pedido de Transferência no CDM"
	#define STR0055 "CD Local a ser escolhido deve ser do Tipo CDL, verifique o Código correto de Identificação do CD Local desejado!"
	#define STR0056 "CD Local deve ser do mesmo Estado(UF) da Loja!"
	#define STR0057 "Código de Identificação do CD Local não encontrado!"
#else
	#ifdef ENGLISH
		#define STR0001 "Address: "
		#define STR0002 ", Supplement :"
		#define STR0003 ", District :"
		#define STR0004 ", City :"
		#define STR0005 ", State :"
		#define STR0006 ", Postal Code:"
		#define STR0007 " ** State Registration: "
		#define STR0008 " ** Company Name: "
		#define STR0009 " ** CNPJ "
		#define STR0010 "Reverse manually and then cancel!"
		#define STR0011 "Attention"
		#define STR0012 "1-Simple Inv."
		#define STR0013 "2-Sndr.Iss.Fut"
		#define STR0014 "3-Account and Order"
		#define STR0015 "4-Symbol Trans"
		#define STR0016 "0-TRF"
		#define STR0017 "Select type of return"
		#define STR0018 "Return"
		#define STR0019 "Change"
		#define STR0020 "Redelivery"
		#define STR0021 "Reverse Logistic"
		#define STR0022 "Invoice Return of Remittance C and Showroom Site Ord."
		#define STR0023 "Wait..."
		#define STR0024 "Invoice Return of Future Inbound Remittance "
		#define STR0025 "Invoice Return Symbolic Transfer"
		#define STR0026 "Attention! Reverse Logistics process is only performed if the Returned Invoices are Type:"
		#define STR0027 "Future Delivery Remittance"
		#define STR0028 "Remittance due to account and order of Showroom Site"
		#define STR0029 "Attention! Reverse Logistics process is only performed if the Returned Invoices are Type:"
		#define STR0030 "Sales performed by Local CD or Delivery Store"
		#define STR0031 "Transf Invoice Return for Store..."
		#define STR0032 "Attention! Reverse Logistics process not performed."
		#define STR0033 "Generating NCC for customer"
		#define STR0034 "Redoing Future Inbound Remittance Order"
		#define STR0035 "Redoing Remittance Order C. and Showroom Site Ord."
		#define STR0036 "Redoing Symbolic Transf Order"
		#define STR0037 "Redoing Sales Order"
		#define STR0038 "Attention! Sales Order of Reverse Logistics not generated."
		#define STR0039 "Attention! TIO: "
		#define STR0040 " not entered in branch: "
		#define STR0041 " or not entered field TIO of Return _F4_TESDV, "
		#define STR0042 "Return Invoice Generation for Original Sales Order: "
		#define STR0043 " not made."
		#define STR0044 "Sales Order"
		#define STR0045 "Antes é necessário faturar os Pedidos: Transferência Simbólica e Remessa Entrega Futura"
		#define STR0046 "Antes é necessário faturar o Pedido: Transferência Simbólica"
		#define STR0047 "OK"
		#define STR0048 "Inbound Invoice Return of Sales Store"
		#define STR0049 "Check Stores Identification File - SLJ"
		#define STR0050 "Não foi possível faturar o Pedido:"
		#define STR0051 "Item:"
		#define STR0052 "Antes é necessário faturar o Pedido de Transferência no CDM"
		#define STR0053 "Antes é necessário efetuar a classificação do Documento de Entrada:"
		#define STR0054 "Não foi gerado Documento de Entrada para este movimento, verifique o Pedido de Transferência no CDM"
		#define STR0055 "CD Local a ser escolhido deve ser do Tipo CDL, verifique o Código correto de Identificação do CD Local desejado!"
		#define STR0056 "CD Local deve ser do mesmo Estado(UF) da Loja!"
		#define STR0057 "Código de Identificação do CD Local não encontrado!"
	#else
		#define STR0001 "Endereco: "
		#define STR0002 ", Complemento :"
		#define STR0003 ", Bairro :"
		#define STR0004 ", Cidade :"
		#define STR0005 ", Estado :"
		#define STR0006 ", CEP :"
		#define STR0007 " ** Insc.Estadual: "
		#define STR0008 " ** Razao Social: "
		#define STR0009 " ** CNPJ "
		#define STR0010 "Estorne manualmente e em seguida cancele!"
		#define STR0011 "Atenção"
		#define STR0012 "1-Simples Fat."
		#define STR0013 "2-Rem.Ent.Fut"
		#define STR0014 "3-Conta e Ordem"
		#define STR0015 "4-Trans.Simbol"
		#define STR0016 "0-TRF"
		#define STR0017 "Selecione o tipo de retorno"
		#define STR0018 "Devolução"
		#define STR0019 "Troca"
		#define STR0020 "Reentrega"
		#define STR0021 "Logística Reversa"
		#define STR0022 "Retorno NF de Remessa C. e Ord. de Estab. Showroom..."
		#define STR0023 "Aguarde..."
		#define STR0024 "Retorno NF de Remessa Entr. Futura..."
		#define STR0025 "Retorno NF de Transf. Simbólica..."
		#define STR0026 "Atenção! O processo de Logística Reversa somente será efetuado se as Notas Devolvidas forem dos Tipos:"
		#define STR0027 "Remessa Entrega Futura"
		#define STR0028 "Remessa por conta e ordem de Estabelecimento Showroom"
		#define STR0029 "Atenção! O processo de Logística Reversa somente será efetuado se as Nota Devolvida for do Tipo:"
		#define STR0030 "Venda realizada pelo CD Local ou Loja de Entrega"
		#define STR0031 "Retorno NF de Transf. para Loja..."
		#define STR0032 "Atenção! O processo de Logística Reversa não foi efetuado."
		#define STR0033 "Gerando NCC para o cliente..."
		#define STR0034 "Refazendo Pedido Remessa Entr. Futura..."
		#define STR0035 "Refazendo Pedido Remessa C. e Ord. de Estab. Showroom..."
		#define STR0036 "Refazendo Pedido Transf. Simbolica..."
		#define STR0037 "Refazendo Pedido de Venda..."
		#define STR0038 "Atenção! Os Pedidos de Vendas do processo de Logística Reversa não foram gerados."
		#define STR0039 "Atenção! TES: "
		#define STR0040 " não cadastrada na filial: "
		#define STR0041 " ou não cadastrado campo TES de Devolução - F4_TESDV, "
		#define STR0042 "Geração da Nota de Devolução para o Pedido de Venda original: "
		#define STR0043 " não efetuada."
		#define STR0044 "Pedido de Venda"
		#define STR0045 "Antes é necessário faturar os Pedidos: Transferência Simbólica e Remessa Entrega Futura"
		#define STR0046 "Antes é necessário faturar o Pedido: Transferência Simbólica"
		#define STR0047 "OK"
		#define STR0048 "Retorno da NF de Entrada da Loja de Venda..."
		#define STR0049 "Verifique o cadastro de Identifcação de Lojas - SLJ"
		#define STR0050 "Não foi possível faturar o Pedido:"
		#define STR0051 "Item:"
		#define STR0052 "Antes é necessário faturar o Pedido de Transferência no CDM"
		#define STR0053 "Antes é necessário efetuar a classificação do Documento de Entrada:"
		#define STR0054 "Não foi gerado Documento de Entrada para este movimento, verifique o Pedido de Transferência no CDM"
		#define STR0055 "CD Local a ser escolhido deve ser do Tipo CDL, verifique o Código correto de Identificação do CD Local desejado!"
		#define STR0056 "CD Local deve ser do mesmo Estado(UF) da Loja!"
		#define STR0057 "Código de Identificação do CD Local não encontrado!"
	#endif
#endif
