#ifdef SPANISH
	#define STR0001 "INICIO DO PROCESSO "
	#define STR0002 " - SCHEDULE - Tarefa "
	#define STR0003 " - EM: "
	#define STR0004 "FIM DO PROCESSO "
	#define STR0005 " - SMARTC/PILHA CHAMADA "
	#define STR0006 "JÁ EXISTE EXECUÇÃO DA ROTINA "
	#define STR0007 "Erro ao consumir o método 'Pedidos' do WebService!"
	#define STR0008 "Erro no método XmlParser: "
	#define STR0009 "Erro ao consumir o método 'ConfirmaPedidos' do WebService!"
	#define STR0010 "Error en ExecAuto"
	#define STR0011 " ¡Registro no se incluyo por el ExecAuto!"
	#define STR0012 "Exito en ejecucion del ExecAuto"
	#define STR0013 "Presupuesto: "
	#define STR0014 "Pedido borrado con exito "
#else
	#ifdef ENGLISH
		#define STR0001 "PROCESS START "
		#define STR0002 " - SCHEDULE - Task "
		#define STR0003 " - IN: "
		#define STR0004 "PROCESS END "
		#define STR0005 " - SMARTC/CALL PILE "
		#define STR0006 "THERE ALREADY IS ROUTINE RUN "
		#define STR0007 "Error when consuming WebService Orders method!"
		#define STR0008 "Error in XmlParser method: "
		#define STR0009 "Error when consuming WebService ConfirmOrders method!"
		#define STR0010 "ExecAuto Error"
		#define STR0011 " Record not included by ExecAuto!"
		#define STR0012 "ExecAuto successfully executed"
		#define STR0013 "Quotation: "
		#define STR0014 "Order successfully deleted "
	#else
		#define STR0001 "INICIO DO PROCESSO "
		#define STR0002 " - SCHEDULE - Tarefa "
		#define STR0003 " - EM: "
		#define STR0004 "FIM DO PROCESSO "
		#define STR0005 " - SMARTC/PILHA CHAMADA "
		#define STR0006 "JÁ EXISTE EXECUÇÃO DA ROTINA "
		#define STR0007 "Erro ao consumir o método 'Pedidos' do WebService!"
		#define STR0008 "Erro no método XmlParser: "
		#define STR0009 "Erro ao consumir o método 'ConfirmaPedidos' do WebService!"
		#define STR0010 "Erro no ExecAuto"
		#define STR0011 " Registro não foi incluido pelo ExecAuto!"
		#define STR0012 "Sucesso na execução do ExecAuto"
		#define STR0013 "Orçamento: "
		#define STR0014 "Pedido excluido com sucesso "
	#endif
#endif
