#ifdef SPANISH
	#define STR0001 "Falla al manipular el XML"
	#define STR0002 "De-A no puede grabarse la integracion podra tener fallas"
	#define STR0003 "El procesamiento por la otra aplicacion no tuvo exito"
	#define STR0004 "Xml mal formateado. "
	#define STR0005 "¡La version del mensaje informado no se implemento!"
	#define STR0006 "Version no informada en el archivo del adapter."
	#define STR0007 "¡Adapter no encontrado!"
	#define STR0008 "¡La lib de framework Protheus esta desactualizada!"
	#define STR0009 "¡El codigo de InternalId es obligatorio!"
	#define STR0010 "¡Version del mensaje no informada!"
	#define STR0011 "¡Error en el parser de la devolucion!"
	#define STR0012 "¡El codigo del InternalId es obligatorio!"
	#define STR0013 "¡Contenido de MessageContent vacio!"
	#define STR0014 "Version del contrato no soportada."
	#define STR0015 "La version soportada es: "
	#define STR0016 "¡Documento no encontrado en de/a!"
#else
	#ifdef ENGLISH
		#define STR0001 "Failure when loading XML"
		#define STR0002 "From-To cannot be recorded. Integration may be flawed"
		#define STR0003 "Processing by the other application was unsuccessful."
		#define STR0004 "Xml badly formatted. "
		#define STR0005 "The version of the entered message was not implemented!"
		#define STR0006 "Version not entered in the adapter register."
		#define STR0007 "Adapter not found!"
		#define STR0008 "Lib of Protheus framework is outdated!"
		#define STR0009 "The InternalId code is mandatory!"
		#define STR0010 "Message version not entered!"
		#define STR0011 "Error in return parser!"
		#define STR0012 "The InternalId code is mandatory!"
		#define STR0013 "Content of MessageContent empty!"
		#define STR0014 "Product version not supported."
		#define STR0015 "Version supported is: "
		#define STR0016 "Invoice not found in from/to!"
	#else
		#define STR0001 "Falha ao manipular o XML"
		#define STR0002 "De-Para não pode ser gravado a integração poderá ter falhas"
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "O processamento pela outra aplicação não teve sucesso", "Processamento pela outra aplicação não teve sucesso" )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "XML mal formatado. ", "Xml mal formatado. " )
		#define STR0005 "A versão da mensagem informada não foi implementada!"
		#define STR0006 "Versão não informada no cadastro do adapter."
		#define STR0007 "Adapter não encontrado!"
		#define STR0008 "A lib da framework Protheus está desatualizada!"
		#define STR0009 "O código do InternalId é obrigatório!"
		#define STR0010 "Versão da mensagem não informada!"
		#define STR0011 "Erro no parser do retorno!"
		#define STR0012 "O código do InternalId é obrigatório!"
		#define STR0013 "Conteúdo do MessageContent vazio!"
		#define STR0014 "Versão do produto não suportada."
		#define STR0015 "A versão suportada é: "
		#define STR0016 "Documento não encontrado no de/para!"
	#endif
#endif
