#IFDEF SPANISH
         #define STR0001  "Entrega ja cadastrada."
         #define STR0002  "Não há dados para a importação"
         #define STR0003  "Não há dados para a reimportação"
         #define STR0004  "Tentativa de exclusao de entrega nao cadastrada."
         #define STR0005  "Fornecedor/Loja nao cadastrado."
         #define STR0006  "Produto nao cadastrado."
         #define STR0007  "Produto nao tem revisao disponivel."
         #define STR0008  "Tamanho do Lote nao numerico."
         #define STR0009  "Nao ha Amarracao entre o Produto e o Fornecedor."
         #define STR0010  "Situacao do Produto X Fornecedor tem Categoria Nao Recebe"
         #define STR0011  "Solicitante nao cadastrado ou nao especificado."
         #define STR0012  "Solicitante tem status Demitido."
         #define STR0013  "Data de Validade do RIAI expirada."
         #define STR0014	"Entrega ja cadastrada."  
         #define STR0015  "Numero do Lote repetido."
         #define STR0016  "Nao foi possivel gerar o Cod. Identificador Entrega."
         #define STR0017  "Laudo em regime de skip-lote automatico"
         #define STR0018  "Nao foi possivel gerar o Cod. Certificado Qualidade."
         #define STR0019  "Certificar, a partir da avaliacao do Skip-Lote"
         #define STR0020  "Inspecionar, a partir da avaliacao do Skip-Lote"
         #define STR0021  "Entrega excluida no SIGAQIE"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Entrega ja cadastrada."
         #define STR0002  "Não há dados para a importação"
         #define STR0003  "Não há dados para a reimportação"
         #define STR0004  "Tentativa de exclusao de entrega nao cadastrada."
         #define STR0005  "Fornecedor/Loja nao cadastrado."
         #define STR0006  "Produto nao cadastrado."
         #define STR0007  "Produto nao tem revisao disponivel."
         #define STR0008  "Tamanho do Lote nao numerico."
         #define STR0009  "Nao ha Amarracao entre o Produto e o Fornecedor."
         #define STR0010  "Situacao do Produto X Fornecedor tem Categoria Nao Recebe"
         #define STR0011  "Solicitante nao cadastrado ou nao especificado."
         #define STR0012  "Solicitante tem status Demitido."
         #define STR0013  "Data de Validade do RIAI expirada."
         #define STR0014	"Entrega ja cadastrada."  
         #define STR0015  "Numero do Lote repetido."
         #define STR0016  "Nao foi possivel gerar o Cod. Identificador Entrega."
         #define STR0017  "Laudo em regime de skip-lote automatico"
         #define STR0018  "Nao foi possivel gerar o Cod. Certificado Qualidade."
         #define STR0019  "Certificar, a partir da avaliacao do Skip-Lote"
         #define STR0020  "Inspecionar, a partir da avaliacao do Skip-Lote"
         #define STR0021  "Entrega excluida no SIGAQIE"
   #ELSE
         #define STR0001  "Entrega ja cadastrada."
         #define STR0002  "Não há dados para a importação"
         #define STR0003  "Não há dados para a reimportação"
         #define STR0004  "Tentativa de exclusao de entrega nao cadastrada."
         #define STR0005  "Fornecedor/Loja nao cadastrado."
         #define STR0006  "Produto nao cadastrado."
         #define STR0007  "Produto nao tem revisao disponivel."
         #define STR0008  "Tamanho do Lote nao numerico."
         #define STR0009  "Nao ha Amarracao entre o Produto e o Fornecedor."
         #define STR0010  "Situacao do Produto X Fornecedor tem Categoria Nao Recebe"
         #define STR0011  "Solicitante nao cadastrado ou nao especificado."
         #define STR0012  "Solicitante tem status Demitido."
         #define STR0013  "Data de Validade do RIAI expirada."
         #define STR0014	"Entrega ja cadastrada."  
         #define STR0015  "Numero do Lote repetido."
         #define STR0016  "Nao foi possivel gerar o Cod. Identificador Entrega."
         #define STR0017  "Laudo em regime de skip-lote automatico"
         #define STR0018  "Nao foi possivel gerar o Cod. Certificado Qualidade."
         #define STR0019  "Certificar, a partir da avaliacao do Skip-Lote"
         #define STR0020  "Inspecionar, a partir da avaliacao do Skip-Lote"
         #define STR0021  "Entrega excluida no SIGAQIE"
   #ENDIF
#ENDIF