#IFDEF SPANISH
   #define STR0001 "Buscar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Modificar"
   #define STR0005 "Borrar"
   #define STR0006 "Imprimir"
   #define STR0007 "Busqueda"
   #define STR0008 "No fue posible encontrar ningun registro con esta clave de busqueda."
   #define STR0009 "Coloque un item valido para busqueda."
   #define STR0010 "Asistente de Impresion"
   #define STR0011 "Texto"
   #define STR0012 "Elija el orden"
   #define STR0013 "A continuacion se listan los indices de la tabla "
   #define STR0014 "Elija los campos"
   #define STR0015 "A continuacion se listan los campos de la tabla "
   #define STR0016 "Campos de la tabla:"
   #define STR0017 "Campos a imprimir:"
   #define STR0018 "Elija el orden de los campos"
   #define STR0019 "Filtro y Parametros"
   #define STR0020 "Elija el intervalo de registros para iniciar y terminar la impresion, basado en el orden elegido:"
   #define STR0021 "Clave:"
   #define STR0022 "De:"
   #define STR0023 "Hasta:"
   #define STR0024 "Preparar para imprimir"
   #define STR0025 "El informe de "
   #define STR0026 " esta listo para ser impreso."
   #define STR0027 "Haga clic en el boton Opciones de Impresion para configurar los detalles de impresion (impresora, formato,...) o en Finalizar para iniciar la impresion."
   #define STR0028 "Opciones de Impresion"
   #define STR0029 "< &Volver"
   #define STR0030 "&Avanzar >"
   #define STR0031 "&Finalizar"
   #define STR0032 "A&nular"
   #define STR0033 "INTERRUMPIDO POR EL USUARIO"
   #define STR0034 "Total de registros impresos: "
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Search"
      #define STR0002 "View"
      #define STR0003 "Insert"
      #define STR0004 "Edit"
      #define STR0005 "Delete"
      #define STR0006 "Print"
      #define STR0007 "Search"
      #define STR0008 "It was not possible to find a record with this search key."
      #define STR0009 "Please enter a valid item for this search."
      #define STR0010 "Assistente de Impressão"
      #define STR0011 "Texto"
      #define STR0012 "Escolha a ordem"
      #define STR0013 "Abaixo estão relacionados os índices da tabela "
      #define STR0014 "Escolha os campos"
      #define STR0015 "Abaixo estão relacionados os campos da tabela "
      #define STR0016 "Campos da tabela:"
      #define STR0017 "Campos a imprimir:"
      #define STR0018 "Escolha a ordem dos campos"
      #define STR0019 "Filtro e Parametros"
      #define STR0020 "Escolha de qual registro iniciar até qual terminar a impressão, baseado na ordem escolhida:"
      #define STR0021 "Chave:"
      #define STR0022 "De:"
      #define STR0023 "Até:"
      #define STR0024 "Preparar para imprimir"
      #define STR0025 "O relatório de "
      #define STR0026 " esta pronto para ser impresso."
      #define STR0027 "Clique no botão Opções de Impressão para configurar os detalhes de impressão (impressora, formato,...) ou em Finalizar para iniciar a impressão."
      #define STR0028 "Opções de Impressão"
      #define STR0029 "< &Voltar"
      #define STR0030 "&Avançar >"
      #define STR0031 "&Finalizar"
      #define STR0032 "&Cancelar"
      #define STR0033 "INTERROMPIDO PELO USUARIO"
      #define STR0034 "Total de Registros Impressos: "
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Imprimir"
      #define STR0007 "Pesquisa"
      #define STR0008 "Não foi possível encontrar registro com esta chave de pesquisa."
      #define STR0009 "Coloque um item válido a ser pesquisado."
      #define STR0010 "Assistente de Impressão"
      #define STR0011 "Texto"
      #define STR0012 "Escolha a ordem"
      #define STR0013 "Abaixo estão relacionados os índices da tabela "
      #define STR0014 "Escolha os campos"
      #define STR0015 "Abaixo estão relacionados os campos da tabela "
      #define STR0016 "Campos da tabela:"
      #define STR0017 "Campos a imprimir:"
      #define STR0018 "Escolha a ordem dos campos"
      #define STR0019 "Filtro e Parametros"
      #define STR0020 "Escolha de qual registro iniciar até qual terminar a impressão, baseado na ordem escolhida:"
      #define STR0021 "Chave:"
      #define STR0022 "De:"
      #define STR0023 "Até:"
      #define STR0024 "Preparar para imprimir"
      #define STR0025 "O relatório de "
      #define STR0026 " esta pronto para ser impresso."
      #define STR0027 "Clique no botão Opções de Impressão para configurar os detalhes de impressão (impressora, formato,...) ou em Finalizar para iniciar a impressão."
      #define STR0028 "Opções de Impressão"
      #define STR0029 "< &Voltar"
      #define STR0030 "&Avançar >"
      #define STR0031 "&Finalizar"
      #define STR0032 "&Cancelar"
      #define STR0033 "INTERROMPIDO PELO USUARIO"
      #define STR0034 "Total de Registros Impressos: "
   #ENDIF
#ENDIF
