#IFDEF SPANISH
   #define STR0001 "La utilizacion del Alias "
   #define STR0002 " solo es permitida en archivos de "
   #define STR0003 "trabajo, que no utilizan la ChkfIle para apertura"
   #define STR0004 "Proceso de Creacion"
   #define STR0005 "Monousuario para Progress"
   #define STR0006 "Problema en la Clave Indice: "
   #define STR0007 "Indices no borrados"
   #define STR0008 "No fue posible crear el directorio de datos"
   #define STR0009 "Ajuste el ConType del "
   #define STR0010 "Error en la Configuracion del "
   #define STR0011 "El error de conexion anterior es controlable, ¡no se preocupe!"
   #define STR0012 "Para eliminarlo actualice el TopConnect"
   #define STR0013 "Falla Conexion TopConn"
   #define STR0014 "Error ("
   #define STR0015 "Falla Conexion TopProtect"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "The utilization of the Alias "
      #define STR0002 " is only possible for Work "
      #define STR0003 "Files that do not use ChkfIle for Opening"
      #define STR0004 "Creation Process"
      #define STR0005 "Monouser for Progress"
      #define STR0006 "Problems in Index Key : "
      #define STR0007 "Indexes not removed"
      #define STR0008 "It was not possible to create the data directory"
      #define STR0009 "Adjust the ConType of "
      #define STR0010 "Error when Configuring the "
      #define STR0011 "The connection error showed above is controlled. Don´´t worry!"
      #define STR0012 "To eliminte it, update the TopConnect"
      #define STR0013 "Failure in TopConn connection"
      #define STR0014 "Error("
      #define STR0015 "Failure in TopProtect connection"
   #ELSE
      #define STR0001 "A utilizacao do Alias "
      #define STR0002 " Soh eh permitida em Arquivos de "
      #define STR0003 "Trabalho, que nao utilizam a ChkfIle para Abertura"
      #define STR0004 "Processo de Criacao"
      #define STR0005 "Monousuario para Progress"
      #define STR0006 "Problema na Chave Indice : "
      #define STR0007 "Índices não removidos"
      #define STR0008 "Não foi possível criar o diretório de dados"
      #define STR0009 "Ajuste o ConType do "
      #define STR0010 "Erro na Configuração do "
      #define STR0011 "O erro de conexao acima eh controlado, nao se preocupe !!!!"
      #define STR0012 "Para elimina-lo atualize o TopConnect"
      #define STR0013 "Falha Conexão TopConn"
      #define STR0014 "Erro ("
      #define STR0015 "Falha Conexão TopProtect"
   #ENDIF
#ENDIF
