#IFDEF SPANISH
      #define STR0001 "Buscar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Modificar"
      #define STR0005 "Borrar"
      #define STR0006 "Leyenda"
      #define STR0007 "Archivo de Presupuestos vs. Ejercicios"
      #define STR0008 "Este programa permite el mantenimiento del archivo de Ejercicios"
      #define STR0009 "Archivo de Presupuestos vs. Ejercicios - Encabezamiento"
      #define STR0010 "Archivo de Presupuestos vs. Ejercicios - Itemes"
      #define STR0011 "Itemes"
      #define STR0012 "No es posible grabar un Presupuesto por Ejercicio sin valores."
      #define STR0013 "Digite al menos un valor por periodo."
      #define STR0014 "Ejercicio no registrado."
      #define STR0015 "Digite el ejercicio correcto - utilice <F3> para seleccionar."                  
      #define STR0016 "Categoria financiera no existente."
      #define STR0017 "Digite la categoria financiera correcta - utilice <F3> para seleccionar."
      #define STR0018 "La moneda digitada no es valida."
      #define STR0019 "Digite o seleccione la moneda correcta."
      #define STR0020 "Archivo de Presupuestos por Ejercicio ya existente."
      #define STR0021 "Verifique si los datos digitados estan correctos o utilice la opcion <Modificar>."
	  #define STR0022 "Atencion"
	  #define STR0023 "Presupuesto por ejercicio sin valores definidos. ¡Verifique!"
	  #define STR0024 "Inc.Exerc."
	  #define STR0025 "Presupuesto por ejercicio ya existente. ¿Desea modificarlo? "
	  #define STR0026 'Si'
	  #define STR0027 'No'
	  #define STR0028 "Presupuesto con valores"
	  #define STR0029 "Presupuesto sin valor informado"
	  #define STR0030 "Presupuesto vs. Ejercicio"
	  #define STR0031 "Ejercicio"
	  #define STR0032 "Incl.Ejerc."
	  #define STR0033 "¿Incl.Pres.Ejercicio?"
	  #define STR0034 "Nuevo Ejercicio"
	  #define STR0035 "Posicionado"
	  #define STR0036 "¿Que moneda    ?"
      #define STR0037 "Inclusion"
      #define STR0038 "Modificacion"
      #define STR0039 "Visualizacion"
      #define STR0040 "Borrado"
      #define STR0041 "Ejercicio sin valores definidos."
      #define STR0042 "Seleccione el ejercicio/la moneda existente." 
      #define STR0043 "De/A categoria debe ser informada."  
      #define STR0044 "Parâmetros" 
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Search"
      #define STR0002 "View"
      #define STR0003 "Insert"
      #define STR0004 "Edit"
      #define STR0005 "Delete"
      #define STR0006 "Caption"
      #define STR0007 "File of Budgets x Fiscal Year"
      #define STR0008 "This program allows the maintenance of File of Fiscal Year"
      #define STR0009 "File of Budget x Fiscal Year - Header"
      #define STR0010 "File of Budget x Fiscal Year - Items"
      #define STR0011 "Items"
      #define STR0012 "It is not possible to write a Budget per Fiscal year with no values."
      #define STR0013 "Enter at least one value per period."
      #define STR0014 "Fiscal year not registered."
      #define STR0015 "Enter the correct fiscal year - press <F3> to select."                  
      #define STR0016 "Non-existent financial category."
      #define STR0017 "Enter the correct financial category - press <F3> to select."
      #define STR0018 "The entered currency is not valid."
      #define STR0019 "Enter or select the correct currency."
      #define STR0020 "File of Budgets per Fiscal Year alredy existent."
      #define STR0021 "Check if the entered data as correct or use the option <Edit> ."
      #define STR0022 "Attention"
      #define STR0023 "Budget by fiscal year without defined values. Please, check!"
      #define STR0024 "Inc.Exerc."
      #define STR0025 "Budget by existing fiscal year. Modify? "
      #define STR0026 'Yes'
      #define STR0027 'No'
      #define STR0028 "Budget with values"
      #define STR0029 "Budget without a value entered"
      #define STR0030 "Budget vs. Fiscal Year"
      #define STR0031 "Fiscal Year"
      #define STR0032 "Incl.FY"
      #define STR0033 "Incl.FY Budget?"
      #define STR0034 "New fiscal year"
      #define STR0035 "Positioned"
      #define STR0036 "Which currency     ?"
      #define STR0037 "Inclusion"
      #define STR0038 "Modification"
      #define STR0039 "View"
      #define STR0040 "Deletion"
      #define STR0041 "Fiscal year without values defined."
      #define STR0042 "Select the existing fiscal year/currency."
      #define STR0043 "From/To category must be entered."
      #define STR0044 "Parâmetros"
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Legenda"
      #define STR0007 "Cadastro de Orcamentos x Exercicios"
      #define STR0008 "Este programa permite a manutencao do Cadastro de Exercicios"
      #define STR0009 "Cadastro de Orcamentos x Exercicios - Cabeçalho"
      #define STR0010 "Cadastro de Orcamentos x Exercicios - Itens"
      #define STR0011 "Orçamento x Exercicio"
      #define STR0012 "Não é possível gravar uma Orcamento por Exercicio sem valores."
      #define STR0013 "Digite pelo menos um valor por periodo."
      #define STR0014 "Exercicio não cadastrado."
      #define STR0015 "Digite o exercicio correto - utilize <F3> para selecionar."                  
      #define STR0016 "Categoria financeira não existente."
      #define STR0017 "Digite a categoria financeira correta - utilize <F3> para selecionar."
      #define STR0018 "A Moeda digitada não é válida."
      #define STR0019 "Digite ou selecione a moeda correta."
      #define STR0020 "Cadastro de Orcamentos por Exercicio já existente."
      #define STR0021 "Verifique se os dados digitados estão corretos ou utilize a opção <Alterar> ."
      #define STR0022 "Atenção"
      #define STR0023 "Orcamento por  exercicio sem valores definidos. Verifique!"
      #define STR0024 "Inc.Exerc."
      #define STR0025 "Orcamento por  exercicio ja existente. Deseja alterar ? "
      #define STR0026 'Sim'
      #define STR0027 'Nao'
      #define STR0028 "Orçamento com valores"
      #define STR0029 "Orçamento sem valor informado"
      #define STR0030 "Orçameto x Exercício"
      #define STR0031 "Exercicio"
      #define STR0032 "Incl.Exerc."
      #define STR0033 "Incl.Orc.Exercicio ?"
      #define STR0034 "Novo Exercicio"
      #define STR0035 "Posicionado"
      #define STR0036 "Qual moeda       ?"
      #define STR0037 "Inclusao"
      #define STR0038 "Alteracao"
      #define STR0039 "Visualizacao"
      #define STR0040 "Exclusao"
      #define STR0041 "Exercicio sem valores definidos."
      #define STR0042 "Escolha o exercicio/moeda existente."
      #define STR0043 "Categoria De/Ate deve ser informada."
      #define STR0044 "Parâmetros"
   #ENDIF
#ENDIF
