#IFDEF SPANISH
	#define STR0001 "Comissões"
	#define STR0002 "Manut. Comissões"
	#define STR0003 "Pesquisar"
	#define STR0004 "Visualizar"
	#define STR0005 "Incluir"
	#define STR0006 "Alterar"
	#define STR0007 "Excluir"
	#define STR0008 "Imprimir"
	#define STR0009 "Legenda"
	#define STR0010 "Gera Ctas a Pagar"
	#define STR0011 "Este programa tem como objetivo solicitar e atualizar" 
	#define STR0012 "a data para pagamento das comissões dos Vendedores."
	#define STR0013 "Gerar Contas a Pagar"	
	#define STR0014 "Confirma a Atual. Pag. de Comiss„o?"
	#define STR0015 "Atenção"	
	#define STR0016 "Número da Comissão Gerada:"
	#define STR0017 "Atenção!"
	#define STR0018 "Ok"
	#define STR0019 "Comissão não paga"
	#define STR0020 "Comissão paga " 
	#define STR0021 "Comissão gerada para Ctas. Pagar"
	#define STR0022 "Vendedor"
	#define STR0023 "Nr.Título"
	#define STR0024 "Parcela"
	#define STR0025 "Série"
	#define STR0026 "Dt.Comissão"
	#define STR0027 "Vlr.Base"
	#define STR0028 "% Vlr.Base"
	#define STR0029 "Comissão"
	#define STR0030 "Comissões Selecionadas"
	#define STR0031 "Valor Total:"
	#define STR0032 "As comissões resultantes desse filtro serão agrupadas em um único "       
	#define STR0033 "título que será posteriormente enviado para a área de contas a    " 
	#define STR0034 "pagar. O valor desse título será igual a soma das comissões	    " 
	#define STR0035 "selecionadas neste filtro. O código desse título será  	    " 
	#define STR0036 "automaticamente criado e poderá ser visualizado após a confirmação" 
	#define STR0037 "final desta operação.                                             " 
	#define STR0038 "Clique em parâmetros para filtrar os registros." 
	#define STR0039 "Aviso"                                                                                                                      
	#define STR0040 "Um ou mais campos não estão preenchidos corretamente ou a comissão foi gerada   para o contas a pagar."                     
	#define STR0041 "Verifique a data, vendedor e Codigo da  categoria."
	#define STR0042 "Data comissao De   ?"
	#define STR0043 "Data comissao Ate  ?"
	#define STR0044 "De Vendedor        ?"
	#define STR0045 "Dia do Pagamento   ?"
	#define STR0046 "Código da Categoria?"
	#define STR0047 "Não existem comissões a pagar com os parâmetros selecionados."
	#define STR0048 "¨A Persona         ?"
	#define STR0049 "Erro na exclusão/cancelamento da NF."
	#define STR0050 "Comissão do vendedor "
	#define STR0051 "já foi lançada no Contas a Pagar sob o número: "
	#define STR0052 "Data Emiss NF De   ?"
	#define STR0053 "Data Emiss NF Ate  ?"
	#define STR0054 "Categoria Sintética ou código da Categoria não compatível com o tipo de carteira do Contas a Pagar."
	#define STR0055 "Informar uma Catégoria Tipo de Carteira Despesas."
	#define STR0056 "Não poderá ser excluído o registro. Somente origem M='Manual'"
	#define STR0057 "Erro na exclusão da comissão!"
	#define STR0058 "Já existem baixas para a comissão!"
	#define STR0059 "Total das comissões igual a zero ou negativa."
	#define STR0060 "Verifique as comissoes selecionadas."
	#define STR0061 "Erro: "
	#define STR0062 "Solução: "
	#define STR0063 "Inconsistencia"
	#define STR0064 "Exclusão"
	#define STR0065 "Incluído"
	#define STR0066 "Estorno de Comissão"
	#define STR0067 "Comissão do vendedor"		
	#define STR0068 "Comissão sobre o cliente"		
	#define STR0069 "Comissão sobre o produto"
	#define STR0070 "Estorno de comissão"
	#define STR0071 "Comissão Manual"		
	#define STR0072 "Vendedor: "
	#define STR0073 "Tipo: "
	#define STR0074 "Valor: "
	#define STR0075 "Comssião Gerada na emissão"  
	#define STR0076 "Comssião Gerada na baixa"
	#define STR0077 "Codigo do produto: "
	#define STR0078 "Campo Motivo deve ser preenchido com     mais de 10 caracteres."
	#define STR0079 "Não é possível excluir uma comissão com título já gerado"
	#define STR0080 "Não é possível excluir uma comissão já paga"    
#ELSE
	#IFDEF ENGLISH
		#define STR0001 "Comissões"
		#define STR0002 "Manut. Comissões"
		#define STR0003 "Pesquisar"
		#define STR0004 "Visualizar"
		#define STR0005 "Incluir"
		#define STR0006 "Alterar"
		#define STR0007 "Excluir"
		#define STR0008 "Imprimir"
		#define STR0009 "Legenda"
		#define STR0010 "Gera Ctas a Pagar"
		#define STR0011 "Este programa tem como objetivo solicitar e atualizar" 
		#define STR0012 "a data para pagamento das comissões dos Vendedores."
		#define STR0013 "Gerar Contas a Pagar"	
		#define STR0014 "Confirma a Atual. Pag. de Comiss„o?"
		#define STR0015 "Atenção"	
		#define STR0016 "Número da Comissão Gerada:"
		#define STR0017 "Atenção!"
		#define STR0018 "Ok"
		#define STR0019 "Comissão não paga"
		#define STR0020 "Comissão paga " 
		#define STR0021 "Comissão gerada para Ctas. Pagar"
		#define STR0022 "Vendedor"
		#define STR0023 "Nr.Título"
		#define STR0024 "Parcela"
		#define STR0025 "Série"
		#define STR0026 "Dt.Comissão"
		#define STR0027 "Vlr.Base"
		#define STR0028 "% Vlr.Base"
		#define STR0029 "Comissão"
		#define STR0030 "Comissões Selecionadas"
		#define STR0031 "Valor Total:"
		#define STR0032 "As comissões resultantes desse filtro serão agrupadas em um único "       
		#define STR0033 "título que será posteriormente enviado para a área de contas a    " 
		#define STR0034 "pagar. O valor desse título será igual a soma das comissões	    " 
		#define STR0035 "selecionadas neste filtro. O código desse título será  	    " 
		#define STR0036 "automaticamente criado e poderá ser visualizado após a confirmação" 
		#define STR0037 "final desta operação.                                             " 
		#define STR0038 "Clique em parâmetros para filtrar os registros." 
		#define STR0039 "Aviso"                                                                                                                      
		#define STR0040 "Um ou mais campos não estão preenchidos corretamente ou a comissão foi gerada   para o contas a pagar."                     
		#define STR0041 "Verifique a data, vendedor e Codigo da  categoria."
		#define STR0042 "Data comissao De   ?"
		#define STR0043 "Data comissao Ate  ?"
		#define STR0044 "De Vendedor        ?"
		#define STR0045 "Dia do Pagamento   ?"
		#define STR0046 "Código da Categoria?"
		#define STR0047 "Não existem comissões a pagar com os parâmetros selecionados."
		#define STR0048 "To Person          ?"
		#define STR0049 "Erro na exclusão/cancelamento da NF."
		#define STR0050 "Comissão do vendedor "
		#define STR0051 "já foi lançada no Contas a Pagar sob o número: "
		#define STR0052 "Data Emiss NF De   ?"
		#define STR0053 "Data Emiss NF Ate  ?"
		#define STR0054 "Categoria Sintética ou código da Categoria não compatível com o tipo de carteira do Contas a Pagar."     
		#define STR0055 "Informar uma Catégoria Tipo de Carteira Despesas."
		#define STR0056 "Não poderá ser excluído o registro. Somente origem M='Manual'"
		#define STR0057 "Erro na exclusão da comissão!"
		#define STR0058 "Já existem baixas para a comissão!"
		#define STR0059 "Total das comissões igual a zero ou negativa."
		#define STR0060 "Verifique as comissoes selecionadas."
		#define STR0061 "Erro: "
		#define STR0062 "Solução: "
		#define STR0063 "Inconsistencia"
		#define STR0064 "Exclusão"
		#define STR0065 "Incluído"
		#define STR0066 "Estorno de Comissão"
		#define STR0067 "Comissão do vendedor"		
		#define STR0068 "Comissão sobre o cliente"		
		#define STR0069 "Comissão sobre o produto"
		#define STR0070 "Estorno de comissão"
		#define STR0071 "Comissão Manual"		
		#define STR0072 "Vendedor: "
		#define STR0073 "Tipo: "
		#define STR0074 "Valor: "
		#define STR0075 "Comssião Gerada na emissão"  
		#define STR0076 "Comssião Gerada na baixa"
		#define STR0077 "Codigo do produto: "
		#define STR0078 "Campo Motivo deve ser preenchido com     mais de 10 caracteres."
		#define STR0079 "Não é possível excluir uma comissão com título já gerado"
		#define STR0080 "Não é possível excluir uma comissão já paga"    
	#ELSE
		#define STR0001 "Comissões"
		#define STR0002 "Manut. Comissões"
		#define STR0003 "Pesquisar"
		#define STR0004 "Visualizar"
		#define STR0005 "Incluir"
		#define STR0006 "Alterar"
		#define STR0007 "Excluir"
		#define STR0008 "Imprimir"
		#define STR0009 "Legenda"
		#define STR0010 "Gera Ctas a Pagar"
		#define STR0011 "Este programa tem como objetivo solicitar e atualizar" 
		#define STR0012 "a data para pagamento das comissões dos Vendedores."
		#define STR0013 "Gerar Contas a Pagar"	
		#define STR0014 "Confirma a Atual. Pag. de Comiss„o?"
		#define STR0015 "Atenção"	
		#define STR0016 "Número da Comissão Gerada:"
		#define STR0017 "Atenção!"
		#define STR0018 "Ok"
		#define STR0019 "Comissão não paga"
		#define STR0020 "Comissão paga " 
		#define STR0021 "Comissão gerada para Ctas. Pagar"
		#define STR0022 "Vendedor"
		#define STR0023 "Nr.Título"
		#define STR0024 "Parcela"
		#define STR0025 "Série"
		#define STR0026 "Dt.Comissão"
		#define STR0027 "Vlr.Base"
		#define STR0028 "% Vlr.Base"
		#define STR0029 "Comissão"
		#define STR0030 "Comissões Selecionadas"
		#define STR0031 "Valor Total:"
		#define STR0032 "As comissões resultantes desse filtro serão agrupadas em um único "       
		#define STR0033 "título que será posteriormente enviado para a área de contas a    " 
		#define STR0034 "pagar. O valor desse título será igual a soma das comissões	    " 
		#define STR0035 "selecionadas neste filtro. O código desse título será  	    " 
		#define STR0036 "automaticamente criado e poderá ser visualizado após a confirmação" 
		#define STR0037 "final desta operação.                                             " 
		#define STR0038 "Clique em parâmetros para filtrar os registros." 
		#define STR0039 "Aviso"                                                                                                                      
		#define STR0040 "Um ou mais campos não estão preenchidos corretamente ou a comissão foi gerada   para o contas a pagar."                     
		#define STR0041 "Verifique a data, vendedor e Codigo da  categoria."
		#define STR0042 "Data comissao De   ?"
		#define STR0043 "Data comissao Ate  ?"
		#define STR0044 "De Vendedor        ?"
		#define STR0045 "Dia do Pagamento   ?"
		#define STR0046 "Código da Categoria?"
		#define STR0047 "Não existem comissões a pagar com os parâmetros selecionados."
		#define STR0048 "Ate Vendedor       ?"
		#define STR0049 "Erro na exclusão/cancelamento da NF."
		#define STR0050 "Comissão do vendedor "
		#define STR0051 "já foi lançada no Contas a Pagar sob o número: "
		#define STR0052 "Data Emiss NF De   ?"
		#define STR0053 "Data Emiss NF Ate  ?"
		#define STR0054 "Categoria Sintética ou código da Categoria não compatível com o tipo de carteira do Contas a Pagar."
		#define STR0055 "Informar uma Catégoria Tipo de Carteira Despesas."
		#define STR0056 "Não poderá ser excluído o registro. Somente origem M='Manual'"
		#define STR0057 "Erro na exclusão da comissão!"
		#define STR0058 "Já existem baixas para a comissão!"
		#define STR0059 "Total das comissões igual a zero ou negativa."
		#define STR0060 "Verifique as comissoes selecionadas."
		#define STR0061 "Erro: "
		#define STR0062 "Solução: "
		#define STR0063 "Inconsistencia"
		#define STR0064 "Exclusão"
		#define STR0065 "Incluído"
		#define STR0066 "Estorno de Comissão"
		#define STR0067 "Comissão do vendedor"		
		#define STR0068 "Comissão sobre o cliente"		
		#define STR0069 "Comissão sobre o produto"
		#define STR0070 "Estorno de comissão"
		#define STR0071 "Comissão Manual"		
		#define STR0072 "Vendedor: "
		#define STR0073 "Tipo: "
		#define STR0074 "Valor: "
		#define STR0075 "Comssião Gerada na emissão"  
		#define STR0076 "Comssião Gerada na baixa"    
		#define STR0077 "Codigo do produto: "
		#define STR0078 "Campo Motivo deve ser preenchido com     mais de 10 caracteres."
		#define STR0079 "Não é possível excluir uma comissão com título já gerado"
		#define STR0080 "Não é possível excluir uma comissão já paga"
	#ENDIF
#ENDIF
