#IFDEF SPANISH
	#define STR0001 "Buscar"
	#define STR0002 "Visualizar"
	#define STR0003 "Incluir"
	#define STR0004 "Modificar"
	#define STR0005 "Cancelar"
	#define STR0006 "Borrar Bajas"
	#define STR0007 "Borrar"
	#define STR0008 "Leyenda"
	#define STR0009 "Cuentas por Cobrar"
	#define STR0010 "Este programa permite el mantenimiento de Cuentas por Cobrar."
	#define STR0011 "Uno o algunos campos obligatorios no fueron llenados correctamente."
	#define STR0012 "Verifique si el codigo del banco fue informado correctamente."
	#define STR0013 "Verifique si la agencia del banco fue informada correctamente."
	#define STR0014 "Verifique si la cuenta del banco fue informada correctamente."
	#define STR0015 "Este ingreso ya finalizo o posee cancelacion parcial. Verifique la operacion."
	#define STR0016 'Anulacion del titulo'
	#define STR0017 "Categoria"
	#define STR0018 "Banco"
	#define STR0019 "Descripcion"
	#define STR0020 "Vencto."
	#define STR0021 "Vencto. Real"
	#define STR0022 "Valor"
	#define STR0023 "Valor Cobrado"
	#define STR0024 "Descuento"
	#define STR0025 "Interes/Multa"
	#define STR0026 "Fecha Pago"
	#define STR0027 "Cheque Nro."
	#define STR0028 "Historial"
	#define STR0029 "Valor de Movimiento"
	#define STR0030 "Anular"
	#define STR0031 "Lista de Anulaciones"
	#define STR0032 "Titulo pendiente"
	#define STR0033 "Anulado parcialmente"
	#define STR0034 "Titulo Anulado"
	#define STR0035 "Cuentas por Pagar"
	#define STR0036 "Visualizar"
	#define STR0037 "Borrar Baja"
	#define STR0038 "No es posible realizar la anulacion porque la moneda del banco y la del titulo son diferentes"
	#define STR0039 "Verifique si el banco fue seleccionado correctamente"
	#define STR0040 "Moneda: "
	#define STR0041 "La moneda del titulo y la del banco son diferentes. La anulacion se convertira para la moneda del banco."
	#define STR0042 "¿Confirma la anulacion del titulo?"
	#define STR0043 "No hay tasas de monedas registradas para el dia "
	#define STR0044 "Acceda al archivo de monedas e indique la tasa."
	#define STR0045 "Verifique si el codigo, sucursal y cuenta corriente del banco fueron informados correctamente."
	#define STR0046 "El Valor Pagado no puede ser menor o igual a cero."
	#define STR0047 "El Valor Pagado no pude ser superior ao valor do titulo."
	#define STR0048 "El Valor del descuento no puede ser superior al valor del titulo."
	#define STR0049 "Fecha de Pago no puede ser superior a la fecha base."
	#define STR0050 "Fecha de Pago invalida: "
	#define STR0051 ""
	#define STR0052 ""
	#define STR0053 ""
	#define STR0054 ""
	#define STR0055 ""
	#define STR0056 ""
	#define STR0057 ""
	#define STR0058 ""
	#define STR0059 ""
	#define STR0060 ""
	#define STR0061 ""
	#define STR0062 ""
	#define STR0063 ""
	#define STR0064 ""
	#define STR0065 ""
	#define STR0066 ""
	#define STR0067 ""
	#define STR0068 ""
	#define STR0069 ""
	#define STR0070 ""
	#define STR0071 ""
	#define STR0072 ""
	#define STR0073 ""
	#define STR0074 ""
	#define STR0075 ""
	#define STR0076 ""
	#define STR0077 ""
	#define STR0078 ""
	#define STR0079 ""
	#define STR0080 ""
	#define STR0081 ""
	#define STR0082 ""
	#define STR0083 ""
	#define STR0084 ""
	#define STR0085 ""
	#define STR0086 ""
	#define STR0087 ""
	#define STR0088 ""
	#define STR0089 ""
	#define STR0090 "Vlr. IRRF"
	#define STR0091 "Compensação"
	#define STR0092 "Estorno Comp."
	#define STR0093 "A data de vencimento e vencimento real não pode ser menor que a data de emissão."
	#define STR0094 "A taxa de juros ao dia nao pode ser maior que 2,00"
	#define STR0095 "Verifique o preenchimento do campo Taxa Juros."
	#define STR0096 "Digitar a quantidade de dias para Baixa."
	#define STR0097 "Nao devera haver valor no campo Dias Baixa, pois o Titulo esta configurado para nao Baixar."
	#define STR0098 "Verifique o preenchimento dos campos Dias Baixa e Baixa."
	#define STR0099 "Preencher a taxa de juros"
	#define STR0100 "A taxa de juros nao devera ser informada caso nao informado o Tipo de Juros."
	#define STR0101 "Verifique o preenchimento do campo Tipo Juros."
	#define STR0102 "Preencher a Data do Desconto"
	#define STR0103 "Verifique o preenchimento do campo Dta.Desconto."
	#define STR0104 "Por medida de segurança não será permitido a alteração de títulos ref. a adiantamento."
	#define STR0105 "Para alterar este título, deve-se excluí-lo e incluí-lo novamente."
	#define STR0106 "Nao é possível a exclusão de baixa deste título, pois o título possui CNAB gerado"
	#define STR0107 "Não é possível efetuar o estorno por esta rotina."
	#define STR0108 "Efetue o estorno do titulo pela rotina de Origem."
	#define STR0109 "Tipo informado invalido."
	#define STR0110 "Verifique o Tipo informado no Título."
	#define STR0111 "Ja existe RA para o titulo."
	#define STR0112 "Nao existe o titulo principal."
	#define STR0113 "Verifique a existencia do Titulo Principal."
	#define STR0114 "Nao pode ser gerado titulo de abatimento."
	#define STR0115 "Verifique o Titulo Principal."
	#define STR0116 "Titulo ja existente."
	#define STR0117 "Nao é possível a Compensacao, pois o título ja foi totalmente baixado."
	#define STR0118 "Nao é possível o Estorno da Compensacao, pois o título nao esta baixado."
	#define STR0119 "Este titulo está agregado a outro título portando não poderá ser maior que o titulo principal."
	#define STR0120 "Informe o titulo de abatimento MENOR ou IGUAL ao título principal."
	#define STR0121 "Ele já gerou lançamento financeiro      para pagamento de Comissão de Vendedor  no Contas a Pagar."
	#define STR0122 "Não existe moeda cadastrada"
	#define STR0123 "Executar o cadastro de moedas"
	#define STR0124 "Moeda cadastrada com valor ZERO"
	#define STR0125 "Atualizar o cadastro de moedas"
	#define STR0126 "Data de emissão em branco ou maior que a data de vencimento"
	#define STR0127 "Corrija o campo Emissão"
	#define STR0128 "Data de vencimento menor do que a data de emissão"
	#define STR0129 "Corrija o campo Vencimento"
	#define STR0130 "Data de vencimento real menor do que a data de emissão"
	#define STR0131 "Corrija o campo Vencto. Real"
	#define STR0132 "Cheques"
	#define STR0133 "Atualização de Cheques"
	#define STR0134 "Compensar"
	#define STR0135 "Liberar"
	#define STR0136 "Confirma a compensação do Documento: "
	#define STR0137 "Cheque Não Liberado"
	#define STR0138 "Cheque em Transito"
	#define STR0139 "Cheque Compensado"
	#define STR0140 "Cheque Avulso"
	#define STR0141 "Este título foi pago com cheque."
	#define STR0142 "Para baixar o título faça a baixa do cheque pela opção cheque do Contas a Receber."
	#define STR0143 "Cheque excluido em: "
	#define STR0144 "Alterar Obs."
	#define STR0145 "Deseja excluir o cheque: "
	#define STR0146 "Não é possivel a exclusão da baixa deste título pois o título foi pago com Cheque"
	#define STR0147 "Pela opção Cheques faça a exclusão do cheque, assim a baixa do título também será excluida"
	#define STR0148 "Transf. p/ Cob. Descontada"
	#define STR0149 "Titulo Renegociado"
	#define STR0150 "Titulo Baixado por Renegociação"
	#define STR0151 "Adiantamento com saldo"
	#define STR0152 "Título Transferido"
	#define STR0153 "Título transferido para Cobrança Descontada via Borderô"
	#define STR0154 "Cancele o Borderô ou disvincule o título."
	#define STR0155 "O Título já está em cobrança descontada"
	#define STR0156 "Para voltar para Em Aberto, exclua a baixa do Título"
	#define STR0157 "Parâmetros"
	#define STR0158 "Baixar simultâneo"
	#define STR0159 "Alterar rateio"
	#define STR0160 "Título gerado a partir de inclusão de nota fiscal, portanto nao pode ser excluido."
	#define STR0161 "Impr. Multiplos Boletos"
	#define STR0162 "Nao é possível a exclusão de baixa deste título, pois o título está vinculado a um comprovante de venda Rede."
	#define STR0163 "Título não possui rateio."
	#define STR0164 "Informe o rateio."
	#define STR0165 "Valores padrão"
	#define STR0166 "Já existem contas encerradas neste parcelamento"
	#define STR0167 "É preciso desfazer o pagamento das contas já encerradas para poder excluír este parcelamento"
	#define STR0168 "Títulos de parcelamento não podem ser excluídos"
	#define STR0169 "Se todas as parcelas estão em aberto, altere o cabeçalho, senão, renegocie"
	#define STR0170 "A soma do valor e desconto está maior que o saldo disponível"
	#define STR0171 "Não é possível alterar esse título"
	#define STR0172 "Títulos gerados com multiplas condições de pagamento não podem ser alterados"
#ELSE
	#IFDEF ENGLISH
		#define STR0001 "Search"
		#define STR0002 "View"
		#define STR0003 "Insert"
		#define STR0004 "Edit"
		#define STR0005 "Post"
		#define STR0006 "Del. Postings"
		#define STR0007 "Delete"
		#define STR0008 "Caption"
		#define STR0009 "Accounts Receivable"
		#define STR0010 "This program allows the maintenance of Accounts Receivable."
		#define STR0011 "One or more compulsory fields were not filled out correctly."
		#define STR0012 "Check if the bank code was correctly entered."
		#define STR0013 "Check if the bank agency was correctly entered."
		#define STR0014 "Check if the bank account was correctly eentered."
		#define STR0015 "This revenue was already finished or was partially posted. Check the operation."
		#define STR0016 'Bill Posting'
		#define STR0017 "Category"
		#define STR0018 "Bank"
		#define STR0019 "Descript."
		#define STR0020 "Due Dt."
		#define STR0021 "Real Due Dt."
		#define STR0022 "Value"
		#define STR0023 "Received Value"
		#define STR0024 "Discount"
		#define STR0025 "Inter./Fine"
		#define STR0026 "Paym. Date"
		#define STR0027 "Check  No."
		#define STR0028 "History  "
		#define STR0029 "Value of Movement "
		#define STR0030 "Cancel"
		#define STR0031 "List of Postings "
		#define STR0032 "Pending Bills   "
		#define STR0033 "Partially posted    "
		#define STR0034 "Bill posted   "
		#define STR0035 "Accounts Payab."
		#define STR0036 "View"
		#define STR0037 "Excluir Baixa"
		#define STR0038 "It not possible to execute the posting for the bank and the bill´s currency are diferent."
		#define STR0039 "Check if the bank was correctly entered."
		#define STR0040 "Curr.: "
		#define STR0041 "The bill and the bank´s currency are different. The posting will be converted to the bank´s currency."
		#define STR0042 "Confirm the bill posting?"
		#define STR0043 "The currencies´ rate are not registered for the day"
		#define STR0044 "Access the currencies´ file and choose the rate."
		#define STR0045 "Check if the bank code, branch and current account were entered correctly."
		#define STR0046 "The amount paid cannot be lower or equal to zero."
		#define STR0047 "The amount paid cannot be higher than the amount of the bill."
		#define STR0048 "The amount of the discount cannot be higher than the amount of the bill."
		#define STR0049 "Payment date cannot be higher than the base date."
		#define STR0050 "Invalid payment date: "
		#define STR0051 ""
		#define STR0052 ""
		#define STR0053 ""
		#define STR0054 ""
		#define STR0055 ""
		#define STR0056 ""
		#define STR0057 "Bordero"
		#define STR0058 ""
		#define STR0059 ""
		#define STR0060 ""
		#define STR0061 ""
		#define STR0062 ""
		#define STR0063 ""
		#define STR0064 ""
		#define STR0065 ""
		#define STR0066 ""
		#define STR0067 ""
		#define STR0068 ""
		#define STR0069 ""
		#define STR0070 ""
		#define STR0071 ""
		#define STR0072 ""
		#define STR0073 ""
		#define STR0074 ""
		#define STR0075 ""
		#define STR0076 ""
		#define STR0077 ""
		#define STR0078 ""
		#define STR0079 ""
		#define STR0080 ""
		#define STR0081 ""
		#define STR0082 ""
		#define STR0083 ""
		#define STR0084 ""
		#define STR0085 ""
		#define STR0086 ""
		#define STR0087 ""
		#define STR0088 ""
		#define STR0089 ""
		#define STR0090 "Vlr. IRRF"
		#define STR0091 "Compensação"
		#define STR0092 "Estorno Comp."
		#define STR0093 "A data de vencimento e vencimento real não pode ser menor que a data de emissão."
		#define STR0094 "A taxa de juros ao dia nao pode ser maior que 2,00"
		#define STR0095 "Verifique o preenchimento do campo Taxa Juros."
		#define STR0096 "Digitar a quantidade de dias para Baixa."
		#define STR0097 "Nao devera haver valor no campo Dias Baixa, pois o Titulo esta configurado para nao Baixar."
		#define STR0098 "Verifique o preenchimento dos campos Dias Baixa e Baixa."
		#define STR0099 "Preencher a taxa de juros"
		#define STR0100 "A taxa de juros nao devera ser informada caso nao informado o Tipo de Juros."
		#define STR0101 "Verifique o preenchimento do campo Tipo Juros."
		#define STR0102 "Preencher a Data do Desconto"
		#define STR0103 "Verifique o preenchimento do campo Dta.Desconto."
		#define STR0104 "Por medida de segurança não será permitido a alteração de títulos ref. a adiantamento."
		#define STR0105 "Para alterar este título, deve-se excluí-lo e incluí-lo novamente."
		#define STR0106 "Nao é possível a exclusão de baixa deste título, pois o título possui CNAB gerado"
		#define STR0107 "Não é possível efetuar o estorno por esta rotina."
		#define STR0108 "Efetue o estorno do titulo pela rotina de Origem."
		#define STR0109 "Tipo informado invalido."
		#define STR0110 "Verifique o Tipo informado no Título."
		#define STR0111 "Ja existe RA para o titulo."
		#define STR0112 "Nao existe o titulo principal."
		#define STR0113 "Verifique a existencia do Titulo Principal."
		#define STR0114 "Nao pode ser gerado titulo de abatimento."
		#define STR0115 "Verifique o Titulo Principal."
		#define STR0116 "Titulo ja existente."
		#define STR0117 "Nao é possível a Compensacao, pois o título ja foi totalmente baixado."
		#define STR0118 "Nao é possível o Estorno da Compensacao, pois o título nao esta baixado."
		#define STR0119 "Este titulo está agregado a outro título portando não poderá ser maior que o titulo principal."
		#define STR0120 "Informe o titulo de abatimento MENOR ou IGUAL ao título principal."
		#define STR0121 "Ele já gerou lançamento financeiro      para pagamento de Comissão de Vendedor  no Contas a Pagar."
		#define STR0122 "Não existe moeda cadastrada"
		#define STR0123 "Executar o cadastro de moedas"
		#define STR0124 "Moeda cadastrada com valor ZERO"
		#define STR0125 "Atualizar o cadastro de moedas"
		#define STR0126 "Data de emissão em branco ou maior que a data de vencimento"
		#define STR0127 "Corrija o campo Emissão"
		#define STR0128 "Data de vencimento menor do que a data de emissão"
		#define STR0129 "Corrija o campo Vencimento"
		#define STR0130 "Data de vencimento real menor do que a data de emissão"
		#define STR0131 "Corrija o campo Vencto. Real"
		#define STR0132 "Cheques"
		#define STR0133 "Atualização de Cheques"
		#define STR0134 "Compensar"
		#define STR0135 "Liberar"
		#define STR0136 "Confirma a compensação do Documento: "
		#define STR0137 "Cheque Não Liberado"
		#define STR0138 "Cheque em Transito"
		#define STR0139 "Cheque Compensado"
		#define STR0140 "Cheque Avulso"
		#define STR0141 "Este título foi pago com cheque."
		#define STR0142 "Para baixar o título faça a baixa do cheque pela opção cheque do Contas a Receber."
		#define STR0143 "Cheque excluido em: "
		#define STR0144 "Alterar Obs."
		#define STR0145 "Deseja excluir o cheque: "
		#define STR0146 "Não é possivel a exclusão da baixa deste título pois o título foi pago com Cheque"
		#define STR0147 "Pela opção Cheques faça a exclusão do cheque, assim a baixa do título também será excluida"
		#define STR0148 "Transf. p/ Cob. Descontada"
		#define STR0149 "Titulo Renegociado"
		#define STR0150 "Titulo Baixado por Renegociação"
		#define STR0151 "Adiantamento com saldo"
		#define STR0152 "Título Transferido"
		#define STR0153 "Título transferido para Cobrança Descontada via Borderô"
		#define STR0154 "Cancele o Borderô ou disvincule o título."
		#define STR0155 "O Título já está em cobrança descontada"
		#define STR0156 "Para voltar para Em Aberto, exclua a baixa do Título"
		#define STR0157 "Parâmetros"
		#define STR0158 "Baixar simultâneo"
		#define STR0159 "Alterar rateio"
		#define STR0160 "Título gerado a partir de inclusão de nota fiscal, portanto nao pode ser excluido."
		#define STR0161 "Impr. Multiplos Boletos"
		#define STR0162 "Nao é possível a exclusão de baixa deste título, pois o título está vinculado a um comprovante de venda Rede."
		#define STR0163 "Título não possui rateio."
		#define STR0164 "Informe o rateio."
		#define STR0165 "Valores padrão"
		#define STR0166 "Já existem contas encerradas neste parcelamento"
		#define STR0167 "É preciso desfazer o pagamento das contas já encerradas para poder excluír este parcelamento"
		#define STR0168 "Títulos de parcelamento não podem ser excluídos"
		#define STR0169 "Se todas as parcelas estão em aberto, altere o cabeçalho, senão, renegocie"
		#define STR0170 "A soma do valor e desconto está maior que o saldo disponível"
		#define STR0171 "Não é possível alterar esse título"
		#define STR0172 "Títulos gerados com multiplas condições de pagamento não podem ser alterados"
	#ELSE
		#define STR0001 "Pesquisar"
		#define STR0002 "Visualizar"
		#define STR0003 "Incluir"
		#define STR0004 "Alterar"
		#define STR0005 "Baixar"
		#define STR0006 "Excl.Baixas"
		#define STR0007 "Excluir"
		#define STR0008 "Legenda"
		#define STR0009 "Contas a Receber"
		#define STR0010 "Este programa permite a manutenção de Contas a Receber."
		#define STR0011 "Um ou alguns campos obrigatorios nao foram preenchidos corretamente."
		#define STR0012 "Verifique se o codigo do banco foi informado corretamente."
		#define STR0013 "Verifique se a agencia do banco foi informada corretamente."
		#define STR0014 "Verifique se a conta do banco foi informada corretamente."
		#define STR0015 "Esta receita ja foi encerrada ou possui baixa parcial. Verifique a operação."
		#define STR0016 'Baixa do Titulo'
		#define STR0017 "Categoria"
		#define STR0018 "Banco"
		#define STR0019 "Descricao"
		#define STR0020 "Vencto."
		#define STR0021 "Vencto. Real"
		#define STR0022 "Valor"
		#define STR0023 "Valor Recebido"
		#define STR0024 "Desconto"
		#define STR0025 "Juros/Multa"
		#define STR0026 "Data Pgto."
		#define STR0027 "Cheque No."
		#define STR0028 "Histórico"
		#define STR0029 "Valor do Movimento"
		#define STR0030 "Cancelar"
		#define STR0031 "Relacao de Baixas"
		#define STR0032 "Titulo em aberto"
		#define STR0033 "Baixado parcialmente"
		#define STR0034 "Titulo Baixado"
		#define STR0035 "Contas a Pagar"
		#define STR0036 "Visualizar"
		#define STR0037 "Excluir Baixa"
		#define STR0038 "Nao é possivel realizar a baixa porque a moeda do banco e a do titulo sao diferentes"
		#define STR0039 "Verifique se o banco foi selecionado corretamente"
		#define STR0040 "Moeda: "
		#define STR0041 "A moeda do titulo e a do banco sao diferentes. A baixa sera convertida para a moeda do banco."
		#define STR0042 "Confirma a baixa do titulo?"
		#define STR0043 "As taxas das moedas nao estao cadastradas para o dia "
		#define STR0044 "Acesse o cadastro de moedas e indique a taxa."
		#define STR0045 "Verifique se o codigo, agencia e conta corrente do banco foram informados corretamente."
		#define STR0046 "O Valor Pago não pode ser menor ou igual a zero."
		#define STR0047 "O Valor Pago não pode ser superior ao valor do titulo."
		#define STR0048 "O Valor do desconto não pode ser superior ao valor do título."
		#define STR0049 "Data de Pagamento não pode ser superior a database."
		#define STR0050 "Data de Pagamento inválida: "
		#define STR0051 "Imprimir"
		#define STR0052 "Exclusão de baixa"
		#define STR0053 "Não é possível excluir a baixa desse    registro."
		#define STR0054 "Ele provavelmente encontra-se           parcialmente ou totalmente baixado na   área de contas a pagar."
		#define STR0055 "Abatimento"
		#define STR0056 "Impr.Boleto"
		#define STR0057 "Bordero"
		#define STR0058 "Um ou alguns campos obrigatorios para Geracao do CNAB nao foram preenchidos."
		#define STR0059 "Verifique se o campo Nosso Numero foi informado corretamente."
		#define STR0060 "Verifique se o campo Local de Impressao foi informado corretamente."
		#define STR0061 "Verifique se o campo Carteira foi informado corretamente."
		#define STR0062 "Verifique se o campo Especie foi informado corretamente."
		#define STR0063 "Verifique se o campo Baixa foi informado corretamente."
		#define STR0064 "Verifique se o campo Protesto foi informado corretamente."
		#define STR0065 "Nao e possivel alterar esse registro, pois o mesmo encontra-se com: Bordero gerado, Bodero enviado ao banco, Bordero pendente ou Bordero encerrado"
		#define STR0066 "Nao e possivel baixar esse registro, pois o mesmo encontra-se com: Bordero gerado, Bodero enviado ao banco, Bordero pendente, Bordero rejeitado ou Bordero encerrado"
		#define STR0067 "A mensagem digitada no campo Msg. Recibo excedeu as 22 linhas permitidas. Ajuste sua mensagem de acordo com a informação abaixo."
		#define STR0068 "Mensagens do campo Msg. Recibo que ultrapassarem 100 caracteres por linha terão quebra de linha automatica de acordo com o último espaço em branco para que a   ultima palavra não seja cortada."
		#define STR0069 "A mensagem digitada no campo Msg. Ficha excedeu as 3 linhas permitidas. Ajuste  sua mensagem de acordo com a informação abaixo."
		#define STR0070 "Mensagens do campo Msg. Ficha que ultra-passarem 40 caracteres por linha terão  quebra de linha automatica de acordo com o último espaço em branco para que a    ultima palavra não seja cortada."
		#define STR0071 "Inconsistência na escolha de parâmetros"
		#define STR0072 "Sendo um título enviado por CNAB e a impressão do boleto no CLIENTE, a carteira não pode ser SIMPLES SEM REGISTRO"
		#define STR0073 "Deseja confirmar o cancelamento da baixa ?"
		#define STR0074 "O valor do desconto está incorreto."
		#define STR0075 "O desconto deverá ser menor ou igual ao valor do título a Receber."
		#define STR0076 "Inclui Rateio"
		#define STR0077 "Rateio"
		#define STR0078 "Renegociar"
		#define STR0079 "Escolha o Tipo de Renegociação"
		#define STR0080 "Tipo de Renegociação"
		#define STR0081 "Lançamento Posicionado: "
		#define STR0082 "Renegociação Múltipla"
		#define STR0083 "Cancelar"
		#define STR0084 "OK"
		#define STR0085 "ATENÇÃO"
		#define STR0086 "Esse lançamento financeiro é proveniente de renegociação. "
		#define STR0087 "Todas as parcelas relativas a essa renegociação também serão excluídas. "
		#define STR0088 "Os lançamentos que originaram essa renegociação serão reabertos."
		#define STR0089 "&Ok"
		#define STR0090 "Vlr. IRRF"
		#define STR0091 "Compensação"
		#define STR0092 "Estorno Comp."
		#define STR0093 "A data de vencimento e vencimento real não pode ser menor que a data de emissão."
		#define STR0094 "A taxa de juros ao dia nao pode ser maior que 2,00"
		#define STR0095 "Verifique o preenchimento do campo Taxa Juros."
		#define STR0096 "Digitar a quantidade de dias para Baixa."
		#define STR0097 "Nao devera haver valor no campo Dias Baixa, pois o Titulo esta configurado para nao Baixar."
		#define STR0098 "Verifique o preenchimento dos campos Dias Baixa e Baixa."
		#define STR0099 "Preencher a taxa de juros"
		#define STR0100 "A taxa de juros nao devera ser informada caso nao informado o Tipo de Juros."
		#define STR0101 "Verifique o preenchimento do campo Tipo Juros."
		#define STR0102 "Preencher a Data do Desconto"
		#define STR0103 "Verifique o preenchimento do campo Dta.Desconto."
		#define STR0104 "Por medida de segurança não será permitido a alteração de títulos ref. a adiantamento."
		#define STR0105 "Para alterar este título, deve-se excluí-lo e incluí-lo novamente."
		#define STR0106 "Nao é possível a exclusão de baixa deste título, pois o título possui CNAB gerado"
		#define STR0107 "Não é possível efetuar o estorno por esta rotina."
		#define STR0108 "Efetue o estorno do titulo pela rotina de Origem."
		#define STR0109 "Tipo informado invalido."
		#define STR0110 "Verifique o Tipo informado no Título."
		#define STR0111 "Ja existe RA para o titulo."
		#define STR0112 "Nao existe o titulo principal."
		#define STR0113 "Verifique a existencia do Titulo Principal."
		#define STR0114 "Nao pode ser gerado titulo de abatimento."
		#define STR0115 "Verifique o Titulo Principal."
		#define STR0116 "Titulo ja existente."
		#define STR0117 "Nao é possível a Compensacao, pois o título ja foi totalmente baixado."
		#define STR0118 "Nao é possível o Estorno da Compensacao, pois o título nao esta baixado."
		#define STR0119 "Este titulo está agregado a outro título portando não poderá ser maior que o titulo principal."
		#define STR0120 "Informe o titulo de abatimento MENOR ou IGUAL ao título principal."
		#define STR0121 "Ele já gerou lançamento financeiro      para pagamento de Comissão de Vendedor  no Contas a Pagar."
		#define STR0122 "Não existe moeda cadastrada"
		#define STR0123 "Executar o cadastro de moedas"
		#define STR0124 "Moeda cadastrada com valor ZERO"
		#define STR0125 "Atualizar o cadastro de moedas"
		#define STR0126 "Data de emissão em branco ou maior que a data de vencimento"
		#define STR0127 "Corrija o campo Emissão"
		#define STR0128 "Data de vencimento menor do que a data de emissão"
		#define STR0129 "Corrija o campo Vencimento"
		#define STR0130 "Data de vencimento real menor do que a data de emissão"
		#define STR0131 "Corrija o campo Vencto. Real"
		#define STR0132 "Cheques"
		#define STR0133 "Atualização de Cheques"
		#define STR0134 "Compensar"
		#define STR0135 "Liberar"
		#define STR0136 "Confirma a compensação do Documento: "
		#define STR0137 "Cheque Não Liberado"
		#define STR0138 "Cheque em Transito"
		#define STR0139 "Cheque Compensado"
		#define STR0140 "Cheque Avulso"
		#define STR0141 "Este título foi pago com cheque, portanto o cheque deve ser compensado antes de ser efetuada a baixa do título."
		#define STR0142 "Para baixar o título faça a compensação do cheque pela opção Cheques no Contas a Receber."
		#define STR0143 "Cheque excluido em: "
		#define STR0144 "Alterar Obs."
		#define STR0145 "Deseja excluir o cheque: "
		#define STR0146 "Não é possivel a exclusão da baixa deste título pois o título foi pago com Cheque"
		#define STR0147 "Pela opção Cheques faça a exclusão do cheque, assim a baixa do título também será excluida"
		#define STR0148 "Transf. p/ Cob. Descontada"
		#define STR0149 "Titulo Renegociado"
		#define STR0150 "Titulo Baixado por Renegociação"
		#define STR0151 "Adiantamento com saldo"
		#define STR0152 "Título Transferido"
		#define STR0153 "Título transferido para Cobrança Descontada via Borderô"
		#define STR0154 "Cancele o Borderô ou disvincule o título."
		#define STR0155 "O Título já está em cobrança descontada"
		#define STR0156 "Para voltar para Em Aberto, exclua a baixa do Título"
		#define STR0157 "Parâmetros"
		#define STR0158 "Baixar simultâneo"
		#define STR0159 "Alterar rateio"
		#define STR0160 "Título gerado a partir de inclusão de nota fiscal, portanto nao pode ser excluido."
		#define STR0161 "Impr. Multiplos Boletos"
		#define STR0162 "Nao é possível a exclusão de baixa deste título, pois o título está vinculado a um comprovante de venda Rede."
		#define STR0163 "Título não possui rateio."
		#define STR0164 "Informe o rateio."
		#define STR0165 "Valores padrão"
		#define STR0166 "Já existem contas encerradas neste parcelamento"
		#define STR0167 "É preciso desfazer o pagamento das contas já encerradas para poder excluír este parcelamento"
		#define STR0168 "Títulos de parcelamento não podem ser excluídos"
		#define STR0169 "Se todas as parcelas estão em aberto, altere o cabeçalho, senão, renegocie"
		#define STR0170 "A soma do valor e desconto está maior que o saldo disponível"
		#define STR0171 "Não é possível alterar esse título"
		#define STR0172 "Títulos gerados com multiplas condições de pagamento não podem ser alterados"
	#ENDIF
#ENDIF
