#ifdef SPANISH
	#define STR0001 "Genera Cotizacion"
	#define STR0002 "bUscar"
	#define STR0003 "Genera Cotizacion"
	#define STR0004 "Genera Cotizacion"
	#define STR0005 "Solicitudes"
	#define STR0006 "Seleccionando Registros..."
	#define STR0007 "Aleatorio"
	#define STR0008 " Sucursal+Parametro"
	#define STR0009 "bUscar"
	#define STR0010 " Item por Localizar "
	#define STR0011 "Confirmar"
	#define STR0012 "Salir"
	#define STR0013 "Selecciona Nuevamente"
	#define STR0014 "Proveedor"
	#define STR0015 "Tienda"
	#define STR0016 "Nombre del Proveedor "
	#define STR0017 "Criterio"
	#define STR0018 "Cantidad"
	#define STR0019 "Fecha Validez"
	#define STR0020 "C.Costo"
	#define STR0021 "Cuenta Contb"
	#define STR0022 "Seleccion de Proveedores"
	#define STR0023 "¿Confirma Seleccion de Proveedores?"
	#define STR0024 "Atencion"
	#define STR0025 "Visualizar"
	#define STR0026 "Inclusion Manual"
	#define STR0027 "Producto: "
	#define STR0028 "Ultima provision en: "
	#define STR0029 "Los items de las SC's a seguir no generan cotaciones, ya que el registro del producto esta definido un Proveedor Canal. Verifique el campo Forn. Canal (B1_MONO).SC's=>"
	#define STR0030 "OK"
	#define STR0031 "Las solicitudes de compras que no generaron cotizaciones no tienen vinculo Producto/Grupo vs Proveedor. Verifique el archivo de vinculo."
	#define STR0032 "Leyenda"
	#define STR0033 "Solicitud con Cotizacion Generada"
	#define STR0034 "Cotizacion no Generada"
	#define STR0035 "Control de Generacion de Cotizaciones por Sucursal"
	#define STR0036 "Actualizar"
	#define STR0037 "Solicitud pendiente"
	#define STR0038 "Solicitud totalmente atendida"
	#define STR0039 "Solicitud parcialmente atendida"
	#define STR0040 "Solicitud en proceso de cotizacion"
	#define STR0041 "Borr. por Residuo"
	#define STR0042 "Solicitud bloqueada"	
	#define STR0043 "Solicitud de producto importado"
	#define STR0044 "Solicitud rechazada"
	#define STR0045 "Integracion Modulo Gestion de Contratos"
    #define STR0046 "Solicitação"
    #define STR0047 "Produto"
    #define STR0048 "Descrição"
    #define STR0049 "Solicitações"
    #define STR0050 "Não existem registros com o filtro informado"
    #define STR0051 "Verifique os parâmetros da rotina"
    #define STR0052 "Pessoa não é um fornecedor"
    #define STR0053 "Informe um Fornecedor"
    #define STR0054 "Fornecedor inexistente"
    #define STR0055 "Informe um Fornecedor válido"
    #define STR0056 "Fornecedor já informado na tela"
    #define STR0057 "INCLUSÃO DE FORNECEDOR MANUAL"
    #define STR0058 "Atenção"
    #define STR0059 "Nome do Fornecedor"
    #define STR0060 "Critério"
    #define STR0061 "Seleção dos Fornecedores"
    #define STR0062 "Solicitacao Compra"
    #define STR0063 "O campo Fornecedor (A5_FORNECE) não foi preenchido"
    #define STR0064 "Não existe registro relacionado ao código de Fornecedor"
    #define STR0065 "Já existe uma linha com esse Fornecedor"
    #define STR0066 "Vídeo de Treinamento"
#else
	#ifdef ENGLISH
		#define STR0001 "Requisitions"
		#define STR0002 "Search   "
		#define STR0003 "Gener.Quote"
		#define STR0004 "Gener.Quote"
		#define STR0005 "Orders"
		#define STR0006 "Selecting Records..."
		#define STR0007 "Random"
		#define STR0008 " Branch+Parameter"
		#define STR0009 "Search  "
		#define STR0010 "Item to Find"
		#define STR0011 "OK  "
		#define STR0012 "Quit"
		#define STR0013 "Select Again"
		#define STR0014 "Supplier"
		#define STR0015 "Branch"
		#define STR0016 "Supplier Name"
		#define STR0017 "Criteria"
		#define STR0018 "Quantity"
		#define STR0019 "Validity Date"
		#define STR0020 "Cost Center"
		#define STR0021 "Account"
		#define STR0022 "Selection of Suppliers"
		#define STR0023 "Confirm Selection of Suppliers?"
		#define STR0024 "Attention"
		#define STR0025 "View"
		#define STR0026 "Manual Insert "
		#define STR0027 "Product: "
		#define STR0028 "Last Supply at : "
		#define STR0029 "The items in following Scs dont generate quotations as no product file is defined in Supplier Channel, Verify the field Forn. Canal (B1_MONO). SC's => "
		#define STR0030 "OK"
		#define STR0031 "Purchase requests do not generate quotations, they do not have a binding Product/Grou vs. Supplier. Check the binding file. "
		#define STR0032 "Caption"
		#define STR0033 "Request with Quotation Generated"
		#define STR0034 "Request withhout Quotation Generated"
		#define STR0035 "Quotation Generation Control per Branch   "
		#define STR0036 "Update "
		#define STR0037 "Pending request "
		#define STR0038 "Fully attended request "
		#define STR0039 "Partially attended request"
		#define STR0040 "Request in quotation process "
		#define STR0041 "Elim. by Residue"
		#define STR0042 "Request blocked "	
		#define STR0043 "Request for imported product "
		#define STR0044 "Request rejected "
		#define STR0045 "Contract Management Module integration"
        #define STR0046 "Solicitação"
        #define STR0047 "Produto"
        #define STR0048 "Descrição"
        #define STR0049 "Solicitações"
		#define STR0050 "Não existem registros com o filtro informado"
		#define STR0051 "Verifique os parâmetros da rotina"
		#define STR0052 "Pessoa não é um fornecedor"
		#define STR0053 "Informe um Fornecedor"
		#define STR0054 "Fornecedor inexistente"
		#define STR0055 "Informe um Fornecedor válido"
		#define STR0056 "Fornecedor já informado na tela"
		#define STR0057 "INCLUSÃO DE FORNECEDOR MANUAL"
		#define STR0058 "Atenção"
        #define STR0059 "Nome do Fornecedor"
        #define STR0060 "Critério"
        #define STR0061 "Seleção dos Fornecedores"
        #define STR0062 "Solicitacao Compra"
        #define STR0063 "O campo Fornecedor (A5_FORNECE) não foi preenchido"
    	 #define STR0064 "Não existe registro relacionado ao código de Fornecedor"
    	 #define STR0065 "Já existe uma linha com esse Fornecedor"
    	 #define STR0066 "Vídeo de Treinamento"
	#else
		#define STR0001 "Solicitaçöes"
		#define STR0002 "Pesquisar"
		#define STR0003 "Gera Cotacao"
		#define STR0004 "Gerar Cotaçao"
		#define STR0005 "Solicitaçoes"
		#define STR0006 "Selecionando Registros..."
		#define STR0007 "Aleatorio"
		#define STR0008 " Filial+Parametro"
		#define STR0009 "Pesquisa"
		#define STR0010 " Item a Localizar "
		#define STR0011 "Confirma"
		#define STR0012 "Abandona"
		#define STR0013 "Seleciona Novamente"
		#define STR0014 "Fornecedor"
		#define STR0015 "Loja"
		#define STR0016 "Nome do Fornecedor "
		#define STR0017 "Criterio"
		#define STR0018 "Quantidade"
		#define STR0019 "Data Valid."
		#define STR0020 "C.Custo"
		#define STR0021 "Conta Contab"
		#define STR0022 "Seleçäo dos Fornecedores"
		#define STR0023 "Confirma Seleçäo dos Fornecedores ?"
		#define STR0024 "Atençäo"
		#define STR0025 "Visualiza"
		#define STR0026 "Inclusao Manual"
		#define STR0027 "Produto: "
		#define STR0028 "Ultimo fornecimento em : "
		#define STR0029 "Os itens das SC's a seguir não geraram cotações, pois no cadastro do produto está definido um Fornecedor Canal. Verifique o campo Forn. Canal (B1_MONO). SC's => "
		#define STR0030 "OK"
		#define STR0031 "As solicitações de compras que não geraram cotações, não possuem amarração Produto/Grupo X Fornecedor. Verifique o cadastro de amarração."
		#define STR0032 "Legenda"
		#define STR0033 "Solicitação com Cotação Gerada"
		#define STR0034 "Solicitação sem Cotação Gerada"
		#define STR0035 "Controle de Geracao de Cotacoes por Filial"
		#define STR0036 "Atualizar"
		#define STR0037 "Solicitacao Pendente"
		#define STR0038 "Solicitacao Totalmente Atendida"
		#define STR0039 "Solicitacao Parcialmente Atendida"
		#define STR0040 "Solicitacao em Processo de Cotacao"
		#define STR0041 "Elim. por Residuo"
		#define STR0042 "Solicitacäo Bloqueada"	
		#define STR0043 "Solicitação de produto Importado"
		#define STR0044 "Solicitacäo Rejeitada"
		#define STR0045 "Integração Modulo Gestão de Contratos"
        #define STR0046 "Solicitação"
        #define STR0047 "Produto"
        #define STR0048 "Descrição"
        #define STR0049 "Solicitações"
        #define STR0050 "Não existem registros com o filtro informado"
        #define STR0051 "Verifique os parâmetros da rotina"
        #define STR0052 "Pessoa não é um fornecedor"
        #define STR0053 "Informe um Fornecedor"
        #define STR0054 "Fornecedor inexistente"
        #define STR0055 "Informe um Fornecedor válido"
        #define STR0056 "Fornecedor já informado na tela"
        #define STR0057 "INCLUSÃO DE FORNECEDOR MANUAL"
        #define STR0058 "Atenção"
        #define STR0059 "Nome do Fornecedor"
        #define STR0060 "Critério"
        #define STR0061 "Seleção dos Fornecedores"
        #define STR0062 "Solicitacao Compra"
        #define STR0063 "O campo Fornecedor (A5_FORNECE) não foi preenchido"
    	 #define STR0064 "Não existe registro relacionado ao código de Fornecedor"
    	 #define STR0065 "Já existe uma linha com esse Fornecedor"
    	 #define STR0066 "Vídeo de Treinamento"
	#endif
#endif
