#IFDEF SPANISH
   #define STR0001 "Buscar"
   #define STR0002 "Visualizar"
   #define STR0003 "Incluir"
   #define STR0004 "Modificar"
   #define STR0005 "Borrar"
   #define STR0006 "Leyenda"
   #define STR0007 "Totales"
   #define STR0008 "Valor de la Mercaderia"
   #define STR0009 "Total "
   #define STR0010 "Remito de Entrada"
   #define STR0011 "Este programa permite el mantenimiento del "
   #define STR0012 " - Encabezamiento"
   #define STR0013 " - Items"
   #define STR0014 "Remito de Entrada"
   #define STR0015 "Seleccione Pedido de Compra..."
   #define STR0016 "Seleccione el Pedido de Compra"
   #define STR0017 "Numero"
   #define STR0018 "Item"
   #define STR0019 "Saldo"
   #define STR0020 "Fc.Entrega"
   #define STR0021 "Producto"
   #define STR0022 "Descripcion"
   #define STR0023 "Valor Unit."
   #define STR0024 "Emision"
   #define STR0025 "Deposito"
   #define STR0026 "No existen pedidos en abierto para este Proveedor/Producto"
   #define STR0027 "Esta opcion solo puede utilizarse en los Documentos de Entrada Tipo Fact Normal"
   #define STR0028 "No se llenaron correctamente los campos obligatorios del encabezamiento."
   #define STR0029 "Verifique los campos obligatorios del encabezamiento."
   #define STR0030 "Fact.Normal"
   #define STR0031 "Fact.Devolucion"
   #define STR0032 "F.Complementaria"
   #define STR0033 "Remito"
   #define STR0034 "Documentos de Entrada"
   #define STR0035 "Este item del pedido de compra ya no posee saldo."
   #define STR0036 "Verifique el saldo del pedido informado."
   #define STR0037 " de Entrada"   
   #define STR0038 " de Devolucion"      
   #define STR0039 "El(la) "
   #define STR0040 " no puede modificarse o borrarse porque ya fue facturado(a)."
   #define STR0041 "No es posible grabar un(a) "
   #define STR0042 " sin items."   
   #define STR0043 "Para efectuar la transaccion, por lo menos seleccione un producto."      
   #define STR0044 "Num. Pedido"
   #define STR0045 "Proveedor"
   #define STR0046 "Nombre"
   #define STR0047 "Fc. Emision"
   #define STR0048 "Generacion de itens del(la) "
   #define STR0049 "¡Espere! Generando items del(la) "
   #define STR0050 "Verifique los datos del encabezamiento"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Search"
      #define STR0002 "View"
      #define STR0003 "Insert"
      #define STR0004 "Edit"
      #define STR0005 "Delete"
      #define STR0006 "Caption"
      #define STR0007 "Totals"
      #define STR0008 "Good´s Value"
      #define STR0009 "Invoice Total"
      #define STR0010 "Remito de Entrada"
      #define STR0011 "This program is used for maintenance "
      #define STR0012 " - Header"
      #define STR0013 " - Items"
      #define STR0014 "Remito de Entrada"
      #define STR0015 "Select Purchase Order..."
      #define STR0016 "Select the Purchase Order"
      #define STR0017 "Number"
      #define STR0018 "Item"
      #define STR0019 "Balance"
      #define STR0020 "Deliv.Dt."
      #define STR0021 "Product"
      #define STR0022 "Description"
      #define STR0023 "Unit Value"
      #define STR0024 "Issue Dt."
      #define STR0025 "Warehouse"
   	  #define STR0026 "There are no open orders for this Supplier/Product"
      #define STR0027 "This option can only be used for `Normal Invoice´ type Inflow Documents "
      #define STR0028 "The header´s mandatory fields have not been correctly entered."
      #define STR0029 "Please check the header´s mandatory fields."
      #define STR0030 "Normal Inv."
      #define STR0031 "Return Inv."
      #define STR0032 "Complement Inv."
      #define STR0033 "Remito"
      #define STR0034 "Inflow Documents"
      #define STR0035 "The balance of this item of the purchase order is zeroed."
      #define STR0036 "Please check the balance of the order entered."
      #define STR0037 " - Inflow"         
      #define STR0038 " - Return"      
      #define STR0039 ""
      #define STR0040 " cannot be modified nor deleted. It has been already invoiced."
      #define STR0041 "It´s not possible to write a "
      #define STR0042 " w/o items."   
      #define STR0043 "Select at least one product to execute the transaction."            
      #define STR0044 "Order No."
      #define STR0045 "Supplier"
      #define STR0046 "Name"
      #define STR0047 "Issue Date"
      #define STR0048 "Items generation of    "
      #define STR0049 "Wait! Generating items of "
      #define STR0050 "Check the header data"
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Legenda"
      #define STR0007 "Totais"
      #define STR0008 "Valor da Mercadoria"
      #define STR0009 "Total da Nota"
      #define STR0010 "Remito de Entrada"
      #define STR0011 "Este programa permite a manutencao do "
      #define STR0012 " - Cabecalho"
      #define STR0013 " - Itens"
      #define STR0014 "Remito de Entrada"
      #define STR0015 "Selecionar Pedido de Compra..."
      #define STR0016 "Selecione o Pedido de Compra"
      #define STR0017 "Numero"
      #define STR0018 "Item"
      #define STR0019 "Saldo"
      #define STR0020 "Dt.Entrega"
      #define STR0021 "Produto"
      #define STR0022 "Descricao"
      #define STR0023 "Valor Unit."
      #define STR0024 "Emissao"
      #define STR0025 "Armazém"
      #define STR0026 "Nao existem pedidos em aberto para este Fornecedor/Produto"
      #define STR0027 "Esta opcao so podera ser utilizada nos Documentos de Entrada Tipo NF Normal"
      #define STR0028 "Os campos obrigatorios do cabecalho nao estao preenchidos corretamente."
      #define STR0029 "Verifique os campos obrigatorios do cabecalho."
      #define STR0030 "NF.Normal"
      #define STR0031 "NF.Devolucao"
      #define STR0032 "NF.Complemento"
      #define STR0033 "Remito"
      #define STR0034 "Documentos de Entrada"
      #define STR0035 "Este item do pedido de compra nao possui mais saldo."
      #define STR0036 "Verifique o saldo do pedido informado."
      #define STR0037 " de Entrada"         
      #define STR0038 " de Devolucao"            
      #define STR0039 "O(A) "
      #define STR0040 " nao pode ser alterado(a) ou excluido(a) porque ja foi faturado(a)."
      #define STR0041 "Não é possível gravar um(a) "
      #define STR0042 " sem itens."   
      #define STR0043 "Selecione pelo menos um produto para efetuar a transação."                  
      #define STR0044 "Num. Pedido"
      #define STR0045 "Fornecedor"
      #define STR0046 "Nome"
      #define STR0047 "Dt. Emissao"
      #define STR0048 "Geracao de itens do(a) "
      #define STR0049 "Aguarde! Gerando itens do(a) "
      #define STR0050 "Verifique os dados do cabecalho"
   #ENDIF
#ENDIF
