#IFDEF SPANISH
      #define STR0001 "Buscar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Modificar"
      #define STR0005 "Borrar"
      #define STR0006 "Aplicar Tabla"
      #define STR0007 "Cambiar Estatus"
      #define STR0008 "Leyenda"
      #define STR0009 "Formacion de Precios de Venta"
      #define STR0010 "Estructura"
      #define STR0011 "Impuestos/Otros Gastos"
      #define STR0012 "Costos Indirectos"
      #define STR0013 "Margen de Ganancia"
      #define STR0014 "Simulacion Precio Venta"
      #define STR0015 "Cambiar Estatus de la Formacion"
      #define STR0016 "No es posible grabar, pues la Guia Estructura o Margen Estan sin itemes."
      #define STR0017 "Digite algun valor en la guia Margen."
      #define STR0018 "En Formacion"
      #define STR0019 "Simulado"
      #define STR0020 "Precio Aplicado a la Tabla"
      #define STR0021 "Nuevo estatus no fue definido."
      #define STR0022 "Abandonando la operacion."
      #define STR0023 "Formacion de Precios no puede ser modificada o borrada."
      #define STR0024 "Si es necesario modificar estatus - Abandonando la operacion."
      #define STR0025 "Precios de venta no pueden ser aplicados, pues esta en formacion."
      #define STR0026 "Precios de venta previamente aplicados."
      #define STR0027 "Simula PV"
      #define STR0028 "Modifica Estatus"
      #define STR0029 "Este Producto "
      #define STR0030 "No Tiene Estructura"
      #define STR0031 "Total General "
      #define STR0032 "Calc com Fator?"
      #define STR0033 "Custo Adicional alterado"
      #define STR0034 "Salve a formação de preço antes de simular o preço"
      #define STR0035 "Calculo da Margem? "
      #define STR0036 "Parâmetros"
      #define STR0037 "Produto de"
      #define STR0038 "Produto até"
      #define STR0039 "Alterar Status Simultâneo"
      #define STR0040 "Status?"
      #define STR0041 "Simula PV Simultâneo"
      #define STR0042 "Produtos para alterar status"
      #define STR0043 "Produtos para Simular PV"
      #define STR0044 "O filtro informado não retorna nenhum produto."
      #define STR0045 "Altere os parâmetros"
      #define STR0046 "Aplicar tabela Simultâneo"
      #define STR0047 "Deseja aplicar preço na tabela"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "Search"
      #define STR0002 "View"
      #define STR0003 "Insert"
      #define STR0004 "Edit"
      #define STR0005 "Delete"
      #define STR0006 "Aplicar Tabela"
      #define STR0007 "Mudar Status"
      #define STR0008 "Caption"
      #define STR0009 "Formação de Preços de Venda"
      #define STR0010 "Estrutura"
      #define STR0011 "Impostos/Outras Despesas"
      #define STR0012 "Custos Indiretos"
      #define STR0013 "Margem de Lucro"
      #define STR0014 "Simulação Preço Venda"
      #define STR0015 "Mudar Status da Formação"
      #define STR0016 "Não é possível gravar, pois a Guia Estrutura ou Margem Estão sem itens."
      #define STR0017 "Digite algum valor na guia Margem."
      #define STR0018 "Em Formação"
      #define STR0019 "Simulado"
      #define STR0020 "Preço Aplicado á Tabela"
      #define STR0021 "Novo status não foi definido."
      #define STR0022 "Abandonando a operação."
      #define STR0023 "Formação de Preços não pode ser alterada ou excluida."
      #define STR0024 "Se necessário alterar status - Abandonando a operação."
      #define STR0025 "Preços de venda não pode ser aplicado, pois está em formação."
      #define STR0026 "Preços de venda previamente aplicado."
      #define STR0027 "Simulate PV"
      #define STR0028 "Edit Status"
      #define STR0029 "This Product "
      #define STR0030 "Does not have Structure"
      #define STR0031 "Grand Total "
      #define STR0032 "Calc com Fator?"
      #define STR0033 "Custo Adicional alterado"
      #define STR0034 "Salve a formação de preço antes de simular o preço"
      #define STR0035 "Calculo da Margem?"
      #define STR0036 "Parâmetros"
      #define STR0037 "Produto de"
      #define STR0038 "Produto até"
      #define STR0039 "Alterar Status Simultâneo"
      #define STR0040 "Status?"
      #define STR0041 "Simula PV Simultâneo"
      #define STR0042 "Produtos para alterar status"
      #define STR0043 "Produtos para Simular PV"
      #define STR0044 "O filtro informado não retorna nenhum produto."
      #define STR0045 "Altere os parâmetros"
      #define STR0046 "Aplicar tabela Simultâneo"
      #define STR0047 "Deseja aplicar preço na tabela"
   #ELSE
      #define STR0001 "Pesquisar"
      #define STR0002 "Visualizar"
      #define STR0003 "Incluir"
      #define STR0004 "Alterar"
      #define STR0005 "Excluir"
      #define STR0006 "Aplicar Tabela"
      #define STR0007 "Mudar Status"
      #define STR0008 "Legenda"
      #define STR0009 "Formação de Preços de Venda"
      #define STR0010 "Estrutura"
      #define STR0011 "Impostos/Outras Despesas"
      #define STR0012 "Custos Indiretos"
      #define STR0013 "Margem de Lucro"
      #define STR0014 "Simulação Preço Venda"
      #define STR0015 "Mudar Status da Formação"
      #define STR0016 "Não é possível gravar, pois a Guia Estrutura ou Margem Estão sem itens."
      #define STR0017 "Digite algum valor na guia Margem."
      #define STR0018 "Em Formação"
      #define STR0019 "Simulado"
      #define STR0020 "Preço Aplicado à Tabela"
      #define STR0021 "Novo status não foi definido."
      #define STR0022 "Abandonando a operação."
      #define STR0023 "Formação de Preços não pode ser alterada ou excluida."
      #define STR0024 "Se necessário alterar status - Abandonando a operação."
      #define STR0025 "Preços de venda não pode ser aplicado, pois está em formação."
      #define STR0026 "Preços de venda previamente aplicado."
      #define STR0027 "Simula PV"
      #define STR0028 "Alt. Status"
      #define STR0029 "Este Produto "
      #define STR0030 "Não Possui Estrutura"
      #define STR0031 "Total Geral "
      #define STR0032 "Calc com Fator?"
      #define STR0033 "Custo Adicional alterado"
      #define STR0034 "Salve a formação de preço antes de simular o preço"
      #define STR0035 "Calculo da Margem?"
      #define STR0036 "Parâmetros"
      #define STR0037 "Produto de"
      #define STR0038 "Produto até"
      #define STR0039 "Alterar Status Simultâneo"
      #define STR0040 "Status?"
      #define STR0041 "Simula PV Simultâneo"
      #define STR0042 "Produtos para alterar status"
      #define STR0043 "Produtos para Simular PV"
      #define STR0044 "O filtro informado não retorna nenhum produto."
      #define STR0045 "Altere os parâmetros"
      #define STR0046 "Aplicar tabela Simultâneo"
      #define STR0047 "Deseja aplicar preço na tabela"
   #ENDIF
#ENDIF