#IFDEF SPANISH
	#define STR0001 "Explosão"
	#define STR0002 "Pesquisar"
	#define STR0003 "Visualizar"
	#define STR0004 "Incluir"
	#define STR0005 "Alterar"
	#define STR0006 "Excluir"
	#define STR0007 "Produto Acabado"
	#define STR0008 "Produtos Comprados"
	#define STR0009 "Produtos Fabricados"
	#define STR0010 "Considera OP em Proc."
	#define STR0011 "Considera estoque"
	#define STR0012 "Gera SC. aut."
	#define STR0013 "Gerar SC"
	#define STR0014 "Gerar OP"
	#define STR0015 "Pendente"
	#define STR0016 "Cancelada"
	#define STR0017 "OP Gerada"
	#define STR0018 "Essa explosão esta cancelada e não poderá gerar Solicitação de Compras."
	#define STR0019 "Inclua uma nova explosão."
	#define STR0020 "Essa explosão ja gerou Ordem de Produção."
	#define STR0021 "Essa explosão ja gerou Solicitação de   Compras."
	#define STR0022 "Não é possível cancelar esta Explosão."
	#define STR0023 "Explosão já cancelada."
	#define STR0024 "Explosão já gerou Ordem de Produção."
	#define STR0025 "Explosão já gerou Solicitação de Compras."
	#define STR0026 "Cancelar"
	#define STR0027 "Inclusão da OP"
	#define STR0028 "Incluir"
	#define STR0029 "Imprimir"
	#define STR0030 "Quantidade a Fabricar"
	#define STR0031 "Esta Explosão não está mais pendente"
	#define STR0032 "Esta operação não é permitida"
	#define STR0033 "Existem SCs já utilizadas com os produtos desta Explosão"
	#define STR0034 "Existem SCs pendentes que serão excluídas junto com esta Explosão, deseja continuar assim mesmo?"
	#define STR0035 "A Operação não foi confirmada"  
	#define STR0036 "Confirme a Operação"
	#define STR0037 "Deseja Realmente Cancelar esta Explosão?"
	#define STR0038 "Explosão "
	#define STR0039 " Cancelada"
	#define STR0040 "Existem SCs pendentes que serão geradas novamente com a alteração desta Explosão, deseja continuar assim mesmo?"
	#define STR0041 "Nenhuma solicitação foi gerada."
	#define STR0042 "Para essa Explosão não é necessário efetuar nenhuma compra."
	#define STR0043 "Produto controla Lote."
	#define STR0044 "Altere a explosão e informe um Lote para o produto acabado."
	#define STR0045 "Data de validade deve ser maior que a data de fabricação"
	#define STR0046 "Corrija as datas."
	#define STR0047 "Campos de datas de Fabricação e Validade não foram preenchidos corretamente."
	#define STR0048 "Preencha corretamente os campos."
	#define STR0049 "Parâmetros"
	#define STR0050 "Gerar SC Mult."
	#define STR0051 "Gerar OP Mult."
	#define STR0052 "OP Criada"
	#define STR0053 "OP número: "
	#define STR0054 " foi criada."
	#define STR0055 "Solicitação de Compras ja gerada para essa explosão."
	#define STR0056 "Exclua a solicitação antes de excluir a explosão."
	#define STR0057 "Exclua a solicitação antes de alterar a explosão."
	#define STR0058 "Uma ou mais produções estão com o número de dias igual a zero, deseja gerar a OP mesmo assim?"
	#define STR0059 "Dias para produção."
	#define STR0060 "SC Gerada"
	#define STR0061 "Vídeo de Treinamento"
	#define STR0062 "Produto não tem estrutura cadastrada."
	#define STR0063 "Crie uma estrutura para o produto selecionado."
	#define STR0064 "Saldos em Estoque:"
#ELSE
	#IFDEF ENGLISH
		#define STR0001 "Explosão"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 "Produto Acabado"
		#define STR0008 "Produtos Comprados"
		#define STR0009 "Produtos Fabricados"
		#define STR0010 "Considera OP em Proc."
		#define STR0011 "Considera estoque"
		#define STR0012 "Gera SC. aut."
		#define STR0013 "Gerar SC"
		#define STR0014 "Gerar OP"
		#define STR0015 "Pendente"
		#define STR0016 "Cancelada"
		#define STR0017 "OP Gerada"
		#define STR0018 "Essa explosão esta cancelada e não poderá gerar Solicitação de Compras."
		#define STR0019 "Inclua uma nova explosão."
		#define STR0020 "Essa explosão ja gerou Ordem de Produção."
		#define STR0021 "Essa explosão ja gerou Solicitação de   Compras."
		#define STR0022 "Não é possível cancelar esta Explosão."
		#define STR0023 "Explosão já cancelada."
		#define STR0024 "Explosão já gerou Ordem de Produção."
		#define STR0025 "Explosão já gerou Solicitação de Compras."
		#define STR0026 "Cancelar"
		#define STR0027 "Inclusão da OP"
		#define STR0028 "Incluir"
		#define STR0029 "Imprimir"
		#define STR0030 "Quantidade a Fabricar"
		#define STR0031 "Esta Explosão não está mais pendente"
		#define STR0032 "Esta operação não é permitida"
		#define STR0033 "Existem SCs já utilizadas com os produtos desta Explosão"
		#define STR0034 "Existem SCs pendentes que serão excluídas junto com esta Explosão, deseja continuar assim mesmo?"
		#define STR0035 "A Operação não foi confirmada"  
		#define STR0036 "Confirme a Operação"
		#define STR0037 "Deseja Realmente Cancelar esta Explosão?"
		#define STR0038 "Explosão "
		#define STR0039 " Cancelada"
		#define STR0040 "Existem SCs pendentes que serão geradas novamente com a alteração desta Explosão, deseja continuar assim mesmo?"
		#define STR0041 "Nenhuma solicitação foi gerada."
		#define STR0042 "Para essa Explosão não é necessário efetuar nenhuma compra."
		#define STR0043 "Produto controla Lote."
		#define STR0044 "Altere a explosão e informe um Lote para o produto acabado."
		#define STR0045 "Data de validade deve ser maior que a data de fabricação"
		#define STR0046 "Corrija as datas."
		#define STR0047 "Campos de datas de Fabricação e Validade não foram preenchidos corretamente."
		#define STR0048 "Preencha corretamente os campos."
		#define STR0049 "Parâmetros"
		#define STR0050 "Gerar SC Mult."
		#define STR0051 "Gerar OP Mult."
		#define STR0052 "OP Criada"
		#define STR0053 "OP número: "
		#define STR0054 " foi criada."
		#define STR0055 "Solicitação de Compras ja gerada para essa explosão."
		#define STR0056 "Exclua a solicitação antes de excluir a explosão."
		#define STR0057 "Exclua a solicitação antes de alterar a explosão."
		#define STR0058 "Uma ou mais produções estão com o número de dias igual a zero, deseja gerar a OP mesmo assim?"
		#define STR0059 "Dias para produção."
		#define STR0060 "SC Gerada"
		#define STR0061 "Vídeo de Treinamento"
		#define STR0062 "Produto não tem estrutura cadastrada."
		#define STR0063 "Crie uma estrutura para o produto selecionado."
		#define STR0064 "Saldos em Estoque:"
	#ELSE
		#define STR0001 "Explosão"
		#define STR0002 "Pesquisar"
		#define STR0003 "Visualizar"
		#define STR0004 "Incluir"
		#define STR0005 "Alterar"
		#define STR0006 "Excluir"
		#define STR0007 "Produto Acabado"
		#define STR0008 "Produtos Comprados"
		#define STR0009 "Produtos Fabricados"
		#define STR0010 "Considera OP em Proc."
		#define STR0011 "Considera estoque"
		#define STR0012 "Gera SC. aut."
		#define STR0013 "Gerar SC"
		#define STR0014 "Gerar OP"
		#define STR0015 "Pendente"
		#define STR0016 "Cancelada"
		#define STR0017 "OP Gerada"
		#define STR0018 "Essa explosão esta cancelada e não poderá gerar Solicitação de Compras."
		#define STR0019 "Inclua uma nova explosão."
		#define STR0020 "Essa explosão ja gerou Ordem de Produção."
		#define STR0021 "Essa explosão ja gerou Solicitação de   Compras."
		#define STR0022 "Não é possível cancelar esta Explosão."
		#define STR0023 "Explosão já cancelada."
		#define STR0024 "Explosão já gerou Ordem de Produção."
		#define STR0025 "Explosão já gerou Solicitação de Compras."
		#define STR0026 "Cancelar"
		#define STR0027 "Inclusão da OP"
		#define STR0028 "Incluir"
		#define STR0029 "Imprimir"
		#define STR0030 "Quantidade a Fabricar"
		#define STR0031 "Esta Explosão não está mais pendente"
		#define STR0032 "Esta operação não é permitida"
		#define STR0033 "Existem SCs já utilizadas com os produtos desta Explosão"
		#define STR0034 "Existem SCs pendentes que serão excluídas junto com esta Explosão, deseja continuar assim mesmo?"
		#define STR0035 "A Operação não foi confirmada"  
		#define STR0036 "Confirme a Operação"
		#define STR0037 "Deseja Realmente Cancelar esta Explosão?"
		#define STR0038 "Explosão "
		#define STR0039 " Cancelada"
		#define STR0040 "Existem SCs pendentes que serão geradas novamente com a alteração desta Explosão, deseja continuar assim mesmo?"
		#define STR0041 "Nenhuma solicitação foi gerada."
		#define STR0042 "Para essa Explosão não é necessário efetuar nenhuma compra."
		#define STR0043 "Produto controla Lote."
		#define STR0044 "Altere a explosão e informe um Lote para o produto acabado."
		#define STR0045 "Data de validade deve ser maior que a data de fabricação"
		#define STR0046 "Corrija as datas."
		#define STR0047 "Campos de datas de Fabricação e Validade não foram preenchidos corretamente."
		#define STR0048 "Preencha corretamente os campos."
		#define STR0049 "Parâmetros"
		#define STR0050 "Gerar SC Mult."
		#define STR0051 "Gerar OP Mult."
		#define STR0052 "OP Criada"
		#define STR0053 "OP número: "
		#define STR0054 " foi criada."
		#define STR0055 "Solicitação de Compras ja gerada para essa explosão."
		#define STR0056 "Exclua a solicitação antes de excluir a explosão."
		#define STR0057 "Exclua a solicitação antes de alterar a explosão."
		#define STR0058 "Uma ou mais produções estão com o número de dias igual a zero, deseja gerar a OP mesmo assim?"
		#define STR0059 "Dias para produção."
		#define STR0060 "SC Gerada"
		#define STR0061 "Vídeo de Treinamento"
		#define STR0062 "Produto não tem estrutura cadastrada."
		#define STR0063 "Crie uma estrutura para o produto selecionado."
		#define STR0064 "Saldos em Estoque:"
	#ENDIF  
#ENDIF