#ifdef SPANISH
	#define STR0001 "Importacion de Factura Electronica"
	#define STR0002 "Atencion"
	#define STR0003 "Rellene correctamente las informaciones solicitadas."
	#define STR0004 "Esta rutina importara el archivo de retorno puesto a disposicion por la   "
	#define STR0005 "Alcaldia Municipal de Sao Paulo, con las informaciones sobre las facturas  "
	#define STR0006 "electronicas generadas en el periodo."
	#define STR0007 "Asistente de parametrizacion"
	#define STR0008 "Informaciones sobre el archivo de retorno: "
	#define STR0009 "Archivo de retorno: "
	#define STR0010 "Nombre de archivo:"
	#define STR0011 "Archivo de importacion no ubicado"
	#define STR0012 "No se ubico en el directorio "
	#define STR0013 "el archivo "
	#define STR0014 " indicado en las preguntas "
	#define STR0015 "de la rutina."
	#define STR0016 "Informe correctamente el directorio y nombre del archivo "
	#define STR0017 "y procese la rutina nuevamente.  "
	#define STR0018 "Implementacion no efectuada"
	#define STR0019 "La implementacion del proceso de la Factura"
	#define STR0020 "Electronica no se efectuo correctamente, "
	#define STR0021 "pues existen tablas y campos que "
	#define STR0022 "no estan a disposicion en el diccionario de datos."
	#define STR0023 "Verifique la documentacion que acompana la rutina, "
	#define STR0024 "ejecute todos los procedimientos indicados y genere "
	#define STR0025 "nuevamente esta rutina."
	#define STR0026 "Tabla SFT  - "
	#define STR0027 " Campos: "
	#define STR0028 "Importacion no realizada"	
	#define STR0029 "No se efectuo la importacion del archivo de retorno  "
	#define STR0030 "por que no existen informaciones de retorno en el archivo "
	#define STR0031 "texto informado. "
	#define STR0032 "Verifique si el archivo de retorno informado en las"
	#define STR0033 "preguntas de la rutina es el enviado por la alcaldia "
	#define STR0034 "y procese nuevamente esta rotina."
	#define STR0035 "RPS no ubicada en la(s) tabla(s):"
	#define STR0036 "ISS en el arch.de retorno diverge del grabado en las facturas."
	#define STR0037 "Numero RPS"
	#define STR0038 "Serie"
	#define STR0039 "No pudo efectuarse la grabacion, intente nuevamente."
	#define STR0040 "Impresion de la lista para cotejo - Fact-e"
	#define STR0041 "Este programa imprimira una lista para cotejar el resultado "
	#define STR0042 "de la importacion de la factura electronica, mostrando los documentos"
	#define STR0043 "importados y posibles errores en la importacion."
	#define STR0044 "A Rayas"
	#define STR0045 "Administracion"
	#define STR0046 "Informe de cotejo de importacion de la Factura Electronica - Sao Paulo "
	#define STR0047 "Numero RPS  Serie  Cliente  Tda.  Factura-e       Valor ISS  Estatus    Mensaje de Error"
	#define STR0048 "Importado"
	#define STR0049 "Error"
	#define STR0050 "ISS en el arch.de retorno diverge de lo grabado en las facturas."
	#define STR0051 "Informe de verificacion de importacion de la Factura Electronica - Sao Paulo "
	#define STR0052 "Este programa imprimira una lista con el resultado de la importacion de retorno de la Factura Electronica "
	#define STR0053 "Cliente"
	#define STR0054 "Tienda"
	#define STR0055 "Fact-e"
	#define STR0056 "Valor ISS"
	#define STR0057 "Estatus"
	#define STR0058 "Mensaje de Error"
	#define STR0059 "Total de documentos importados sin error:"
	#define STR0060 "Total de documentos no importados:       "
	#define STR0061 "Total de documentos importados sin error"
	#define STR0062 "Total de documentos no importados       "
	#define STR0063 "No se encontro el encabezado (SF2) del documento para la sucursal: "
	#define STR0064 ", RPS: "
	#define STR0065 " y serie: "
	#define STR0066 ". Verifique si el archivo se esta importando en la sucursal correcta."
	#define STR0067 "ISS en el arch. de retorno: "
	#define STR0068 " diverge de lo grabado en las facturas: "
	#define STR0069 "Alicuota en el archivo de retorno: "
	#define STR0070 " diverge de la grabada en las facturas: "
	#define STR0071 "El codigo de ISS grabado en el libro fiscal (SF3): "
	#define STR0072 " diverge del archivo de retorno: "
	#define STR0073 "Libro fiscal (SF3) no ubicado. Verifique si el codigo de ISS y/o cliente de la Fact-e corresponden al RPS."
#else
	#ifdef ENGLISH
		#define STR0001 "Import of Electronic Invoice"
		#define STR0002 "Attention"
		#define STR0003 "Properly enter the information required."
		#define STR0004 "This routine imports the return file available by        "
		#define STR0005 "São Paulo Municipal Local Government, with information on electronic invoices     "
		#define STR0006 "generated in the period."
		#define STR0007 "Parameterization wizard"
		#define STR0008 "Information on return file: "
		#define STR0009 "Return file: "
		#define STR0010 "File name: "
		#define STR0011 "Import file not located"	
		#define STR0012 "Not found in the directory "
		#define STR0013 " the file "
		#define STR0014 " indicated in questions "
		#define STR0015 "of routine."
		#define STR0016 "Properly enter the file directory and name "
		#define STR0017 "and process the routine again."
		#define STR0018 "Implementation not performed"
		#define STR0019 "Implementation of Electroni Invoice "
		#define STR0020 "was not properly performed, "
		#define STR0021 "since there are tables and fields that "
		#define STR0022 "are not available in data dictionary."
		#define STR0023 "Check the documentation following the routine and "
		#define STR0024 "run all procedures indicated and process "
		#define STR0025 "this routine again."
		#define STR0026 "SFT Table - "
		#define STR0027 " Fields: "
		#define STR0028 "Import not performed"	
		#define STR0029 "Import of return file was not performed "
		#define STR0030 "since there was no return information in text "
		#define STR0031 "texto informado. "
		#define STR0032 "Check if files indicated in "
		#define STR0033 "routine questions is the one sent by local government "
		#define STR0034 "and process this routine again."
		#define STR0035 "RPS not found in table(s): "
		#define STR0036 "ISS in return file is different from the one saved in invoices."
		#define STR0037 "RPS Number"
		#define STR0038 "Series"
		#define STR0039 "It was unable to save it, try it again."
		#define STR0040 "Printing of Conference relation - NF-e"
		#define STR0041 "This program generates a conference relation with the result "
		#define STR0042 "of Electronic Invoice import, displaying all documents "
		#define STR0043 "imported and possible import errors."
		#define STR0044 "Z.form"
		#define STR0045 "Administration"
		#define STR0046 "Import conference report of Electronic Invoice - São Paulo"
		#define STR0047 "RPS Number  Series  Customer  Store  e-inv         Value ISS  Status    Error Message"
		#define STR0048 "Imported"
		#define STR0049 "Error"
		#define STR0050 "ISS in return file is different from the one saved in invoices."
		#define STR0051 "Import conference report of Electronic Invoice - São Paulo"
		#define STR0052 "This program displays a relation with import results of Electronic Invoice return"
		#define STR0053 "Customer"
		#define STR0054 "Store"
		#define STR0055 "e-Inv."
		#define STR0056 "ISS Value"
		#define STR0057 "Status"
		#define STR0058 "Error Message"
		#define STR0059 "Total of imported documents without errors: "
		#define STR0060 "Total of documents not imported:      "
		#define STR0061 "Total of documents imported without errors "
		#define STR0062 "Total of not imported documents      "
		#define STR0063 "No document header (SF2) for branch:                             "
		#define STR0064 ", RPS: "
		#define STR0065 " and series: "
		#define STR0066 ". Check if the file is beint imported in the right branch. "
		#define STR0067 "ISS in return file:     "
		#define STR0068 " differs from that saved in invoices:  "
		#define STR0069 "Tax rate in return file: "
		#define STR0070 " differs from that saved in invoices:  "
		#define STR0071 "The ISS code saved in the tax record (SF3): "
		#define STR0072 " differs from the return file:  "
		#define STR0073 "Tax record (SF3) not found. Please, check if ISS code and/or customer of NF-e correspond to RPS."
	#else
		#define STR0001 "Importação da Nota Fiscal Eletrônica"
		#define STR0002 "Atencäo"
		#define STR0003 "Preencha corretamente as informacöes solicitadas."
		#define STR0004 "Esta rotina ira importar o arquivo de retorno disponibilizado pela        "
		#define STR0005 "Prefeitura Municipal de São Paulo, contendo informações sobre as notas     "
		#define STR0006 "fiscais eletrônicas geradas no período."
		#define STR0007 "Assistente de parametrizacäo"
		#define STR0008 "Informações sobre o arquivo de retorno: "
		#define STR0009 "Arquivo de retorno: "
		#define STR0010 "Nome do arquivo: "
		#define STR0011 "Arquivo de importação não localizado"	
		#define STR0012 "Não foi localizado no diretório "
		#define STR0013 " o arquivo "
		#define STR0014 " indicado nas perguntas "
		#define STR0015 "da rotina."
		#define STR0016 "Informe o diretório e o nome do arquivo "
		#define STR0017 "corretamente e processe a rotina novamente."
		#define STR0018 "Implementação não efetuada"
		#define STR0019 "A implementação do processo da Nota "
		#define STR0020 "Fiscal Eletrônica não foi efetuada corretamente, "
		#define STR0021 "visto que existem tabelas e campos que "
		#define STR0022 "não estão disponíveis no dicionário de dados."
		#define STR0023 "Verifique a documentação que acompanha a rotina e "
		#define STR0024 "execute todos os procedimentos indicados e processe "
		#define STR0025 "esta rotina novamente."
		#define STR0026 "Tabela SFT - "
		#define STR0027 " Campos: "
		#define STR0028 "Importação não realizada"	
		#define STR0029 "A importação do arquivo de retorno não foi realizada "
		#define STR0030 "por não existirem informações de retorno no arquivo "
		#define STR0031 "texto informado. "
		#define STR0032 "Verifique se o arquivo de retorno informado nas "
		#define STR0033 "perguntas da rotina é o enviado pela prefeitura "
		#define STR0034 "e processe esta rotina novamente."
		#define STR0035 "RPS não localizado na(s) tabela(s): "
		#define STR0036 "ISS no arq. de retorno diverge do gravado nas notas fiscais."
		#define STR0037 "Número RPS"
		#define STR0038 "Série"
		#define STR0039 "Não foi possível efetuar a gravação, tente novamente."
		#define STR0040 "Impressão da listagem de conferência - NF-e"
		#define STR0041 "Este programa ira emitir uma listagem de conferência com o resultado "
		#define STR0042 "da importação da Nota Fiscal Eletrônica, apresentando os documentos "
		#define STR0043 "importados e possíveis erros na importação."
		#define STR0044 "Zebrado"
		#define STR0045 "Administracao"
		#define STR0046 "Relatório de conferância de importação da Nota Fiscal Eletr}onica - São Paulo"
		#define STR0047 "Número RPS  Série  Cliente  Loja  NF-e            Valor ISS  Status     Mensagem de Erro"
		#define STR0048 "Importado"
		#define STR0049 "Erro"
		#define STR0050 "ISS no arq. de retorno diverge do gravado nas notas fiscais."
		#define STR0051 "Relatório de conferência de importação da Nota Fiscal Eletrônica - São Paulo"
		#define STR0052 "Este programa irá apresentar uma listagem com o resultado da importação do retorno da Nota Fiscal Eletrônica"
		#define STR0053 "Cliente"
		#define STR0054 "Loja"
		#define STR0055 "NF-e"
		#define STR0056 "Valor ISS"
		#define STR0057 "Status"
		#define STR0058 "Mensagem de Erro"
		#define STR0059 "Total de documentos importados sem erro: "
		#define STR0060 "Total de documentos não importados:      "
		#define STR0061 "Total de documentos importados sem erro "
		#define STR0062 "Total de documentos não importados      "
		#define STR0063 "Não foi encontrado o cabeçalho (SF2) do documento para a filial: "
		#define STR0064 ", RPS: "
		#define STR0065 " e série: "
		#define STR0066 ". Verifique se o arquivo está sendo importado na filial correta."
		#define STR0067 "ISS no arq. de retorno: "
		#define STR0068 " diverge do gravado nas notas fiscais: "
		#define STR0069 "Alíquota no arq. de retorno: "
		#define STR0070 " diverge da gravada nas notas fiscais: "
		#define STR0071 "O código do ISS gravado no livro fiscal (SF3): "
		#define STR0072 " diverge do arquivo de retorno: "
		#define STR0073 "Livro fiscal (SF3) não localizado. Verifique se o código do ISS e/ou cliente da NF-e correspondem ao RPS."
	#endif
#endif
