#ifdef SPANISH
	#define STR0001 "Trabajador sin vinculo de empleo - Inicio"
	#define STR0002 "Registro incluido"
	#define STR0003 "Registro Modificado"
	#define STR0004 "Registro Borrado"
	#define STR0005 "Visualizar"
	#define STR0006 "Datos del trabajador"
	#define STR0007 "Informaciones de nacimiento"
	#define STR0008 "Documentos"
	#define STR0009 "Direccion"
	#define STR0010 "Informaciones del contacto"
	#define STR0011 "Informaciones de Transmision"
	#define STR0012 "Trabajador Por Hora"
	#define STR0013 "Contribuyente Individual"
	#define STR0014 "Servidor Publico"
	#define STR0015 "Dirigente Sindical"
	#define STR0016 "Pasante"
	#define STR0017 "Trabajador"
	#define STR0018 "Informaciones del Trabajador"
	#define STR0019 "Informaciones del Trabajador Extranjero"
	#define STR0020 "Informaciones Deficiencia"
	#define STR0021 "Dependientes"
	#define STR0022 "Sin Vinculo"
	#define STR0023 "Informaciones del Trabajador Sin Vinculo"
	#define STR0024 "Registro transmitido"
	#define STR0025 "Este evento se encuentra transmitido."
	#define STR0026 "El borrado de este registro se debe hacer por medio del evento S-2900."
	#define STR0027 "Encerramiento"
	#define STR0028 "El Evento de borrado no se transmitio. ¿Realmente quiere borrarlo o mantener el evento de borrado para transmision posterior ?"
	#define STR0029 "Borrar"
	#define STR0030 "Mantener"
#else
	#ifdef ENGLISH
		#define STR0001 "Worker Without Work Link - Start"
		#define STR0002 "Record Added"
		#define STR0003 "Record Edited"
		#define STR0004 "Record Deleted"
		#define STR0005 "View"
		#define STR0006 "Worker Data"
		#define STR0007 "Information of Birth"
		#define STR0008 "Documents"
		#define STR0009 "Address"
		#define STR0010 "Contact Information"
		#define STR0011 "Information of Transmission"
		#define STR0012 "Individual Worker"
		#define STR0013 "Individual Taxpayer"
		#define STR0014 "Public Server"
		#define STR0015 "Union Leader"
		#define STR0016 "Intern"
		#define STR0017 "Worker"
		#define STR0018 "Employee Information"
		#define STR0019 "Foreigner Worker Information"
		#define STR0020 "Disability Information"
		#define STR0021 "Dependents"
		#define STR0022 "No relationship"
		#define STR0023 "Worker information with no relationship"
		#define STR0024 "Record Transmitted"
		#define STR0025 "This event was transmitted."
		#define STR0026 "The deletion of this record should be done by event S-2900."
		#define STR0027 "Close"
		#define STR0028 "The deletion Event was not transmitted. Do you really wish to delete it or keep the deletion event for later transmission?"
		#define STR0029 "Delete"
		#define STR0030 "Keep"
	#else
		#define STR0001 "Trabalhador Sem Vínculo de Emprego - Início"
		#define STR0002 "Registro Incluído"
		#define STR0003 "Registro Alterado"
		#define STR0004 "Registro Excluído"
		#define STR0005 "Visualizar"
		#define STR0006 "Dados do Trabalhador"
		#define STR0007 "Informações de Nascimento"
		#define STR0008 "Documentos"
		#define STR0009 "Endereço"
		#define STR0010 "Informações do Contato"
		#define STR0011 "Informações de Transmissão"
		#define STR0012 "Trabalhador Avulso"
		#define STR0013 "Contribuinte Individual"
		#define STR0014 "Servidor Público"
		#define STR0015 "Dirigente Sindical"
		#define STR0016 "Estagiário"
		#define STR0017 "Trabalhador"
		#define STR0018 "Informações do Trabalhador"
		#define STR0019 "Informações de Trabalhador Estrangeiro"
		#define STR0020 "Informações Deficiência"
		#define STR0021 "Dependentes"
		#define STR0022 "Sem Vínculo"
		#define STR0023 "Informações do Trabalhador Sem Vínculo"
		#define STR0024 "Registro Transmitido"
		#define STR0025 "Este evento encontra-se transmitido."
		#define STR0026 "A exclusão deste registro deverá ser feita através do evento S-2900."
		#define STR0027 "Fechar"
		#define STR0028 "O Evento de exclusão não foi transmitido. Deseja realmente exclui-lo ou manter o evento de exclusão para transmissão posterior ?"
		#define STR0029 "Excuir"
		#define STR0030 "Manter"
	#endif
#endif
