#ifdef SPANISH
	#define STR0001 "Asistente de configuracion e-Social / Factura electronica"
	#define STR0002 "Complete correctamente las informaciones solicitadas."
	#define STR0003 "Asistente para configuracion de los parametros necesarios para la transmision de los archivos del e-Social y Factura Electronica"
	#define STR0004 "Configuracion del Certificado digital"
	#define STR0005 "Parametros para generacion"
	#define STR0006 "Servicio"
	#define STR0007 "1 - E-Social"
	#define STR0008 "2 - Factura electronica"
	#define STR0009 "Url WebService"
	#define STR0010 "Url Totvs Sped"
	#define STR0011 "1 - Produccion"
	#define STR0012 "2 - Homologacion"
	#define STR0013 "Tipo de certificado digital"
	#define STR0014 "Formato apache(.pem)"
	#define STR0015 "Formato PFX(.pfx o .p12)"
	#define STR0016 "HSM"
	#define STR0017 "Nombre del archivo del certificado digital"
	#define STR0018 "Informe el nombre del archivo de la private key"
	#define STR0019 "Slot del certificado digital"
	#define STR0020 "Label del certificado digital"
	#define STR0021 "Contrasena del archivo digital"
	#define STR0022 "Camino y archivo del modulo HSM"
	#define STR0023 "Servidor SMTP"
	#define STR0024 "Utilizar conexion segura"
	#define STR0025 "Utilizar conexion segura TLS"
	#define STR0026 "Enviar DANFE por e-mail"
	#define STR0027 "Servidor POP"
	#define STR0028 "Login de e-mail"
	#define STR0029 "Contrasena"
	#define STR0030 "Cuenta de e-mail"
	#define STR0031 "Autenticacion"
	#define STR0032 "E-mail de notificacion"
	#define STR0033 "Entorno"
	#define STR0034 "Seleccione el Entorno y el Servicio"
	#define STR0035 "Requerida"
	#define STR0036 "Si"
	#define STR0037 "Esta rutina tiene como objetivo ayudarlo en la configuracion de la integracion del Protheus con el servicio TOTVS Services SPED. "
	#define STR0038 "El primer paso es configurar la conexion del Protheus con el servicio."
	#define STR0039 "Atencion"
	#define STR0040 "Siga con atencion los pasos para la configuracion del e-Social/e-Fact."
	#define STR0041 "Drive:"
	#define STR0042 "Archivos .PEM |*.PEM"
	#define STR0043 "Seleccione el certificado"
	#define STR0044 "Arquivos .PFX |*.PFX"
	#define STR0045 "ID Hex del certificado digital"
	#define STR0046 "Usted concluyo con exito la configuracion de la integracion del Protheus para el TOTVS Services."
#else
	#ifdef ENGLISH
		#define STR0001 "e-Invoice/e-Social Configuration Wizard"
		#define STR0002 "Fill out properly with the required information."
		#define STR0003 "Assistant for configuration of parameters necessary for transmitting the e-Social and e-Invoice files."
		#define STR0004 "Digital certificate configuration"
		#define STR0005 "Parameters for Generation"
		#define STR0006 "Service"
		#define STR0007 "1 - e-Social"
		#define STR0008 "2 - e-Invoice"
		#define STR0009 "WebService Url"
		#define STR0010 "TOTVS Sped Url"
		#define STR0011 "1- Production"
		#define STR0012 "2 - Approval"
		#define STR0013 "Digital certificate type"
		#define STR0014 "Apache format(.pem)"
		#define STR0015 "PFX Format(.pfx or .p12) "
		#define STR0016 "HSM"
		#define STR0017 "File name of digital certificate"
		#define STR0018 "Enter file name of private key"
		#define STR0019 "Slot of digital certificate"
		#define STR0020 "Label of digital certificate"
		#define STR0021 "Password of digital file"
		#define STR0022 "Path and file of HSM module"
		#define STR0023 "SMTP Server"
		#define STR0024 "Use safe connection"
		#define STR0025 "Use TLS safe connection"
		#define STR0026 "Send DANFE by e-mail"
		#define STR0027 "POP Server"
		#define STR0028 "E-mail login"
		#define STR0029 "Password"
		#define STR0030 "E-mail account"
		#define STR0031 "Authentication"
		#define STR0032 "Notification e-mail"
		#define STR0033 "Environment"
		#define STR0034 "Select the Environment and Service"
		#define STR0035 "Requested"
		#define STR0036 "Yes"
		#define STR0037 "This routine helps you configure the integration of Protheus with TOTVS SPED Services. "
		#define STR0038 "The first step is to configure Protheus connection with the service."
		#define STR0039 "Attention"
		#define STR0040 "Follow the steps carefully to configure e-Social/EIvc."
		#define STR0041 "Drive:"
		#define STR0042 "Files .PEM |*.PEM"
		#define STR0043 "Select certificate"
		#define STR0044 "Files .PFX |*.PFX"
		#define STR0045 "Hex ID of digital certificate"
		#define STR0046 "You successfully finished the configuration of the integration of Protheus with Totvs Services."
	#else
		#define STR0001 "Assistente de Configuração e-Social / Nota Fiscal Eletrônica"
		#define STR0002 "Preencha corretamente as informações solicitadas."
		#define STR0003 "Assistente para configuração dos parâmetros necessários para a transmissão dos arquivos do e-Social e Nota Fiscal Eletrôncia"
		#define STR0004 "Configuração do Certificado Digital"
		#define STR0005 "Parâmetros para Geração"
		#define STR0006 "Serviço"
		#define STR0007 "1 - E-Social"
		#define STR0008 "2 - Nota fiscal eletrônica"
		#define STR0009 "Url WebService"
		#define STR0010 "Url Totvs Sped"
		#define STR0011 "1 - Produção"
		#define STR0012 "2 - Homologação"
		#define STR0013 "Tipo de certificado digital"
		#define STR0014 "Formato Apache (.pem)"
		#define STR0015 "Formato PFX (*.pfx ou *.p12)"
		#define STR0016 "HSM"
		#define STR0017 "Nome do arquivo do certificado digital"
		#define STR0018 "Informe o nome do arquivo da private key"
		#define STR0019 "Slot do certificado digital"
		#define STR0020 "Label do certificado digital"
		#define STR0021 "Senha do arquivo digital"
		#define STR0022 "Caminho e arquivo do módulo HSM"
		#define STR0023 "Servidor SMTP"
		#define STR0024 "Utilizar conexão segura"
		#define STR0025 "Utilizar conexão segura TLS"
		#define STR0026 "Enviar DANFE por e-mail"
		#define STR0027 "Servidor POP"
		#define STR0028 "Login do e-mail"
		#define STR0029 "Senha"
		#define STR0030 "Conta de e-mail"
		#define STR0031 "Autenticação"
		#define STR0032 "E-mail de notificação"
		#define STR0033 "Ambiente"
		#define STR0034 "Selecione o Ambiente e o Serviço"
		#define STR0035 "Requerida"
		#define STR0036 "Sim"
		#define STR0037 "Esta rotina tem como objetivo ajuda-lo na configuração da integração com o Protheus com o serviço Totvs Services SPED. "
		#define STR0038 "O primeiro passo é configurar a conexão do Protheus com o serviço."
		#define STR0039 "Atenção"
		#define STR0040 "Siga atentamente os passos para a configuração do e-Social/Nfe."
		#define STR0041 "Drive:"
		#define STR0042 "Arquivos .PEM |*.PEM"
		#define STR0043 "Selecione o certificado"
		#define STR0044 "Arquivos .PFX |*.PFX"
		#define STR0045 "ID Hex do certificado digital"
		#define STR0046 "Você concluíu com sucesso a configuração da integração do Protheus para o Totvs Services."
	#endif
#endif
