#ifdef SPANISH
	#define STR0001 "Monitor de seguimiento de Check-In"
	#define STR0002 "Estructura"
	#define STR0003 "Check-In realizado"
	#define STR0004 "Esperando decision operativa"
	#define STR0005 "Ausente"
	#define STR0006 "Leyenda"
	#define STR0007 "Visualizar localizacion"
	#define STR0008 "Campo con localizacion Vacio"
	#define STR0009 "Registro sin programacion de agenda"
	#define STR0010 "Analisis de Check-In"
	#define STR0011 "Salir"
	#define STR0012 "Usted selecciono un periodo que contiene fechas incorrectas"
	#define STR0013 "Usted selecciono un periodo que contiene horarios incorrectos"
	#define STR0014 "¡No hay registros para mostrar!"
	#define STR0015 "La agenda ya tiene mantenimiento por motivo de anulacion."
	#define STR0016 "No se puede realizar la sustitución de la agenda. ¡Fuente TECA550 desatuaclizado!"
	#define STR0017 "¡Usuario sin autorizacion de acceso a las informaciones de asignacion!"
	#define STR0018 "Usuario no esta autorizado para realizar mantenimiento en esta agenda."
	#define STR0019 "Sustituir"
	#define STR0020 "Filtro"
	#define STR0021 "Actualizar"
	#define STR0022 "Actualizando"
	#define STR0023 "Ajustar Check-In"
	#define STR0024 "Registro inconsistente"
	#define STR0025 "Hora extra"
	#define STR0026 "Salida anticipada"
	#define STR0027 "Transferencia"
	#define STR0028 "Atencion"
	#define STR0029 "No existen datos vinculados para efectuar la busqueda de manera especifica"
	#define STR0030 "No se puede ajustar el Check-In sin referencia inicial"
	#define STR0031 "Registrar falta"
	#define STR0032 "No se puede registrar falta sin referencia inicial"
	#define STR0033 "El Check-In seleccionado ya posee presencia registrada"
	#define STR0034 "Timer Activado"
	#define STR0035 "Timer Desactivado"
	#define STR0036 "Check-In no realizado: "
	#define STR0037 "Check-In realizados: "
	#define STR0038 "Fecha"
	#define STR0039 "Hora"
	#define STR0040 "Puesto X Marcacion del Check-In"
#else
	#ifdef ENGLISH
		#define STR0001 "Check-in Follow Up Monitor"
		#define STR0002 "Structure"
		#define STR0003 "Check-in"
		#define STR0004 "Awaiting Operational Decision"
		#define STR0005 "Absent"
		#define STR0006 "Caption"
		#define STR0007 "View Location"
		#define STR0008 "Empty localization field"
		#define STR0009 "Marking with no Scheduling"
		#define STR0010 "Check-in Analysis"
		#define STR0011 "Exit"
		#define STR0012 "You selected a period that contains incorrect dates"
		#define STR0013 "You selected a period that contains incorrect times"
		#define STR0014 "There are no records to display!"
		#define STR0015 "The schedule already has a maintenance by cancellation reason."
		#define STR0016 "Schedule replacements could not be made. Source TECA550 outdated!"
		#define STR0017 "User with no access permission for allocation information!"
		#define STR0018 "User not allowed to make maintenances to this schedule."
		#define STR0019 "Replace"
		#define STR0020 "Filter"
		#define STR0021 "Update"
		#define STR0022 "Updating"
		#define STR0023 "Adjust Check-In"
		#define STR0024 "Inconsistent Marking"
		#define STR0025 "Overtime"
		#define STR0026 "Early Exit"
		#define STR0027 "Transfer"
		#define STR0028 "Warning"
		#define STR0029 "There are no related data to run a specific query"
		#define STR0030 "Not possible to adjust the check-in with no Start Reference"
		#define STR0031 "Point Failure"
		#define STR0032 "Not possible to point a mistake with no Start Reference"
		#define STR0033 "Selected Check-in Already Has Registered Attendance"
		#define STR0034 "Activated Timer"
		#define STR0035 "Deactivated Timer"
		#define STR0036 "Check-In Not Made: "
		#define STR0037 "Check-ins Made: "
		#define STR0038 "Date"
		#define STR0039 "Time"
		#define STR0040 "Station X Check-In Selection"
	#else
		#define STR0001 "Monitor de Acompanhamento de Check-In"
		#define STR0002 "Estrutura"
		#define STR0003 "Check-In realizado"
		#define STR0004 "Aguardando Decisão Operacional"
		#define STR0005 "Ausente"
		#define STR0006 "Legenda"
		#define STR0007 "Visualizar Localização"
		#define STR0008 "Campo com Localização Vazio"
		#define STR0009 "Marcação Sem Agendamento"
		#define STR0010 "Analise de Check-In"
		#define STR0011 "Sair"
		#define STR0012 "Você Selecionou um Período Contendo Datas Incorretas"
		#define STR0013 "Você Selecionou um Período Contendo Horários Incorretos"
		#define STR0014 "Não há registros para serem exibidos!"
		#define STR0015 "A agenda já possui manutenção por motivo de cancelamento."
		#define STR0016 "Não será possivel realizar a substituição da agenda. Fonte TECA550 desatualizado!"
		#define STR0017 "Usuário sem permissão de acesso para as informações de alocação!"
		#define STR0018 "Usuário não possui permissão para realizar manutenção nesta agenda."
		#define STR0019 "Substituir"
		#define STR0020 "Filtro"
		#define STR0021 "Atualizar"
		#define STR0022 "Atualizando"
		#define STR0023 "Ajustar Check-In"
		#define STR0024 "Marcação Inconsistente"
		#define STR0025 "Hora Extra"
		#define STR0026 "Saida Antecipada"
		#define STR0027 "Transferencia"
		#define STR0028 "Atenção"
		#define STR0029 "Não Existem Dados Relacionados para Efetuar a Pesquisa de Forma Específica"
		#define STR0030 "Não é Possível Ajusta Check-In Sem Referencia Inicial"
		#define STR0031 "Apontar Falta"
		#define STR0032 "Não é Possível Apontar Falta Sem Referencia Inicial"
		#define STR0033 "O Check-In Selecionado Já Possui Presença Registrada"
		#define STR0034 "Timer Ativado"
		#define STR0035 "Timer Desativado"
		#define STR0036 "Check-In Não Realizado: "
		#define STR0037 "Check-In Realizados: "
		#define STR0038 "Data"
		#define STR0039 "Hora"
		#define STR0040 "Posto X Marcação do Check-In"
	#endif
#endif
