#IFDEF SPANISH
   #define STR0001 "PRODUTO"
   #define STR0002 "Para Devolucao Grade Tecle F11"
   #define STR0003 "Tipo tem que ser igual a Devolucao"
   #define STR0004 "Preencha o numero da nota fiscal"
   #define STR0005 "Preencha a série da nota fiscal"
   #define STR0006 "Preencha o código do cliente"
   #define STR0007 "Preencha a loja do cliente"
   #define STR0008 "Preencha a espécie da nota fiscal"
   #define STR0009 "Aguarde, atualizado Itens "
   #define STR0010 "Marca"
   #define STR0011 "F10 - Marca Item   F11-Marca Grade   F12-Marca Todos"
   #define STR0012 "Pesquisar por:"
   #define STR0013 "Localizar"
   #define STR0014 "Emissao         ?"
   #define STR0015 "TES             ?"
   #define STR0016 "Centro de Custo ?"
   #define STR0017 "Armazem         ?"
#ELSE
   #IFDEF ENGLISH
      #define STR0001 "PRODUTO"
      #define STR0002 "Para Devolucao Grade Tecle F11"
      #define STR0003 "Tipo tem que ser igual a Devolucao"
      #define STR0004 "Preencha o numero da nota fiscal"
      #define STR0005 "Preencha a série da nota fiscal"
      #define STR0006 "Preencha o código do cliente"
      #define STR0007 "Preencha a loja do cliente"
      #define STR0008 "Preencha a espécie da nota fiscal"
      #define STR0009 "Aguarde, atualizado Itens "
      #define STR0010 "Marca"
      #define STR0011 "F10 - Marca Item   F11-Marca Grade   F12-Marca Todos"
      #define STR0012 "Pesquisar por:"
      #define STR0013 "Localizar"
      #define STR0014 "Emissao         ?"
      #define STR0015 "TES             ?"
      #define STR0016 "Centro de Custo ?"
      #define STR0017 "Armazem         ?"
   #ELSE
      #define STR0001 "PRODUTO"
      #define STR0002 "Para Devolucao Grade Tecle F11"
      #define STR0003 "Tipo tem que ser igual a Devolucao"
      #define STR0004 "Preencha o numero da nota fiscal"
      #define STR0005 "Preencha a série da nota fiscal"
      #define STR0006 "Preencha o código do cliente"
      #define STR0007 "Preencha a loja do cliente"
      #define STR0008 "Preencha a espécie da nota fiscal"
      #define STR0009 "Aguarde, atualizado Itens "
      #define STR0010 "Marca"
      #define STR0011 "F10 - Marca Item   F11-Marca Grade   F12-Marca Todos"
      #define STR0012 "Pesquisar por:"
      #define STR0013 "Localizar"
      #define STR0014 "Emissao         ?"
      #define STR0015 "TES             ?"
      #define STR0016 "Centro de Custo ?"
      #define STR0017 "Armazem         ?"
   #ENDIF
#ENDIF
