#ifdef SPANISH
	#define STR0001 "ACTUALIZACION DE DICCIONARIOS Y TABLAS"
	#define STR0002 "Esta rutina tiene como funcion actualizar los diccionarios del sistema ( SX?/SIX )"
	#define STR0003 "Este proceso debe ejecutarse de modo EXCLUSIVO, es decir, no deben haber otros"
	#define STR0004 "usuarios o jobs utilizando el sistema.  Es EXTREMADAMENTE recomendable que se haga una"
	#define STR0005 "COPIA DE SEGURIDAD de los DICCIONARIOS  y de la  BASE DE DATOS antes de esta actualizacion, porque si "
	#define STR0006 "ocurren eventuales fallas, esta copia de seguridad se podra restaurar."
	#define STR0007 "¿Confirma la actualizacion de los diccionarios?"
	#define STR0008 "Actualizando"
	#define STR0009 "Espere, actualizando..."
	#define STR0010 "Actualizacion realizada."
	#define STR0011 "Actualizacion no realizada."
	#define STR0012 "Actualizacion concluida."
	#define STR0013 "UPDLO153"
	#define STR0014 "Actualizacion de la empresa "
	#define STR0015 " no efectuada."
	#define STR0016 "LOG DE ACTUALIZACION DE LOS DICCIONARIOS"
	#define STR0017 " Datos entorno"
	#define STR0018 " --------------------"
	#define STR0019 " Empresa/Sucursal...: "
	#define STR0020 " Nombre empresa...: "
	#define STR0021 " Nombre sucursal...: "
	#define STR0022 " Fecha base...........: "
	#define STR0023 " Fecha/Hora inicial.: "
	#define STR0024 " Environment........: "
	#define STR0025 " StartPath..........: "
	#define STR0026 " RootPath...........: "
	#define STR0027 " Version.............: "
	#define STR0028 " Usuario TOTVS .....: "
	#define STR0029 " Computer Name......: "
	#define STR0030 " Datos Thread"
	#define STR0031 " Usuario de la red....: "
	#define STR0032 " Estacion............: "
	#define STR0033 " Programa inicial...: "
	#define STR0034 " Environment........: "
	#define STR0035 " Conexion............: "
	#define STR0036 "Empresa: "
	#define STR0037 "Diccionario de datos"
	#define STR0038 "Actualizando campos/indices"
	#define STR0039 "Hubo un error desconocido durante la actualizacion de la tabla: "
	#define STR0040 ". Verifique la integridad del diccionario y de la tabla."
	#define STR0041 "ATENCION"
	#define STR0042 "Hubo un error desconocido durante la actualizacion de la estructura de la tabla: "
	#define STR0043 "Diccionario de tablas sistema"
	#define STR0044 "Help de campo"
	#define STR0045 " Fecha/Hora final.: "
	#define STR0046 "Actualizacion concluida."
	#define STR0047 "Inicio de la actualizacion"
	#define STR0048 "Reser. Hotel"
	#define STR0049 "Reserva hotel"
	#define STR0050 "El tamano del campo "
	#define STR0051 " NO se actualizo y se mantuvo en ["
	#define STR0052 "]"
	#define STR0053 " porque pertenece al grupo de campos ["
	#define STR0054 "]"
	#define STR0055 "Se creo el campo "
	#define STR0056 "Actualizando campos de tablas (SX3)..."
	#define STR0057 "Final de la actualizacion"
	#define STR0058 " SX3"
	#define STR0059 "Inicio de la actualizacion del SX5"
	#define STR0060 "CREDITO AL CUARTO"
	#define STR0061 "Actualizando tablas..."
	#define STR0062 "Item creado de la tabla. Tabla "
	#define STR0063 "Item modificado de la tabla. Tabla "
	#define STR0064 "Final de la actualizacion"
	#define STR0065 " SX5"
	#define STR0066 "Inicio de la actualizacion"
	#define STR0067 "Helps de campo"
	#define STR0068 "Actualizando helps de campo..."
	#define STR0069 "Codigo de la reserva - Hotel."
	#define STR0070 "Se actualizo el help de campo "
	#define STR0071 "Pantalla para multiples selecciones de Empresas/Sucursales"
	#define STR0072 "Seleccione la(s) empresa(s) para actualizacion"
	#define STR0073 "Empresa"
	#define STR0074 "Todos"
	#define STR0075 "Marca/Desmarca"
	#define STR0076 "Mascara empresa ( ?? )"
	#define STR0077 "&Invertir"
	#define STR0078 "Invertir seleccion"
	#define STR0079 "&Marcar"
	#define STR0080 "Marcar utilizando"
	#define STR0081 "mascara ( ?? )"
	#define STR0082 "&Desmarcar"
	#define STR0083 "Desmarcar utilizando"
	#define STR0084 "Procesar"
	#define STR0085 "Confirma la seleccion y realiza"
	#define STR0086 "el procesamiento"
	#define STR0087 "Anular"
	#define STR0088 "Anula el procesamiento"
	#define STR0089 "y abandona la aplicacion"
	#define STR0090 "No fue posible abrir la tabla "
	#define STR0091 "de empresas (SM0)."
	#define STR0092 "de empresas (SM0) de forma exclusiva."
	#define STR0093 "Tamano maximo de exhibicion del LOG alcanzado."
	#define STR0094 "LOG Completo en el archivo "
#else
	#ifdef ENGLISH
		#define STR0001 "TABLE AND DICTIONARY UPDATE"
		#define STR0002 "This routine updates system dictionaries ( SX?/SIX )"
		#define STR0003 "Run this process in EXCLUSIVE mode; that is, with no other"
		#define STR0004 "users or jobs using the system.  It is STRONGLY advisable to"
		#define STR0005 "BACKUP DICTIONARIES and DATABASE before this update, so you can "
		#define STR0006 "restore this backup in case of failures."
		#define STR0007 "Confirm dictionary update?"
		#define STR0008 "Updating"
		#define STR0009 "Wait, updating ..."
		#define STR0010 "Update Completed."
		#define STR0011 "Update Failed."
		#define STR0012 "Update Finished."
		#define STR0013 "UPDLO153"
		#define STR0014 "Company update "
		#define STR0015 " failed."
		#define STR0016 "DICTIONARY UPDATE LOG"
		#define STR0017 " Environment Data"
		#define STR0018 " --------------------"
		#define STR0019 " Company/Branch...: "
		#define STR0020 " Company Name.......: "
		#define STR0021 " Branch Name........: "
		#define STR0022 " BaseDate...........: "
		#define STR0023 " Start Date/Time: "
		#define STR0024 " Environment........: "
		#define STR0025 " StartPath..........: "
		#define STR0026 " RootPath...........: "
		#define STR0027 " Version.............: "
		#define STR0028 " TOTVS User .......: "
		#define STR0029 " Computer Name......: "
		#define STR0030 " Thread Data"
		#define STR0031 " Network User....: "
		#define STR0032 " Station............: "
		#define STR0033 " Initial Program...: "
		#define STR0034 " Environment........: "
		#define STR0035 " Connection............: "
		#define STR0036 "Company: "
		#define STR0037 "Data dictionary"
		#define STR0038 "Updating fields/indexes"
		#define STR0039 "There was an unknown error during table update: "
		#define STR0040 ". Check dictionary and table integrity."
		#define STR0041 "ATTENTION"
		#define STR0042 "An unknown error occurred during table structure update: "
		#define STR0043 "Dictionary of system tables"
		#define STR0044 "Field Helps"
		#define STR0045 " End Date / Time.: "
		#define STR0046 "Update completed."
		#define STR0047 "Start of Update"
		#define STR0048 "Hotel Reser"
		#define STR0049 "Hotel Reservation"
		#define STR0050 "Field size "
		#define STR0051 " NOT updated and kept in ["
		#define STR0052 "]"
		#define STR0053 " because it belongs to field group ["
		#define STR0054 "]"
		#define STR0055 "Field created "
		#define STR0056 "Updating Table Fields (SX3)..."
		#define STR0057 "End of Update"
		#define STR0058 " SX3"
		#define STR0059 "Start of Update SX5"
		#define STR0060 "CREDIT TO ROOM"
		#define STR0061 "Updating tables..."
		#define STR0062 "Table item created. Table "
		#define STR0063 "Table item changed. Table "
		#define STR0064 "End of Update"
		#define STR0065 " SX5"
		#define STR0066 "Start of Update"
		#define STR0067 "Field Helps"
		#define STR0068 "Updating field helps..."
		#define STR0069 "Reservation Code - Hotel."
		#define STR0070 "Field help updated "
		#define STR0071 "Screen for Multiple Selections of Companies/Branches"
		#define STR0072 "Select Companies for Update"
		#define STR0073 "Company"
		#define STR0074 "All"
		#define STR0075 "Select / Clear"
		#define STR0076 "Company Mask (?? )"
		#define STR0077 "&Invert"
		#define STR0078 "Invert Selection"
		#define STR0079 "&Select"
		#define STR0080 "Select using"
		#define STR0081 "mask (?? )"
		#define STR0082 "&Clear"
		#define STR0083 "Clear using"
		#define STR0084 "Process"
		#define STR0085 "Check the selection and perform"
		#define STR0086 "the processing"
		#define STR0087 "Cancel"
		#define STR0088 "Cancel processing"
		#define STR0089 "and abandon application"
		#define STR0090 "Could not open table "
		#define STR0091 "of companies (SM0)."
		#define STR0092 "of companies (SM0) exclusively."
		#define STR0093 "Maximum exhibition size LOG."
		#define STR0094 "Complete LOG on file "
	#else
		#define STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#define STR0002 "Esta rotina tem como função fazer  a atualização  dos dicionários do Sistema ( SX?/SIX )"
		#define STR0003 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
		#define STR0004 "usuários  ou  jobs utilizando  o sistema.  É EXTREMAMENTE recomendavél  que  se  faça um"
		#define STR0005 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização, para que caso "
		#define STR0006 "ocorram eventuais falhas, esse backup possa ser restaurado."
		#define STR0007 "Confirma a atualização dos dicionários ?"
		#define STR0008 "Atualizando"
		#define STR0009 "Aguarde, atualizando ..."
		#define STR0010 "Atualização Realizada."
		#define STR0011 "Atualização não Realizada."
		#define STR0012 "Atualização Concluída."
		#define STR0013 "UPDLO153"
		#define STR0014 "Atualização da empresa "
		#define STR0015 " não efetuada."
		#define STR0016 "LOG DA ATUALIZAÇÃO DOS DICIONÁRIOS"
		#define STR0017 " Dados Ambiente"
		#define STR0018 " --------------------"
		#define STR0019 " Empresa / Filial...: "
		#define STR0020 " Nome Empresa.......: "
		#define STR0021 " Nome Filial........: "
		#define STR0022 " DataBase...........: "
		#define STR0023 " Data / Hora Ínicio.: "
		#define STR0024 " Environment........: "
		#define STR0025 " StartPath..........: "
		#define STR0026 " RootPath...........: "
		#define STR0027 " Versão.............: "
		#define STR0028 " Usuário TOTVS .....: "
		#define STR0029 " Computer Name......: "
		#define STR0030 " Dados Thread"
		#define STR0031 " Usuário da Rede....: "
		#define STR0032 " Estação............: "
		#define STR0033 " Programa Inicial...: "
		#define STR0034 " Environment........: "
		#define STR0035 " Conexão............: "
		#define STR0036 "Empresa : "
		#define STR0037 "Dicionário de dados"
		#define STR0038 "Atualizando campos/índices"
		#define STR0039 "Ocorreu um erro desconhecido durante a atualização da tabela : "
		#define STR0040 ". Verifique a integridade do dicionário e da tabela."
		#define STR0041 "ATENÇÃO"
		#define STR0042 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
		#define STR0043 "Dicionário de tabelas sistema"
		#define STR0044 "Helps de Campo"
		#define STR0045 " Data / Hora Final.: "
		#define STR0046 "Atualização concluida."
		#define STR0047 "Ínicio da Atualização"
		#define STR0048 "Reser. Hotel"
		#define STR0049 "Reserva Hotel"
		#define STR0050 "O tamanho do campo "
		#define STR0051 " NÃO atualizado e foi mantido em ["
		#define STR0052 "]"
		#define STR0053 " por pertencer ao grupo de campos ["
		#define STR0054 "]"
		#define STR0055 "Criado campo "
		#define STR0056 "Atualizando Campos de Tabelas (SX3)..."
		#define STR0057 "Final da Atualização"
		#define STR0058 " SX3"
		#define STR0059 "Ínicio da Atualização SX5"
		#define STR0060 "CREDITO AO QUARTO"
		#define STR0061 "Atualizando tabelas..."
		#define STR0062 "Item da tabela criado. Tabela "
		#define STR0063 "Item da tabela alterado. Tabela "
		#define STR0064 "Final da Atualização"
		#define STR0065 " SX5"
		#define STR0066 "Ínicio da Atualização"
		#define STR0067 "Helps de Campos"
		#define STR0068 "Atualizando Helps de Campos ..."
		#define STR0069 "Codigo da reserva - Hotel."
		#define STR0070 "Atualizado o Help do campo "
		#define STR0071 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#define STR0072 "Selecione a(s) Empresa(s) para Atualização"
		#define STR0073 "Empresa"
		#define STR0074 "Todos"
		#define STR0075 "Marca / Desmarca"
		#define STR0076 "Máscara Empresa ( ?? )"
		#define STR0077 "&Inverter"
		#define STR0078 "Inverter Seleção"
		#define STR0079 "&Marcar"
		#define STR0080 "Marcar usando"
		#define STR0081 "máscara ( ?? )"
		#define STR0082 "&Desmarcar"
		#define STR0083 "Desmarcar usando"
		#define STR0084 "Processar"
		#define STR0085 "Confirma a seleção e efetua"
		#define STR0086 "o processamento"
		#define STR0087 "Cancelar"
		#define STR0088 "Cancela o processamento"
		#define STR0089 "e abandona a aplicação"
		#define STR0090 "Não foi possível a abertura da tabela "
		#define STR0091 "de empresas (SM0)."
		#define STR0092 "de empresas (SM0) de forma exclusiva."
		#define STR0093 "Tamanho de exibição maxima do LOG alcançado."
		#define STR0094 "LOG Completo no arquivo "
	#endif
#endif
