#ifdef SPANISH
	#define STR0001 "Deseja efetuar a atualizacao do Dicionário? Esta rotina deve ser utilizada em modo exclusivo ! Faca um backup dos dicionários e da Base de Dados antes da atualização para eventuais falhas de atualização !"
	#define STR0002 "Atençâo!"
	#define STR0003 "Atualização do Dicionario"
	#define STR0004 "Processando"
	#define STR0005 "Aguarde , processando arquivos"
	#define STR0006 "Atualizacao efetuada!"
	#define STR0007 "Verificando integridade dos dicionários...."
	#define STR0008 "Empresa : "
	#define STR0009 "Analisando Dicionario de Dados..."
	#define STR0010 "Atualizando estruturas. Aguarde... "
	#define STR0011 "Ocorreu um erro desconhecido durante a atualizacao da tabela : "
	#define STR0012 ". Verifique a integridade do dicionario e da tabela."
	#define STR0013 "Continuar"
	#define STR0014 "Ocorreu um erro desconhecido durante a atualizacao da estrutura da tabela : "
	#define STR0015 "Log da atualização "
	#define STR0016 "Atualização concluida."
	#define STR0017 "Deseja atualizar tamanho dos campos LF1_NOTA, LF1_NOTA02, LF1_NOTA03, LF1_NOTA04, LF1_NOTA05 ?"
	#define STR0018 "Foram alteradas as estruturas dos seguintes campos : "
	#define STR0019 "Nâo foi possivel a abertura da tabela de empresas de forma exclusiva !"
#else
	#ifdef ENGLISH
		#define STR0001 "Deseja efetuar a atualizacao do Dicionário? Esta rotina deve ser utilizada em modo exclusivo ! Faca um backup dos dicionários e da Base de Dados antes da atualização para eventuais falhas de atualização !"
		#define STR0002 "Atençâo!"
		#define STR0003 "Atualização do Dicionario"
		#define STR0004 "Processando"
		#define STR0005 "Aguarde , processando arquivos"
		#define STR0006 "Atualizacao efetuada!"
		#define STR0007 "Verificando integridade dos dicionários...."
		#define STR0008 "Empresa : "
		#define STR0009 "Analisando Dicionario de Dados..."
		#define STR0010 "Atualizando estruturas. Aguarde... "
		#define STR0011 "Ocorreu um erro desconhecido durante a atualizacao da tabela : "
		#define STR0012 ". Verifique a integridade do dicionario e da tabela."
		#define STR0013 "Continuar"
		#define STR0014 "Ocorreu um erro desconhecido durante a atualizacao da estrutura da tabela : "
		#define STR0015 "Log da atualização "
		#define STR0016 "Atualização concluida."
		#define STR0017 "Deseja atualizar tamanho dos campos LF1_NOTA, LF1_NOTA02, LF1_NOTA03, LF1_NOTA04, LF1_NOTA05 ?"
		#define STR0018 "Foram alteradas as estruturas dos seguintes campos : "
		#define STR0019 "Nâo foi possivel a abertura da tabela de empresas de forma exclusiva !"
	#else
		#define STR0001  "Deseja efetuar a atualizacao do Dicionário? Esta rotina deve ser utilizada em modo exclusivo ! Faca um backup dos dicionários e da Base de Dados antes da atualização para eventuais falhas de atualização !"
		#define STR0002  "Atençâo!"
		#define STR0003  "Atualização do Dicionario"
		#define STR0004  "Processando"
		#define STR0005  "Aguarde , processando arquivos"
		#define STR0006  "Atualizacao efetuada!"
		#define STR0007  "Verificando integridade dos dicionários...."
		#define STR0008  "Empresa : "
		#define STR0009  "Analisando Dicionario de Dados..."
		#define STR0010  "Atualizando estruturas. Aguarde... "
		#define STR0011  "Ocorreu um erro desconhecido durante a atualizacao da tabela : "
		#define STR0012  ". Verifique a integridade do dicionario e da tabela."
		#define STR0013  "Continuar"
		#define STR0014  "Ocorreu um erro desconhecido durante a atualizacao da estrutura da tabela : "
		#define STR0015  "Log da atualização "
		#define STR0016  "Atualização concluida."
		#define STR0017  "Deseja atualizar tamanho dos campos LF1_NOTA, LF1_NOTA02, LF1_NOTA03, LF1_NOTA04, LF1_NOTA05 ?"
		#define STR0018  "Foram alteradas as estruturas dos seguintes campos : "
		#define STR0019  "Nâo foi possivel a abertura da tabela de empresas de forma exclusiva !"
	#endif
	
#endif
