#ifdef SPANISH
	#define STR0001 "Este programa tiene por objetivo compatibilizar el entorno del cliente de acuerdo con las actualizaciones seleccionadas en la siguiente lista: "
	#define STR0002 "¡Estas actualizaciones solamente podrán realizarse de modo"
	#define STR0003 " exclusivo! "
	#define STR0004 "¡Haga una copia de seguridad de los diccionarios y de la base de datos antes de la actualización para eventuales fallas de actualización."
	#define STR0005 "Update compatibilizador - Totvs Automatización fiscal - Protheus"
	#define STR0006 "Marca/Desmarca pendientes"
	#define STR0007 "Pendiente"
	#define STR0008 "Seleccionar empresas"
	#define STR0009 "Procesar..."
	#define STR0010 "Anular"
	#define STR0011 "Espere la finalización del procesamiento"
	#define STR0012 "Parám. Apertura ECF"
	#define STR0013 "¡No fue posible la apertura de la tabla de empresas de forma exclusiva!"
	#define STR0014 "Se modificó el nombre del fuente vinculado a la consulta estándar CHD"
	#define STR0015 "Ejecutado"
	#define STR0016 "Pendiente"
	#define STR0017 "Empresa"
	#define STR0018 "Sucursal"
	#define STR0019 "Nombre"
	#define STR0020 "Id"
	#define STR0021 "Marca/Desmarca"
	#define STR0022 "LOG de actualizaciones"
	#define STR0023 "Espere, Montando el Tree con las actualizaciones..."
	#define STR0024 "Tabla"
	#define STR0025 "Archivo:"
	#define STR0026 "Descripción:"
	#define STR0027 "Modo de acceso:"
	#define STR0028 "Rutina:"
	#define STR0029 "Campo:"
	#define STR0030 "Orden:"
	#define STR0031 "Clave:"
	#define STR0032 "Descripción:"
	#define STR0033 "Título"
	#define STR0034 "Tamaño"
	#define STR0035 "Decimal"
	#define STR0036 "Utilizado:"
	#define STR0037 "Validación:"
	#define STR0038 "Inicializador estándar:"
	#define STR0039 "Inicializador estándar (Browse):"
	#define STR0040 "Modo de edición:"
	#define STR0041 "Contexto:"
	#define STR0042 "Propriedad:"
	#define STR0043 "Browse:"
	#define STR0044 "¿Cons. Estándar:"
	#define STR0045 "Carpeta:"
	#define STR0046 "Lista de opciones:"
	#define STR0047 "Parámetro"
	#define STR0048 "Tipo:"
	#define STR0049 "Contenido:"
	#define STR0050 "Origen:"
	#define STR0051 "Destino:"
	#define STR0052 "Regla:"
	#define STR0053 "Primario"
	#define STR0054 "Extranjero"
	#define STR0055 "Posición"
	#define STR0056 "¿Marca?"
	#define STR0057 "Sí"
	#define STR0058 "No"
	#define STR0059 "Condición:"
	#define STR0060 "Mensajes:"
	#define STR0061 "Grupo:"
	#define STR0062 "Pregunte:"
	#define STR0063 "Variable"
	#define STR0064 "Archivos"
	#define STR0065 "Ninguna actualización realizada"
	#define STR0066 "Índices"
	#define STR0067 "Índice"
	#define STR0068 "Diccionario de datos"
	#define STR0069 "Tablas genéricas"
	#define STR0070 "Disparadores"
	#define STR0071 "Disparador:"
	#define STR0072 "Carpetas (Folders)"
	#define STR0073 "Consultas estándares"
	#define STR0074 "Consulta:"
	#define STR0075 "Rutinas de ajuste de la base de datos"
	#define STR0076 "Rutina"
	#define STR0077 "Preguntas"
	#define STR0078 "Archivos texto "
	#define STR0079 "Actualizaciones - SX2: Tablas"
	#define STR0080 "Alias"
	#define STR0081 "Exclusivo"
	#define STR0082 "Compartido "
	#define STR0083 "Actualizaciones - SIX: Índices"
	#define STR0084 "Path"
	#define STR0085 "Archivo descripción"
	#define STR0086 "Modo de acceso"
	#define STR0087 "Índice"
	#define STR0088 "Orden"
	#define STR0089 "Clave"
	#define STR0090 "Descripción"
	#define STR0091 "Archivo"
	#define STR0092 "Campo"
	#define STR0093 "Tipo"
	#define STR0094 "Decimales"
	#define STR0095 "Actualizaciones - SX5: Tablas genéricas"
	#define STR0096 "Actualizaciones - SX7: Disparadores"
	#define STR0097 "Origen"
	#define STR0098 "Sec"
	#define STR0099 "Regla"
	#define STR0100 "Actualizaciones - SXA: Carpetas"
	#define STR0101 "Archivo"
	#define STR0102 "Actualizaciones - SXB: Consultas estándar"
	#define STR0103 "Columna"
	#define STR0104 "Contenido"
	#define STR0105 "Actualizaciones de rutinas"
	#define STR0106 "Estatus"
	#define STR0107 "Actualizaciones - SX1: Preguntas de parametrización"
	#define STR0108 "Grupo"
	#define STR0109 "Pregunte"
	#define STR0110 "Variable"
	#define STR0111 "¡Archivo de LOG grabado con éxito!"
	#define STR0112 "Error en la grabación del archivo de Log "
	#define STR0113 "Update"
	#define STR0114 "Llamado/Tarea"
	#define STR0115 "Seleccione las Empresas para el procesamiento..."
	#define STR0116 "Corrección en la validación y propiedades del campo CAX_ID y de la consulta estándar CAX"
	#define STR0117 "Corrección de campos inconsistentes en el bloque M de la ECF, en el archivo del registro M030. "
	#define STR0118 "¡Atención!"
	#define STR0119 "Ocurrió un error desconocido durante la actualización de la tabla: "
	#define STR0120 ". Verifique la integridad del diccionario y de la tabla."
	#define STR0121 "Existe parámetro en la base."
	#define STR0122 "A continuación se muestra su contenido: "
	#define STR0123 "Sí"
	#define STR0124 "No"
	#define STR0125 "Corrección en la consulta estándar para exhibición de los modelos fiscales. "
	#define STR0126 "Modelo de facturas"
	#define STR0127 "Actualización para atender el Manual de orientación de la ECF de Mayo 2015."
	#define STR0128 "Modificación en el índice 2 de la tabla CFQ para inclusión del campo CFQ_PAIS."
	#define STR0129 "Corrección de las relaciones del ECF, referente a tabla C1O."
	#define STR0130 "Relaciones "
	#define STR0131 "Dominio: "
	#define STR0132 "Actualizaciones - SX9: Relaciones"
	#define STR0133 "Remoción del botón de inclusión/modificación de la consulta estándar CZV."
	#define STR0134 "Corrección de error en la consulta estándar 'Tipos de barrio' "
	#define STR0135 "Tipos de barrio"
	#define STR0136 "Tipo de combustible vehicular"
	#define STR0137 "Modificación del índice de la columna"
	#define STR0138 "Código"
	#define STR0139 "Descripción"
	#define STR0140 "ID"
	#define STR0141 "Inclusión de la Rutina de dominio de la consulta"
	#define STR0142 "Actualizaciones - SX6: Parámetros"
	#define STR0143 "Correção da consulta padrão do campo CM4_TRABAL e a inicialização padrão do campo CM4_DTRABA na rotina de Aviso Prévio."
	#define STR0144 "Correção da consulta padrão do campo CMC_TRABAL e a inicialização padrão do campo CMC_DTRABA."
	#define STR0145 "Correção na inclusão das notas de entrada e saída."
	#define STR0146 "Adequação do Tamanho do campo 'C1E_CODFIL' utilizado no relacionamento com as tabelas compartilhadas."
	#define STR0147 "Ajuste na descrição, tamanho e casas decimais do campo CFV_TXJUR."
#else
	#ifdef ENGLISH
		#define STR0001 "This program aims to make the customer environment compatible in accordance with the updates selected on the list below: "
		#define STR0002 "These updates can only be made in mode"
		#define STR0003 " exclusive! "
		#define STR0004 "Backup dictionaries and database before updating to prepare for contingent update failures."
		#define STR0005 "Update Compatibility Program - TOTVS Tax Automation - Protheus"
		#define STR0006 "Check/Uncheck Pending Items"
		#define STR0007 "Pending"
		#define STR0008 "Select Companies"
		#define STR0009 "Process..."
		#define STR0010 "Cancel"
		#define STR0011 "Wait for process to finish."
		#define STR0012 "ECF Opening Parameter"
		#define STR0013 "Company table could not be opened in exclusive mode!"
		#define STR0014 "Name of source code related to default CHD query has changed"
		#define STR0015 "Executed"
		#define STR0016 "Pending"
		#define STR0017 "Company"
		#define STR0018 "Branch"
		#define STR0019 "Name"
		#define STR0020 "ID"
		#define STR0021 "Select/Clear"
		#define STR0022 "Updates LOG"
		#define STR0023 "Wait. Assembling Tree with updates..."
		#define STR0024 "Table"
		#define STR0025 "File:"
		#define STR0026 "Description:"
		#define STR0027 "Access Mode:"
		#define STR0028 "Routine:"
		#define STR0029 "Field:"
		#define STR0030 "Order:"
		#define STR0031 "Key:"
		#define STR0032 "Description:"
		#define STR0033 "Bill"
		#define STR0034 "Size"
		#define STR0035 "Decimal"
		#define STR0036 "Used:"
		#define STR0037 "Validation:"
		#define STR0038 "Default Starter:"
		#define STR0039 "Default Starter (Browser):"
		#define STR0040 "Editing Mode:"
		#define STR0041 "Context:"
		#define STR0042 "Property:"
		#define STR0043 "Browser:"
		#define STR0044 "Default Query:"
		#define STR0045 "Folder:"
		#define STR0046 "List of Options:"
		#define STR0047 "Parameter"
		#define STR0048 "Type:"
		#define STR0049 "Content:"
		#define STR0050 "Origin:"
		#define STR0051 "Destination:"
		#define STR0052 "Rule:"
		#define STR0053 "Primary"
		#define STR0054 "Foreign"
		#define STR0055 "Positioning"
		#define STR0056 "Position?"
		#define STR0057 "Yes"
		#define STR0058 "No"
		#define STR0059 "Condition:"
		#define STR0060 "Messages:"
		#define STR0061 "Group:"
		#define STR0062 "Question:"
		#define STR0063 "Variable"
		#define STR0064 "Files"
		#define STR0065 "No update performed"
		#define STR0066 "Indexes"
		#define STR0067 "Index"
		#define STR0068 "Data Dictionary"
		#define STR0069 "Generic Tables"
		#define STR0070 "Triggers"
		#define STR0071 "Trigger:"
		#define STR0072 "Folders"
		#define STR0073 "Default Queries"
		#define STR0074 "Query:"
		#define STR0075 "Database Adjustment Routines"
		#define STR0076 "Routine"
		#define STR0077 "Questions"
		#define STR0078 "Text Files "
		#define STR0079 "Updates - SX2: Tables"
		#define STR0080 "Alias"
		#define STR0081 "Exclusive"
		#define STR0082 "Shared "
		#define STR0083 "Updates - SIX: Indices"
		#define STR0084 "Path"
		#define STR0085 "File Description"
		#define STR0086 "Access Mode"
		#define STR0087 "Index"
		#define STR0088 "Order"
		#define STR0089 "Key"
		#define STR0090 "Description"
		#define STR0091 "File"
		#define STR0092 "Field"
		#define STR0093 "Type"
		#define STR0094 "Decimals"
		#define STR0095 "Updates - SX5: Generic Tables"
		#define STR0096 "Updates - SX7: Triggers"
		#define STR0097 "Source"
		#define STR0098 "Seq"
		#define STR0099 "Rule"
		#define STR0100 "Updates - SXA: Folders"
		#define STR0101 "File"
		#define STR0102 "Updates - SXB: Default Queries"
		#define STR0103 "Column"
		#define STR0104 "Content"
		#define STR0105 "Routine updates"
		#define STR0106 "Status"
		#define STR0107 "Updates - SX1: Parameterization Questions"
		#define STR0108 "Group"
		#define STR0109 "Question"
		#define STR0110 "Variable"
		#define STR0111 "LOG file saved!"
		#define STR0112 "Error saving log file "
		#define STR0113 "Update"
		#define STR0114 "Ticket/Task"
		#define STR0115 "Select Companies for processing..."
		#define STR0116 "Correction on validation and properties of the CAX_ID field and default query CAX"
		#define STR0117 "Inconsistent field corrections in Block M of ECF, in Register of Record M030. "
		#define STR0118 "Attention!"
		#define STR0119 "There was an unknown error during table update: "
		#define STR0120 ". Check dictionary and table integrity."
		#define STR0121 "There is already a parameter on the basis."
		#define STR0122 "Below its content: "
		#define STR0123 "Yes"
		#define STR0124 "No"
		#define STR0125 "Default query correction for displaying tax models. "
		#define STR0126 "Invoice Model"
		#define STR0127 "Update to comply with the ECF Guidance Manual of May 2015."
		#define STR0128 "Change in index 2 of table CFQ to add field CFQ_PAIS."
		#define STR0129 "Correction of ECF relationships related to table C1O."
		#define STR0130 "Relationships "
		#define STR0131 "Domain: "
		#define STR0132 "Updates - SX9: Relationships"
		#define STR0133 "Removal of add/edit button from CZV default query."
		#define STR0134 "Error correction in 'District Types' default query "
		#define STR0135 "District Types"
		#define STR0136 "Vehicle Fuel Type"
		#define STR0137 "Column Index Change"
		#define STR0138 "Code"
		#define STR0139 "Description"
		#define STR0140 "ID"
		#define STR0141 "Addition of Query Domain Routine"
		#define STR0142 "Updates - SX6: Parameters"
		#define STR0143 "Correction of default query of field CM4_TRABAL and default start of field CM4_DTRABA."
		#define STR0144 "Correction of default query of field CMC_TRABAL and default start of field CMC_DTRABA."
		#define STR0145 "Correction when adding inbound and outbound invoices."
		#define STR0146 "Adequação do Tamanho do campo 'C1E_CODFIL' utilizado no relacionamento com as tabelas compartilhadas."
		#define STR0147 "Ajuste na descrição, tamanho e casas decimais do campo CFV_TXJUR."
	#else
		#define STR0001 "Este programa tem por objetivo compatibilizar o ambiente do cliente conforme as atualizacoes selecionadas na lista abaixo: "
		#define STR0002 "Estas atualizacoes somente poderao ser realizadas em modo"
		#define STR0003 " exclusivo! "
		#define STR0004 "Faca um backup dos dicionários e da Base de Dados antes da atualização para eventuais falhas na atualização."
		#define STR0005 "Update Compatibilizador - Totvs Automação Fiscal - Protheus"
		#define STR0006 "Marca/Desmarca Pendentes"
		#define STR0007 "Pendente"
		#define STR0008 "Selecionar Empresas"
		#define STR0009 "Processar..."
		#define STR0010 "Cancelar"
		#define STR0011 "Aguarde o termino do Processamento"
		#define STR0012 "Param. Abertura ECF"
		#define STR0013 "Nao foi possivel a abertura da tabela de empresas de forma exclusiva !"
		#define STR0014 "Alterado nome do fonte associado a consulta padrão CHD"
		#define STR0015 "Executado"
		#define STR0016 "Pendente"
		#define STR0017 "Empresa"
		#define STR0018 "Filial"
		#define STR0019 "Nome"
		#define STR0020 "Id"
		#define STR0021 "Marca/Desmarca"
		#define STR0022 "LOG das Atualizacoes"
		#define STR0023 "Aguarde, Montando o Tree com as atualizacoes..."
		#define STR0024 "Tabela"
		#define STR0025 "Arquivo:"
		#define STR0026 "Descrição:"
		#define STR0027 "Modo de Acesso:"
		#define STR0028 "Rotina:"
		#define STR0029 "Campo:"
		#define STR0030 "Ordem:"
		#define STR0031 "Chave:"
		#define STR0032 "Descrição:"
		#define STR0033 "Titulo"
		#define STR0034 "Tamanho"
		#define STR0035 "Decimal"
		#define STR0036 "Usado:"
		#define STR0037 "Validação:"
		#define STR0038 "Inicializador Padrão:"
		#define STR0039 "Inicializador Padrão (Browse):"
		#define STR0040 "Modo de Edição:"
		#define STR0041 "Contexto:"
		#define STR0042 "Propriedade:"
		#define STR0043 "Browse:"
		#define STR0044 "Cons. Padrão:"
		#define STR0045 "Pasta:"
		#define STR0046 "Lista de Opções:"
		#define STR0047 "Parâmetro"
		#define STR0048 "Tipo:"
		#define STR0049 "Conteúdo:"
		#define STR0050 "Origem:"
		#define STR0051 "Destino:"
		#define STR0052 "Regra:"
		#define STR0053 "Primário"
		#define STR0054 "Estrangeiro"
		#define STR0055 "Posicionamento"
		#define STR0056 "Posiciona?"
		#define STR0057 "Sim"
		#define STR0058 "Não"
		#define STR0059 "Condicao:"
		#define STR0060 "Mensagens:"
		#define STR0061 "Grupo:"
		#define STR0062 "Pergunte:"
		#define STR0063 "Variável"
		#define STR0064 "Arquivos"
		#define STR0065 "Nenhuma atualizacao realizada"
		#define STR0066 "Indices"
		#define STR0067 "Indice"
		#define STR0068 "Dicionario de Dados"
		#define STR0069 "Tabelas Genéricas"
		#define STR0070 "Gatilhos"
		#define STR0071 "Gatilho:"
		#define STR0072 "Pastas (Folders)"
		#define STR0073 "Consultas Padroes"
		#define STR0074 "Consulta:"
		#define STR0075 "Rotinas de ajuste de base de dados"
		#define STR0076 "Rotina"
		#define STR0077 "Perguntas"
		#define STR0078 "Arquivos Texto "
		#define STR0079 "Atualizacoes - SX2: Tabelas"
		#define STR0080 "Alias"
		#define STR0081 "Exclusivo"
		#define STR0082 "Compartilhado "
		#define STR0083 "Atualizacoes - SIX: Indices"
		#define STR0084 "Path"
		#define STR0085 "Arquivo Descrição"
		#define STR0086 "Modo Acesso"
		#define STR0087 "Indice"
		#define STR0088 "Ordem"
		#define STR0089 "Chave"
		#define STR0090 "Descrição"
		#define STR0091 "Arquivo"
		#define STR0092 "Campo"
		#define STR0093 "Tipo"
		#define STR0094 "Decimais"
		#define STR0095 "Atualizacoes - SX5: Tabelas Genericas"
		#define STR0096 "Atualizacoes - SX7: Gatilhos"
		#define STR0097 "Origem"
		#define STR0098 "Seq"
		#define STR0099 "Regra"
		#define STR0100 "Atualizacoes - SXA: Pastas"
		#define STR0101 "Arquivo"
		#define STR0102 "Atualizacoes - SXB: Consultas Padroes"
		#define STR0103 "Coluna"
		#define STR0104 "Conteudo"
		#define STR0105 "Atualizacoes de rotinas"
		#define STR0106 "Status"
		#define STR0107 "Atualizacoes - SX1: Perguntas de parametrizacao"
		#define STR0108 "Grupo"
		#define STR0109 "Pergunte"
		#define STR0110 "Variável"
		#define STR0111 "Arquivo de LOG salvo com sucesso!"
		#define STR0112 "Erro na gravação do arquivo de Log "
		#define STR0113 "Update"
		#define STR0114 "Chamado/Tarefa"
		#define STR0115 "Selecione as Empresas para o processamento..."
		#define STR0116 "Correção na validação e propriedades do campo CAX_ID e da consulta padrão CAX"
		#define STR0117 "Correção de campos inconsistentes no Bloco M da ECF, no Cadastro do Registro M030. "
		#define STR0118 "Atencao!"
		#define STR0119 "Ocorreu um erro desconhecido durante a atualizacao da tabela : "
		#define STR0120 ". Verifique a integridade do dicionario e da tabela."
		#define STR0121 "Já existe parâmetro na base."
		#define STR0122 "Segue abaixo o seu conteúdo: "
		#define STR0123 "Sim"
		#define STR0124 "Não"
		#define STR0125 "Correção na consulta padrão para exibição dos modelos fiscais. "
		#define STR0126 "Modelo de Notas Fiscais"
		#define STR0127 "Atualização para atender o Manual de Orientação da ECF de Maio 2015."
		#define STR0128 "Alteração no índice 2 da tabela CFQ para inclusão do campo CFQ_PAIS."
		#define STR0129 "Correção dos relacionamentos do ECF, referente a tabela C1O."
		#define STR0130 "Relacionamentos "
		#define STR0131 "Dominio: "
		#define STR0132 "Atualizacoes - SX9: Relacionamentos"
		#define STR0133 "Remoção do botão de inclusão/alteração da consulta padrão CZV."
		#define STR0134 "Correção de erro na consulta padrão 'Tipos de Bairro' "
		#define STR0135 "Tipos de Bairro"
		#define STR0136 "Tipo de Combustivel Veicular"
		#define STR0137 "Alteração do Indice da Coluna"
		#define STR0138 "Codigo"
		#define STR0139 "Descrição"
		#define STR0140 "ID"
		#define STR0141 "Inclusão da Rotina de Domínio da Consulta"
		#define STR0142 "Atualizações - SX6: Parâmetros"
		#define STR0143 "Correção da consulta padrão do campo CM4_TRABAL e a inicialização padrão do campo CM4_DTRABA na rotina de Aviso Prévio."
		#define STR0144 "Correção da consulta padrão do campo CMC_TRABAL e a inicialização padrão do campo CMC_DTRABA."
		#define STR0145 "Correção na inclusão das notas de entrada e saída."
		#define STR0146 "Adequação do Tamanho do campo 'C1E_CODFIL' utilizado no relacionamento com as tabelas compartilhadas."
		#define STR0147 "Ajuste na descrição, tamanho e casas decimais do campo CFV_TXJUR."
	#endif
#endif
