#ifdef SPANISH
	#define STR0001 "Apanhe"
	#define STR0002 "Reabastecimento"
	#define STR0003 "Vaya a la dirección"
	#define STR0004 "Deseja encerrar o [VAR01]?"
	#define STR0005 "Sim"
	#define STR0006 "Não"
	#define STR0007 "Endereço"
	#define STR0008 "Confirme!"
	#define STR0009 "Pegue o produto"
	#define STR0010 "Quantidade"
	#define STR0011 "Ultrapassou o total!"
	#define STR0012 "Lote [VAR01] não consta no documento atual."
	#define STR0013 "Leve para o endereço"
	#define STR0014 "Problema no [VAR01]!"
	#define STR0015 "Lote [VAR01] sem saldo disponivel."
	#define STR0016 "Unidade p/ [VAR01]?"
	#define STR0017 "Produto [VAR01] não consta no documento atual."
	#define STR0018 "Lote"
	#define STR0019 "Endereço incorreto"
	#define STR0020 "Qtde"
	#define STR0021 "Etiqueta inválida!"
	#define STR0022 "Processando..."
	#define STR0023 "Info. Carga"
	#define STR0024 "Docto: [VAR01]"
	#define STR0025 "Carga..: [VAR01]"
	#define STR0026 "Unitizador:"
	#define STR0027 "Informe el sublote"
	#define STR0028 "Sub-Lote [VAR01] não consta no documento atual."
	#define STR0029 "Sub-Lote"
	#define STR0030 "Finalizar"
	#define STR0031 "Total"
	#define STR0032 "Separada"
	#define STR0033 "Finalizar atividade com quantidade inferior?"
	#define STR0034 "Deseja alterar o lote?"
	#define STR0035 "Atividade está aglutinada, não permite movimentar parcial."
	#define STR0036 "Separar quantidade superior?"
	#define STR0037 "Pedido.: [VAR01]"
	#define STR0038 "Cliente: [VAR01]"
	#define STR0039 "Número do lote alterado."
	#define STR0040 "Não foi possível efetuar a alteração."
	#define STR0041 "Produto [VAR01]"
	#define STR0042 "Quant."
	#define STR0043 "Lotes a separar"
	#define STR0044 "Atenção!"
	#define STR0045 "Encerrar"
	#define STR0046 "Dirección destino"
	#define STR0047 "Para [VAR01] com unitizador a quantidade não pode ser menor que um."
	#define STR0048 "Saldo no endereço [VAR01] insuficiente para a retirada!"
	#define STR0049 "Etiqueta"
	#define STR0050 "Etiqueta já informada!"
	#define STR0051 "Produto: [VAR01] é componente do produto: [VAR02] e não pode ter a quantidade alterada!"
	#define STR0052 "Não permitido o cancelamento total da separação. Utilize o estorno do monitor de serviço"
	#define STR0053 "Atividade está aglutinada, não permite o cancelamento parcial da separação. Utilize o estorno do monitor de serviço"
	#define STR0054 "Volume.: [VAR01]"
	#define STR0055 "Informe el volumen"
	#define STR0056 "Volumen actual"
	#define STR0057 "Lote [VAR01]"
	#define STR0058 "Qtd [VAR01] já coletado. Faltando apenas finalizar atividade."
	#define STR0059 "Volume"
	#define STR0060 "Endereço possui saldo de [VAR01]."
	#define STR0061 "No tiene porcentaje de tolerancia de separación a más registrado."
	#define STR0062 "Solamente en la primera actividad podrá separarse una cantidad mayor que la solicitada."
	#define STR0063 "Actividad está agrupada, no permite separar cantidad diferente de la solicitada."
	#define STR0064 "Total supera la cantidad de tolerancia a más para la orden de servicio."
#else
	#ifdef ENGLISH
		#define STR0001 "To sort"
		#define STR0002 "Refueling"
		#define STR0003 "Go to the address"
		#define STR0004 "Do you want to close the [VAR01]?"
		#define STR0005 "Yes"
		#define STR0006 "No"
		#define STR0007 "Address"
		#define STR0008 "Confirm!"
		#define STR0009 "Take the product"
		#define STR0010 "Quantity"
		#define STR0011 "Total was exceeded!"
		#define STR0012 "Lot [VAR01] is not in the current document."
		#define STR0013 "Take to the address"
		#define STR0014 "Problem in [VAR01]!"
		#define STR0015 "Lot [VAR01] without available balance."
		#define STR0016 "Unit f/ [VAR01]?"
		#define STR0017 "Product [VAR01] is not in the current document."
		#define STR0018 "Batch"
		#define STR0019 "Incorrect address"
		#define STR0020 "Qty."
		#define STR0021 "Label not valid!"
		#define STR0022 "Processing..."
		#define STR0023 "Load Info."
		#define STR0024 "Doc: [VAR01]"
		#define STR0025 "Load..: [VAR01]"
		#define STR0026 "Unitizer:"
		#define STR0027 "Enter the Sublot"
		#define STR0028 "Sublot [VAR01] is not in the current document."
		#define STR0029 "Sublot"
		#define STR0030 "Finish"
		#define STR0031 "Total"
		#define STR0032 "Separate"
		#define STR0033 "Finish activity with lower amount?"
		#define STR0034 "Do you want to change the lot?"
		#define STR0035 "The activity is grouped, partial movement is not possible."
		#define STR0036 "Separate superior amount?"
		#define STR0037 "Order.: [VAR01]"
		#define STR0038 "Customer: [VAR01]"
		#define STR0039 "Number of changed lot."
		#define STR0040 "Could not execute change."
		#define STR0041 "Product [VAR01]"
		#define STR0042 "Qty."
		#define STR0043 "Lots to separate"
		#define STR0044 "Attention!"
		#define STR0045 "Close"
		#define STR0046 "Destination address"
		#define STR0047 "For [VAR01] with unitizer, the quantity cannot be smaller than one."
		#define STR0048 "Balance in address [VAR01] not enough for pick-up!"
		#define STR0049 "Label"
		#define STR0050 "Label already entered!"
		#define STR0051 "Product: [VAR01] is a component of the product: [VAR02] and you cannot change its quantity!"
		#define STR0052 "Total cancellation of sorting not allowed! Use service monitor reversal"
		#define STR0053 "Activity is grouped, not allowing partial cancellation of sorting. Use service monitor reversal"
		#define STR0054 "Volume.: [VAR01]"
		#define STR0055 "Enter the volume"
		#define STR0056 "Current volume"
		#define STR0057 "Batch [VAR01]"
		#define STR0058 "Qty [VAR01] already collected. You must only close the activity."
		#define STR0059 "Volume"
		#define STR0060 "Address has balance of [VAR01]."
		#define STR0061 "Has no separation tolerance percentage to greater registered."
		#define STR0062 "Only on the first activity a greater amount than the requested can be separated."
		#define STR0063 "Activity is grouped, not allowing to separate a different amount of the requested."
		#define STR0064 "The total exceeds the tolerance amount to greater for the service order."
	#else
		#define STR0001 "Apanhe"
		#define STR0002 "Reabastecimento"
		#define STR0003 "Va para o endereço"
		#define STR0004 "Deseja encerrar o [VAR01]?"
		#define STR0005 "Sim"
		#define STR0006 "Não"
		#define STR0007 "Endereço"
		#define STR0008 "Confirme!"
		#define STR0009 "Pegue o produto"
		#define STR0010 "Quantidade"
		#define STR0011 "Ultrapassou o total!"
		#define STR0012 "Lote [VAR01] não consta no documento atual."
		#define STR0013 "Leve para o endereço"
		#define STR0014 "Problema no [VAR01]!"
		#define STR0015 "Lote [VAR01] sem saldo disponivel."
		#define STR0016 "Unidade p/ [VAR01]?"
		#define STR0017 "Produto [VAR01] não consta no documento atual."
		#define STR0018 "Lote"
		#define STR0019 "Endereço incorreto"
		#define STR0020 "Qtde"
		#define STR0021 "Etiqueta inválida!"
		#define STR0022 "Processando..."
		#define STR0023 "Info. carga"
		#define STR0024 "Docto: [VAR01]"
		#define STR0025 "Carga..: [VAR01]"
		#define STR0026 "Unitizador:"
		#define STR0027 "Informe o sub-Lote"
		#define STR0028 "Sub-Lote [VAR01] não consta no documento atual."
		#define STR0029 "Sub-Lote"
		#define STR0030 "Finalizar"
		#define STR0031 "Total"
		#define STR0032 "Separada"
		#define STR0033 "Finalizar atividade com quantidade inferior?"
		#define STR0034 "Deseja alterar o lote?"
		#define STR0035 "Atividade está aglutinada, não permite movimentar parcial."
		#define STR0036 "Separar quantidade superior?"
		#define STR0037 "Pedido.: [VAR01]"
		#define STR0038 "Cliente: [VAR01]"
		#define STR0039 "Número do lote alterado."
		#define STR0040 "Não foi possível efetuar a alteração."
		#define STR0041 "Produto [VAR01]"
		#define STR0042 "Quant."
		#define STR0043 "Lotes a separar"
		#define STR0044 "Atenção!"
		#define STR0045 "Encerrar"
		#define STR0046 "Endereço destino"
		#define STR0047 "Para [VAR01] com unitizador a quantidade não pode ser menor que um."
		#define STR0048 "Saldo no endereço [VAR01] insuficiente para a retirada!"
		#define STR0049 "Etiqueta"
		#define STR0050 "Etiqueta já informada!"
		#define STR0051 "Produto: [VAR01] é componente do produto: [VAR02] e não pode ter a quantidade alterada!"
		#define STR0052 "Não permitido o cancelamento total da separação. Utilize o estorno do monitor de serviço"
		#define STR0053 "Atividade está aglutinada, não permite o cancelamento parcial da separação. Utilize o estorno do monitor de serviço"
		#define STR0054 "Volume.: [VAR01]"
		#define STR0055 "Informe o volume"
		#define STR0056 "Volume atual"
		#define STR0057 "Lote [VAR01]"
		#define STR0058 "Qtd [VAR01] já coletado. Faltando apenas finalizar atividade."
		#define STR0059 "Volume"
		#define STR0060 "Endereço possui saldo de [VAR01]."
		#define STR0061 "Não possui percentual de tolerancia de separação a maior cadastrado."
		#define STR0062 "Somente na primeira atividade poderá ser separado uma quantidade maior que a solicitada."
		#define STR0063 "Atividade está aglutinada, não permite separar quantidade diferente da solicitada."
		#define STR0064 "Total ultrapassa a quantidade de tolerância a maior para a ordem de serviço."
	#endif
#endif
