#ifdef SPANISH
	#define STR0001 "O.S.WMS "
	#define STR0002 "Producto "
	#define STR0003 "Si se informa el servicio WMS, el almacén origen no puede ser diferente del almacén destino."
	#define STR0004 " "
	#define STR0005 "OCURRENCIA EN LA DEVOLUCION"
	#define STR0006 "Servicio :"
	#define STR0007 "Carga : "
	#define STR0008 "Documento : "
	#define STR0009 "Lote : "
	#define STR0010 "Cantidad: "
	#define STR0011 "El sistema intento transferir de direccion "
	#define STR0012 " para la direccion "
	#define STR0013 "mas la direccion"
	#define STR0014 " ya esta "
	#define STR0015 " con "
	#define STR0016 " exceso en la capacidad de almacenaje."
	#define STR0017 "Verifique el estatus de direccion "
	#define STR0018 ", pues esta "
	#define STR0019 "La direccion destino [VAR01] está bloqueada."
	#define STR0020 "Estructura física [VAR01] no registrada. (DC8)"
	#define STR0021 "Producto [VAR01] no tiene secuencia de abastecimiento para Almacén/Estructura [VAR02]/[VAR03]. (DC3)"
	#define STR0022 "Producto [VAR01] no está registrado para la zona de almacenamiento [VAR02]. (SB5,DCH)"
	#define STR0023 "Movimiento de [VAR01] para la direccion [VAR02] excediendo la capacidad de almacenamiento."
	#define STR0024 "Capacidad total de la direccion de [VAR01]."
	#define STR0025 "Direccion con saldo de [VAR01]."
	#define STR0026 "Movimentação WMS (Saída) pendente de [VAR01]."
	#define STR0027 "Otro producto esta utilizando la direccion [VAR01]."
	#define STR0028 " Actual:"
	#define STR0029 " Diferencia:"
	#define STR0030 " Obs. "
	#define STR0031 "¿Libera la RUA ?"
	#define STR0032 "Si"
	#define STR0033 "No"
	#define STR0034 "Solo servicios de SALIDA pueden digitarse para este tipo de movimiento."
	#define STR0035 "Solo servicios de ENTRADA pueden digitarse para este tipo de movimiento."
	#define STR0036 "Ok"
	#define STR0037 "Dispositivo Móvil"
	#define STR0038 "Etiqueta"
	#define STR0039 "Dispositivo no encontrado..."
	#define STR0040 "¡Etiqueta ya informada!"
	#define STR0041 "¡No fue posible realizar el servicio!"
	#define STR0042 "Producto sin saldo disponible en las Estructuras Fisicas informadas en la Secuencia de Abastecimiento"
	#define STR0043 "Cantidad de Recoleccion Minima en la Secuencia de Abastecimiento incorrecta."
	#define STR0044 "Reabastecimientos pendientes que deben ejecutarse"
	#define STR0045 "No encontro una direccion de picking para efectuar la recoleccion."
	#define STR0046 "Crear la clave de indice"
	#define STR0047 "Parametro"
	#define STR0048 "en uso..."
	#define STR0049 "no encontrado..."
	#define STR0050 "Seleccionando registros..."
	#define STR0051 "WMS1 - > Direccion invalida."
	#define STR0052 "WMS2 - > Direccion informada para el producto es de uso exclusivo de un"
	#define STR0053 "WMS3 - > Estructura fisica de la direccion no registrada en la secuencia de"
	#define STR0054 "WMS4 - > Zona de almacenaje invalida."
	#define STR0055 "          otro producto."
	#define STR0056 "          abastecimiento del producto."
	#define STR0057 "No se puede clasificar una factura sin que su respectiva verificacion se haya finalizado."
	#define STR0058 "SIGAWMS"
	#define STR0059 "Solamente servicios WMS de transferencia pueden utilizarse."
	#define STR0060 "Solamente servicios de WMS del tipo 'Mov.Interna' pueden utilizarse."
	#define STR0061 "Si se informa el servicio WMS, el código del producto origen no puede ser diferente del código del producto destino."
	#define STR0062 "Direccion destino sin estructura registrada."
	#define STR0063 "¡Para transferencias con servicio WMS se necesita informar numero de documento!"
	#define STR0064 "Otro lote esta utilizando la direccion [VAR01]."
	#define STR0065 "La direccion origen [VAR01] esta bloqueada."
	#define STR0066 "Existen actividades por ejecutar que comprometen el saldo del producto [VAR01] en la direccion [VAR02]."
	#define STR0067 "Para ordenes de servicio de control de ubicacion con problemas, ejecute manualmente las ordenes de servicio interrumpidas y analice el informe de búsqueda de direccion."
	#define STR0068 "Para ordenes de servicio de expedicion con problemas, ejecute manualmente las ordenes de servicio interrumpidas y analice el informe de busqueda de saldo."
	#define STR0069 "Archivos texto (*.TXT) |*.txt|"
	#define STR0070 "Grabar como..."
	#define STR0071 "Para transferencias con servicio WMS es necesario que el almacén origen sea el mismo que el almacén destino."
#else
	#ifdef ENGLISH
		#define STR0001 "WMS S.O."
		#define STR0002 "Product "
		#define STR0003 "When you enter the WMS service, the source warehouse cannot be different from the target warehouse."
		#define STR0004 ""
		#define STR0005 "OCCURRENCE IN REVERSAL "
		#define STR0006 "Service: "
		#define STR0007 "Load:  "
		#define STR0008 "Document:  "
		#define STR0009 "Lot:  "
		#define STR0010 "Amount:  "
		#define STR0011 "The system tried to transfer from address "
		#define STR0012 " to address  "
		#define STR0013 "but the address "
		#define STR0014 " is already"
		#define STR0015 " with "
		#define STR0016 " storage capacity exceeded. "
		#define STR0017 "Check the address status  "
		#define STR0018 " because this "
		#define STR0019 "destination address [VAR01] blocked."
		#define STR0020 "Physical structure [VAR01] not registered. (DC8)"
		#define STR0021 "Product [VAR01] has no supply sequence for Warehouse/Structure [VAR02]/[VAR03]. (DC3)"
		#define STR0022 "Product [VAR01] not registered for storage zone [VAR02]. (SB5,DCH)"
		#define STR0023 "Movement of [VAR01] for address [VAR02] exceeding storage capacity."
		#define STR0024 "Total capacity of address of [VAR01]."
		#define STR0025 "Address has balance of [VAR01]."
		#define STR0026 "WMS movement (Outflow) of [VAR01] pending."
		#define STR0027 "Address [VAR01] in use by another product."
		#define STR0028 " Current:"
		#define STR0029 " Difference:"
		#define STR0030 " Note: "
		#define STR0031 "Release STREET?"
		#define STR0032 "Yes"
		#define STR0033 "No"
		#define STR0034 "You can only enter OUTFLOW services for this transaction type"
		#define STR0035 "You can only enter INFLOW services for this transaction type"
		#define STR0036 "OK"
		#define STR0037 "Mobile Device"
		#define STR0038 "Label"
		#define STR0039 "Device not found..."
		#define STR0040 "Label already entered!"
		#define STR0041 "Service could not be performed!"
		#define STR0042 "Product with no available balance on the entered Physical Structures on Supply Sequence"
		#define STR0043 "Amount of Minimum Pick-Up on Supply Sequence is not correct"
		#define STR0044 "Pending Resupply that need to be run"
		#define STR0045 "Picking address not found to perform pick up"
		#define STR0046 "Create index key"
		#define STR0047 "Parameter"
		#define STR0048 "in use..."
		#define STR0049 "not found..."
		#define STR0050 "Selecting Records..."
		#define STR0051 "WMS1 - > Invalid address."
		#define STR0052 "WMS2 - > Address indicated for product is of exclusive use of a"
		#define STR0053 "WMS3 - > Physical structure of address not registered in the sequence of"
		#define STR0054 "WMS4 - > Storage Zone invalid."
		#define STR0055 "          other product."
		#define STR0056 "          supply of product."
		#define STR0057 "You cannot classify an invoice without finishing its respective checking."
		#define STR0058 "SIGAWMS"
		#define STR0059 "You can only use WMS Transfer services."
		#define STR0060 "Only WMS services of type 'Internal Mov.' can be used."
		#define STR0061 "When you enter the WMS service, the source product code cannot be different from the target product code."
		#define STR0062 "Destination address without registered structure."
		#define STR0063 "Enter document number for transfers with WMS service!"
		#define STR0064 "Address [VAR01] in use by another lot."
		#define STR0065 "Origin address [VAR01] blocked."
		#define STR0066 "There are activities to run that compromise product balance [VAR01] in address [VAR02]."
		#define STR0067 "For addressing service orders with problems, run interrupted service orders manually and analyze the address search report."
		#define STR0068 "For dispatch service orders with problems, run interrupted service orders manually and analyze the balance search report."
		#define STR0069 "Text files (*.TXT) |*.txt|"
		#define STR0070 "Save As..."
		#define STR0071 "For WMS service transfers, the source warehouse must be the same as the target warehouse."
	#else
		#define STR0001 If( cPaisLoc $ "ANG|PTG", "O.s.wms ", "O.S.WMS " )
		#define STR0002 "Produto "
		#define STR0003 "Quando informado serviço WMS o armazém origem não pode ser diferente do armazém destino."
		#define STR0004 ""
		#define STR0005 If( cPaisLoc $ "ANG|PTG", "Ocorrência No Devolução", "OCORRENCIA NO ESTORNO" )
		#define STR0006 "Serviço : "
		#define STR0007 "Carga : "
		#define STR0008 "Documento : "
		#define STR0009 "Lote : "
		#define STR0010 "Quantidade: "
		#define STR0011 If( cPaisLoc $ "ANG|PTG", "O sistema tentou transferir da morada ", "O sistema tentou transferir do endereço " )
		#define STR0012 If( cPaisLoc $ "ANG|PTG", " para a morada ", " para o endereço " )
		#define STR0013 If( cPaisLoc $ "ANG|PTG", "Mas a morada ", "mas o endereço " )
		#define STR0014 If( cPaisLoc $ "ANG|PTG", " já está ", " ja esta " )
		#define STR0015 " com "
		#define STR0016 If( cPaisLoc $ "ANG|PTG", " a exceder a capacidade de armazenamento.", " excedendo a capacidade de armazenagem." )
		#define STR0017 If( cPaisLoc $ "ANG|PTG", "Verificar o estado da morada ", "Verifique o status do endereço " )
		#define STR0018 If( cPaisLoc $ "ANG|PTG", ", pois está ", ", pois esta " )
		#define STR0019 "O endereço destino [VAR01] está bloqueado."
		#define STR0020 "Estrutura física [VAR01] não cadastrada. (DC8)"
		#define STR0021 "Produto [VAR01] não possui sequência de abastecimento para Armazém/Estrutura [VAR02]/[VAR03]. (DC3)"
		#define STR0022 "Produto [VAR01] não está cadastrado para a zona armazenagem [VAR02]. (SB5,DCH)"
		#define STR0023 "Movimentação de [VAR01] para o endereço [VAR02] excedendo a capacidade de armazenagem."
		#define STR0024 "Capacidade total do endereço de [VAR01]."
		#define STR0025 "Endereço possui saldo de [VAR01]."
		#define STR0026 "Movimentação WMS (Saída) pendente de [VAR01]."
		#define STR0027 "Endereço [VAR01] em uso por outro produto."
		#define STR0028 " Atual:"
		#define STR0029 " Diferenca:"
		#define STR0030 " Obs: "
		#define STR0031 "Libera a RUA ?"
		#define STR0032 "Sim"
		#define STR0033 "Nao"
		#define STR0034 "Somente serviços de SAÍDA podem ser digitados para este tipo de movimentação"
		#define STR0035 "Somente serviços de ENTRADA podem ser digitados para este tipo de movimentação"
		#define STR0036 "Ok"
		#define STR0037 "Dispositivo Móvel"
		#define STR0038 "Etiqueta"
		#define STR0039 "Dispositivo nao encontrado..."
		#define STR0040 "Etiqueta ja informada!"
		#define STR0041 "Nao foi possivel realizar o servico!"
		#define STR0042 "Produto sem saldo disponivel nas Estruturas Fisicas informadas na Sequencia de Abastecimento"
		#define STR0043 "Quantidade do Apanhe Minimo na Sequencia de Abastecimento incorreta"
		#define STR0044 "Reabastecimentos pendentes que precisam ser executados"
		#define STR0045 "Nao encontrou um endereco de picking para efetuar o apanhe"
		#define STR0046 "Criar a chave de indice"
		#define STR0047 "Parametro"
		#define STR0048 "em uso..."
		#define STR0049 "nao encontrado..."
		#define STR0050 "Selecionando Registros..."
		#define STR0051 "WMS1 - > Endereço inválido."
		#define STR0052 "WMS2 - > Endereço informado para o produto é de uso exclusivo de um"
		#define STR0053 "WMS3 - > Estrutura física do endereço não cadastrada na sequencia de"
		#define STR0054 "WMS4 - > Zona de Armazenagem inválida."
		#define STR0055 "          outro produto."
		#define STR0056 "          abastecimento do produto."
		#define STR0057 "Não é possível classificar uma nota sem que a sua respectiva conferência tenha sido finalizada."
		#define STR0058 "SIGAWMS"
		#define STR0059 "Somente serviços WMS de transferência podem ser utilizados."
		#define STR0060 "Somente serviços de WMS do tipo 'Mov.Interna' podem ser utilizados."
		#define STR0061 "Quando informado serviço WMS o código do produto origem não pode ser diferente do código do produto destino."
		#define STR0062 "Endereço destino sem estrutura cadastrada."
		#define STR0063 "Para transferências com serviço WMS é necessário informar número de documento!"
		#define STR0064 "Endereço [VAR01] em uso por outro lote."
		#define STR0065 "O endereço origem [VAR01] está bloqueado."
		#define STR0066 "Existem atividades a executar que comprometem o saldo do produto [VAR01] no endereço [VAR02]."
		#define STR0067 "Para ordens de serviço de endereçamento com problemas, execute manual as ordens de serviço interrompidas e analise o relatório de busca de endereço."
		#define STR0068 "Para ordens de serviço de expedição com problemas, execute manual as ordens de serviço interrompidas e analise o relatório de busca de saldo."
		#define STR0069 "Arquivos Texto (*.TXT) |*.txt|"
		#define STR0070 "Salvar como..."
		#define STR0071 "Para transferências com serviço WMS é necessário que o armazém origem seja o mesmo que o armazém destino."
	#endif
#endif
